//====================================================================================================================================================
// Copyright 2026 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
// This file was automatically generated by the Team 302 code generator version 2026.1.0

// FRC Includes
#include "frc/DriverStation.h"
#include "frc2/command/Commands.h"
#include "networktables/NetworkTableInstance.h"

#include "mechanisms/intake/Intake.h"
#include "state/RobotState.h"
#include "teleopcontrol/TeleopControl.h"
#include "utils/logging/debug/Logger.h"
#include "utils/logging/signals/DragonDataLogger.h"

#include "ctre/phoenix6/TalonFX.hpp"
#include "ctre/phoenix6/TalonFXS.hpp"
#include "ctre/phoenix6/configs/Configuration.hpp"

using ctre::phoenix6::configs::CANdiConfiguration;
using ctre::phoenix6::configs::TalonFXConfiguration;
using ctre::phoenix6::configs::TalonFXSConfiguration;

using std::string;

Intake::Intake(RobotIdentifier id) : BaseMechSubsystem(MechanismTypes::MECHANISM_TYPE::INTAKE, std::string("Intake")),
									 m_activeRobotId(id),
									 m_stateMap(),
									 m_autonCommand(frc2::cmd::None())
{
	RobotState::GetInstance()->RegisterForStateChanges(this, RobotStateChanges::StateChange::ClimbModeStatus_Bool);
	RobotState::GetInstance()->RegisterForStateChanges(this, RobotStateChanges::StateChange::IsLaunching_Bool);
	m_extenderPositionDeg.EnableFOC = true;
}

std::map<std::string, Intake::STATE_NAMES>
	Intake::stringToSTATE_NAMESEnumMap{
		{"STATE_OFF", Intake::STATE_NAMES::STATE_OFF},
		{"STATE_INTAKE", Intake::STATE_NAMES::STATE_INTAKE},
		{"STATE_EXPEL", Intake::STATE_NAMES::STATE_EXPEL},
		{"STATE_LAUNCH", Intake::STATE_NAMES::STATE_LAUNCH},
		{"STATE_LOAD_HOPPER", Intake::STATE_NAMES::STATE_LOAD_HOPPER}};

std::map<Intake::STATE_NAMES, std::string>
	Intake::STATE_NAMESEnumToStringMap{
		{Intake::STATE_NAMES::STATE_OFF, "STATE_OFF"},
		{Intake::STATE_NAMES::STATE_INTAKE, "STATE_INTAKE"},
		{Intake::STATE_NAMES::STATE_EXPEL, "STATE_EXPEL"},
		{Intake::STATE_NAMES::STATE_LAUNCH, "STATE_LAUNCH"},
		{Intake::STATE_NAMES::STATE_LOAD_HOPPER, "STATE_LOAD_HOPPER"}};

void Intake::CreateCompBot302()
{
	m_ntName = "Intake";
	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, string("Initializing mechanism"), string("Intake for COMPBOT_302"), "");

	// --- Hardware Setup ---
	m_intakeMotor = new ctre::phoenix6::hardware::TalonFX(16, ctre::phoenix6::CANBus("canivore"));
	m_extenderMotor = new ctre::phoenix6::hardware::TalonFXS(11, ctre::phoenix6::CANBus("canivore"));
	m_extenderCANdi = new ctre::phoenix6::hardware::CANdi(11, ctre::phoenix6::CANBus("canivore"));

	// --- Control Data Setup ---
	m_percentOut = new ControlData(
		"m_percentOut",											 // std::string indentifier
		0.0,													 // double proportional
		0.0,													 // double integral
		0.0,													 // double derivative
		0.0,													 // double feedforward
		0.0,													 // double velocityGain
		0.0,													 // double accelartionGain
		0.0,													 // double staticFrictionGain,
		0.0,													 // double integralZone
		0.0,													 // double maxAcceleration
		0.0,													 // double cruiseVelocity
		ControlData::GravityTypeValue::Elevator_Static,			 // Gravity type
		ControlData::StaticFeedforwardSignValue::UseVelocitySign // Static feedforward sign
	);
	m_positionDeg = new ControlData(
		"m_positionDeg",										 // std::string indentifier
		1.0,													 // double proportional
		0.5,													 // double integral
		0.0,													 // double derivative
		1.0,													 // double feedforward
		0.0,													 // double velocityGain
		0.0,													 // double accelartionGain
		0.0,													 // double staticFrictionGain,
		0.0,													 // double integralZone
		300.0,													 // double maxAcceleration
		150.0,													 // double cruiseVelocity
		ControlData::GravityTypeValue::Arm_Cosine,				 // Gravity type
		ControlData::StaticFeedforwardSignValue::UseVelocitySign // Static feedforward sign
	);

	ReadConstants("Intake.xml", 302);
}

void Intake::InitializeCompBot302()
{
	// Initializtion Mehtods of all of the hardware in this robot
	InitializeTalonFXIntakeCompBot302();
	InitializeTalonFXSExtenderCompBot302();
	InitializeCANdiExtenderCompBot302();
}

// All of the Initializtion Mehtods for all of the robots

void Intake::InitializeTalonFXIntakeCompBot302()
{
	TalonFXConfiguration configs{};
	configs.CurrentLimits.StatorCurrentLimit = units::current::ampere_t(120.0);
	configs.CurrentLimits.StatorCurrentLimitEnable = true;
	configs.CurrentLimits.SupplyCurrentLimit = units::current::ampere_t(70.0);
	configs.CurrentLimits.SupplyCurrentLimitEnable = true;
	configs.CurrentLimits.SupplyCurrentLowerLimit = units::current::ampere_t(35.0);
	configs.CurrentLimits.SupplyCurrentLowerTime = units::time::second_t(0.0);

	configs.Voltage.PeakForwardVoltage = units::voltage::volt_t(11.0);
	configs.Voltage.PeakReverseVoltage = units::voltage::volt_t(-11.0);
	configs.ClosedLoopRamps.TorqueClosedLoopRampPeriod = units::time::second_t(0.25);
	configs.OpenLoopRamps.DutyCycleOpenLoopRampPeriod = units::time::second_t(0.1);

	configs.HardwareLimitSwitch.ForwardLimitEnable = false;
	configs.HardwareLimitSwitch.ForwardLimitRemoteSensorID = 0;
	configs.HardwareLimitSwitch.ForwardLimitAutosetPositionEnable = false;
	configs.HardwareLimitSwitch.ForwardLimitAutosetPositionValue = units::angle::turn_t(0.0);
	configs.HardwareLimitSwitch.ForwardLimitSource = ctre::phoenix6::signals::ForwardLimitSourceValue::Disabled;
	configs.HardwareLimitSwitch.ForwardLimitType = ctre::phoenix6::signals::ForwardLimitTypeValue::NormallyOpen;

	configs.HardwareLimitSwitch.ReverseLimitEnable = false;
	configs.HardwareLimitSwitch.ReverseLimitRemoteSensorID = 0;
	configs.HardwareLimitSwitch.ReverseLimitAutosetPositionEnable = false;
	configs.HardwareLimitSwitch.ReverseLimitAutosetPositionValue = units::angle::turn_t(0.0);
	configs.HardwareLimitSwitch.ReverseLimitSource = ctre::phoenix6::signals::ReverseLimitSourceValue::Disabled;
	configs.HardwareLimitSwitch.ReverseLimitType = ctre::phoenix6::signals::ReverseLimitTypeValue::NormallyClosed;

	configs.MotorOutput.Inverted = ctre::phoenix6::signals::InvertedValue::CounterClockwise_Positive;
	configs.MotorOutput.NeutralMode = ctre::phoenix6::signals::NeutralModeValue::Coast;
	configs.MotorOutput.PeakForwardDutyCycle = 1.0;
	configs.MotorOutput.PeakReverseDutyCycle = -1.0;
	configs.MotorOutput.DutyCycleNeutralDeadband = 0.0;

	configs.Feedback.FeedbackSensorSource = ctre::phoenix6::signals::FeedbackSensorSourceValue::RotorSensor;
	configs.Feedback.SensorToMechanismRatio = 1.0;

	ctre::phoenix::StatusCode status = ctre::phoenix::StatusCode::StatusCodeNotInitialized;
	for (int i = 0; i < 5; ++i)
	{
		status = m_intakeMotor->GetConfigurator().Apply(configs, units::time::second_t(0.25));
		if (status.IsOK())
			break;
	}
	if (!status.IsOK())
		Logger::GetLogger()->LogData(LOGGER_LEVEL::ERROR, "m_intakeMotor", "m_intakeMotor Status", status.GetName());
}

void Intake::InitializeTalonFXSExtenderCompBot302()
{
	TalonFXSConfiguration configs{};
	configs.CurrentLimits.StatorCurrentLimit = units::current::ampere_t(35.0);
	configs.CurrentLimits.StatorCurrentLimitEnable = true;
	configs.CurrentLimits.SupplyCurrentLimit = units::current::ampere_t(70.0);
	configs.CurrentLimits.SupplyCurrentLimitEnable = true;
	configs.CurrentLimits.SupplyCurrentLowerLimit = units::current::ampere_t(35.0);
	configs.CurrentLimits.SupplyCurrentLowerTime = units::time::second_t(0.0);

	configs.Voltage.PeakForwardVoltage = units::voltage::volt_t(11.0);
	configs.Voltage.PeakReverseVoltage = units::voltage::volt_t(-11.0);
	configs.ClosedLoopRamps.VoltageClosedLoopRampPeriod = units::time::second_t(0.25);
	configs.OpenLoopRamps.VoltageOpenLoopRampPeriod = units::time::second_t(0.1);

	configs.HardwareLimitSwitch.ForwardLimitEnable = true;
	configs.HardwareLimitSwitch.ForwardLimitRemoteSensorID = 11;
	configs.HardwareLimitSwitch.ForwardLimitAutosetPositionEnable = false;
	configs.HardwareLimitSwitch.ForwardLimitAutosetPositionValue = units::angle::turn_t(102.8);
	configs.HardwareLimitSwitch.ForwardLimitSource = ctre::phoenix6::signals::ForwardLimitSourceValue::RemoteCANdiS2;
	configs.HardwareLimitSwitch.ForwardLimitType = ctre::phoenix6::signals::ForwardLimitTypeValue::NormallyOpen;

	configs.HardwareLimitSwitch.ReverseLimitEnable = true;
	configs.HardwareLimitSwitch.ReverseLimitRemoteSensorID = 11;
	configs.HardwareLimitSwitch.ReverseLimitAutosetPositionEnable = true;
	configs.HardwareLimitSwitch.ReverseLimitAutosetPositionValue = units::angle::turn_t(-8.0);
	configs.HardwareLimitSwitch.ReverseLimitSource = ctre::phoenix6::signals::ReverseLimitSourceValue::RemoteCANdiS1;
	configs.HardwareLimitSwitch.ReverseLimitType = ctre::phoenix6::signals::ReverseLimitTypeValue::NormallyOpen;

	configs.MotorOutput.Inverted = ctre::phoenix6::signals::InvertedValue::Clockwise_Positive;
	configs.MotorOutput.NeutralMode = ctre::phoenix6::signals::NeutralModeValue::Brake;
	configs.MotorOutput.PeakForwardDutyCycle = 1.0;
	configs.MotorOutput.PeakReverseDutyCycle = -1.0;
	configs.MotorOutput.DutyCycleNeutralDeadband = 0.0;

	configs.Commutation.MotorArrangement = ctre::phoenix6::signals::MotorArrangementValue::Minion_JST;

	configs.ExternalFeedback.ExternalFeedbackSensorSource = ctre::phoenix6::signals::FeedbackSensorSourceValue::RotorSensor;
	configs.ExternalFeedback.SensorToMechanismRatio = 0.1499023469387;

	configs.Slot0.kI = m_positionDeg->GetI();
	configs.Slot0.kD = m_positionDeg->GetD();
	configs.Slot0.kG = m_positionDeg->GetF();
	configs.Slot0.kS = m_positionDeg->GetS();
	configs.Slot0.kV = m_positionDeg->GetV();
	configs.Slot0.kP = m_positionDeg->GetP();
	configs.Slot0.kA = m_positionDeg->GetA();
	configs.Slot0.GravityType = ctre::phoenix6::signals::GravityTypeValue::Arm_Cosine;
	configs.Slot0.StaticFeedforwardSign = ctre::phoenix6::signals::StaticFeedforwardSignValue::UseVelocitySign;

	ctre::phoenix::StatusCode status = ctre::phoenix::StatusCode::StatusCodeNotInitialized;
	for (int i = 0; i < 5; ++i)
	{
		status = m_extenderMotor->GetConfigurator().Apply(configs, units::time::second_t(0.25));
		if (status.IsOK())
			break;
	}
	if (!status.IsOK())
		Logger::GetLogger()->LogData(LOGGER_LEVEL::ERROR, "m_extenderMotor", "m_extenderMotor Status", status.GetName());

	m_extenderMotor->SetPosition(102.8_tr);
}

void Intake::InitializeCANdiExtenderCompBot302()
{
	CANdiConfiguration CANdiConfig{};

	CANdiConfig.DigitalInputs.S1CloseState = ctre::phoenix6::signals::S1CloseStateValue::CloseWhenHigh;
	CANdiConfig.DigitalInputs.S1FloatState = ctre::phoenix6::signals::S1FloatStateValue::PullHigh;
	CANdiConfig.DigitalInputs.S2CloseState = ctre::phoenix6::signals::S2CloseStateValue::CloseWhenFloating;
	CANdiConfig.DigitalInputs.S2FloatState = ctre::phoenix6::signals::S2FloatStateValue::FloatDetect;

	ctre::phoenix::StatusCode status = ctre::phoenix::StatusCode::StatusCodeNotInitialized;
	for (int i = 0; i < 5; ++i)
	{
		status = m_extenderCANdi->GetConfigurator().Apply(CANdiConfig, units::time::second_t(0.25));
		if (status.IsOK())
			break;
	}
	if (!status.IsOK())
		Logger::GetLogger()->LogData(LOGGER_LEVEL::ERROR, "m_extenderCANdi", "m_extenderCANdi Status", status.GetName());
}

void Intake::SetCurrentState(int state, bool run)
{
	// Autonomous bridge: schedule the command that corresponds to the requested state.
	// Cancel the previous auton command first so its requirement on this subsystem is released
	// before the owning CommandPtr is replaced.
	m_autonCommand.Cancel();
	m_autonCommand = GetCommandForState(static_cast<STATE_NAMES>(state));
	if (run)
	{
		frc2::CommandScheduler::GetInstance().Schedule(m_autonCommand);
	}
}

void Intake::RefreshCachedData()
{
	m_cachedExtenderPositionDeg = m_extenderMotor->GetPosition().GetValue();
}

void Intake::Periodic()
{
	// This function is called once per loop by the CommandScheduler (all modes) before any
	// scheduled command's execute(). It performs the per-loop housekeeping that used to live
	// in StateMgr::RunCommonTasks(): refresh cached sensor data, apply manual control, and
	// push the active control requests to the motors.
	RefreshCachedData();
	Update();

	ManualControl();

	// Logging
	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, m_ntName, "State", GetCurrentStateName());
	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, m_ntName, "Intake Position", m_cachedExtenderPositionDeg.value());
	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, m_ntName, "Extender Target", m_extenderPositionDeg.Position.value());
}

/// @brief update the output to the mechanism using the current controller and target value(s)
/// @return void
void Intake::Update()
{
	m_intakeMotor->SetControl(*m_intakeActiveTarget);
	m_extenderMotor->SetControl(*m_extenderActiveTarget);
}

ControlData *Intake::GetControlData(string name)
{
	if (name.compare("m_percentOut") == 0)
		return m_percentOut;
	else if (name.compare("m_positionDeg") == 0)
		return m_positionDeg;
	return nullptr;
}

void Intake::DataLog(uint64_t timestamp)
{
	// Mechanism State
	LogStringData(timestamp, m_intakeStatePath, GetCurrentStateName());

	// Control Requests/Targets
	LogDoubleData(timestamp, m_loggingIntakeTargetPath, m_intakePercentOut.Output.value());
	LogStringData(timestamp, m_loggingIntakeControlRequest, std::string(m_intakeActiveTarget->GetName()));
	LogDoubleData(timestamp, m_loggingExtenderTargetPath, m_extenderPositionDeg.Position.value());
	LogDoubleData(timestamp, m_loggingExtenderPositionPath, m_cachedExtenderPositionDeg.value());
	LogStringData(timestamp, m_loggingExtenderControlRequest, std::string(m_extenderActiveTarget->GetName()));
}

void Intake::NotifyStateUpdate(RobotStateChanges::StateChange change, bool value)
{
	if (change == RobotStateChanges::StateChange::ClimbModeStatus_Bool)
	{
		m_isInClimbMode = value;
	}
	else if (change == RobotStateChanges::StateChange::IsLaunching_Bool)
	{
		m_isLaunching = value;
	}
}
void Intake::ManualControl()
{
	TeleopControl *controller = TeleopControl::GetInstance();
	if (controller != nullptr && frc::DriverStation::IsTeleop())
	{
		double manualExtenderPercent = m_percentModifier * (TeleopControl::GetInstance()->GetAxisValue(TeleopControlFunctions::MANUAL_INTAKE_IN) - TeleopControl::GetInstance()->GetAxisValue(TeleopControlFunctions::MANUAL_INTAKE_OUT));
		if (std::abs(manualExtenderPercent) > 0.05)
		{
			if ((m_cachedExtenderPositionDeg > m_protectExtenderPositionDegUp) && manualExtenderPercent > 0.0)
				UpdateTargetExtenderPercentOut(0.0);
			else
				UpdateTargetExtenderPercentOut(manualExtenderPercent);
		}
		else
		{
			if (GetCurrentState() == STATE_INTAKE || GetCurrentState() == STATE_EXPEL || GetCurrentState() == STATE_LAUNCH)
			{
				if (m_cachedExtenderPositionDeg < m_protectExtenderPositionDegDown)
				{
					UpdateTargetExtenderPercentOut(0.0);
				}
			}
			else
				UpdateTargetExtenderPercentOut(0.0);
		}
	}
}

void Intake::PublishIntakeMode(bool intaking)
{
	RobotState::GetInstance()->PublishStateChange(RobotStateChanges::StateChange::IsIntaking_Bool, intaking);
}