//====================================================================================================================================================
// Copyright 2026 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
// This file was automatically generated by the Team 302 code generator version 2026.1.0

#pragma once

#include <string>

// FRC Includes
#include <networktables/NetworkTable.h>

#include "RobotIdentifier.h"
#include "mechanisms/base/BaseMech.h"
#include "mechanisms/base/BaseMechSubsystem.h"
#include "mechanisms/configs/MechanismConfigMgr.h"
#include "mechanisms/configs/RobotElementNames.h"
#include "mechanisms/controllers/ControlData.h"
#include "state/IRobotStateChangeSubscriber.h"
#include "state/RobotStateChanges.h"

// Hardware Includes
#include "ctre/phoenix6/CANdi.hpp"
#include "ctre/phoenix6/TalonFX.hpp"
#include "ctre/phoenix6/TalonFXS.hpp"
#include "ctre/phoenix6/configs/Configuration.hpp"
#include "utils/logging/signals/DragonDataLogger.h"

// Intake command classes
#include "mechanisms/intake/commands/IntakeExpelCommand.h"
#include "mechanisms/intake/commands/IntakeIntakeCommand.h"
#include "mechanisms/intake/commands/IntakeLaunchCommand.h"
#include "mechanisms/intake/commands/IntakeLoadHopperCommand.h"
#include "mechanisms/intake/commands/IntakeOffCommand.h"

class Intake : public BaseMechSubsystem, public IRobotStateChangeSubscriber, public DragonDataLogger
{
public:
	enum STATE_NAMES
	{
		STATE_OFF,
		STATE_INTAKE,
		STATE_EXPEL,
		STATE_LAUNCH,
		STATE_LOAD_HOPPER,
	};

	Intake(RobotIdentifier id);
	Intake() = delete;
	~Intake() = default;

	// Creation Methods per Robot
	void CreateCompBot302();
	void InitializeCompBot302();

	static std::map<std::string, STATE_NAMES> stringToSTATE_NAMESEnumMap;
	static std::map<STATE_NAMES, std::string> STATE_NAMESEnumToStringMap;

	RobotIdentifier getActiveRobotId() { return m_activeRobotId; }

	void Periodic() override;
	void DataLog(uint64_t timestamp) override;

	// Command Getters
	frc2::CommandPtr GetOffCommand() { return IntakeCommands::IntakeOffCommand(this).ToPtr(); }
	frc2::CommandPtr GetIntakeCommand() { return IntakeCommands::IntakeIntakeCommand(this).ToPtr(); }
	frc2::CommandPtr GetExpelCommand() { return IntakeCommands::IntakeExpelCommand(this).ToPtr(); }
	frc2::CommandPtr GetLaunchCommand() { return IntakeCommands::IntakeLaunchCommand(this).ToPtr(); }
	frc2::CommandPtr GetLoadHopperCommand() { return IntakeCommands::IntakeLoadHopperCommand(this).ToPtr(); }

	/// @brief Map a STATE_NAMES value to the matching command (used by the autonomous bridge).
	frc2::CommandPtr GetCommandForState(STATE_NAMES state)
	{
		switch (state)
		{
		case STATE_INTAKE:
			return GetIntakeCommand();
		case STATE_EXPEL:
			return GetExpelCommand();
		case STATE_LAUNCH:
			return GetLaunchCommand();
		case STATE_LOAD_HOPPER:
			return GetLoadHopperCommand();
		case STATE_OFF:
		default:
			return GetOffCommand();
		}
	}

	// Update Target Methods
	void UpdateTargetIntakePercentOut(double percentOut)
	{
		m_intakePercentOut.Output = percentOut;
		m_intakeActiveTarget = &m_intakePercentOut;
	}
	void UpdateTargetExtenderPercentOut(double percentOut)
	{
		m_extenderPercentOut.Output = percentOut;
		m_extenderActiveTarget = &m_extenderPercentOut;
	}
	void UpdateTargetExtenderPositionDeg(units::angle::turn_t position)
	{
		m_extenderPositionDeg.Position = position;
		m_extenderActiveTarget = &m_extenderPositionDeg.WithSlot(0);
	}

	// Hardware Getters
	ctre::phoenix6::hardware::TalonFX *GetIntakeTalonFX() const { return m_intakeMotor; }
	ctre::phoenix6::hardware::TalonFXS *GetExtenderTalonFXS() const { return m_extenderMotor; }
	ctre::phoenix6::hardware::CANdi *GetExtenderCANdi() const { return m_extenderCANdi; }

	// ControlData Getters
	ControlData *GetPercentOutControlData() const { return m_percentOut; }
	ControlData *GetPositionDegControlData() const { return m_positionDeg; }

	/// @brief Autonomous bridge: schedule the command matching the requested state.
	/// @details Keeps the same signature the old StateMgr exposed so CyclePrimitives and
	///          the auton XML pipeline continue to work unchanged.
	void SetCurrentState(int state, bool run);

	/// @brief Set the active mode tracker. Used by the Intake command classes in their Initialize().
	void SetCurrentState(int mode) { m_currentState = mode; }

	std::string GetCurrentStateName()
	{
		STATE_NAMES state = static_cast<STATE_NAMES>(GetCurrentState());
		return (STATE_NAMESEnumToStringMap.find(state) == STATE_NAMESEnumToStringMap.end()) ? "Unknown State" : STATE_NAMESEnumToStringMap.at(state);
	}

	int GetCurrentState() const { return m_currentState; }

	// --- Handwritten Public Members ---
	void PublishIntakeMode(bool intaking);
	void NotifyStateUpdate(RobotStateChanges::StateChange change, bool value) override;

	void ManualControl();
	bool HasBeenEnabled() const { return m_hasEnabled; }
	void SetHasBeenEnabled(bool hasEnabled) { m_hasEnabled = hasEnabled; }
	bool IsLaunching() const { return m_isLaunching; }
	units::angle::turn_t GetCahcedExtenderPositionDegrees() { return m_cachedExtenderPositionDeg; };

protected:
	RobotIdentifier m_activeRobotId;
	std::string m_ntName;
	ControlData *GetControlData(std::string name) override;

	// --- Handwritten Protected Members ---

private:
	/// @brief update the output to the mechanism using the current controller and target value(s)
	virtual void Update();

	std::unordered_map<std::string, STATE_NAMES> m_stateMap;

	// Command-based mode tracking + autonomous command handle (replaces StateMgr internals)
	int m_currentState = STATE_OFF;
	frc2::CommandPtr m_autonCommand;

	// Hardware Initializtion Methods
	void InitializeTalonFXIntakeCompBot302();
	void InitializeTalonFXSExtenderCompBot302();
	void InitializeCANdiExtenderCompBot302();

	// Hardware Declarations
	ctre::phoenix6::hardware::TalonFX *m_intakeMotor = nullptr;
	ctre::phoenix6::hardware::TalonFXS *m_extenderMotor = nullptr;
	ctre::phoenix6::hardware::CANdi *m_extenderCANdi = nullptr;

	// Control Data Declarations
	ControlData *m_percentOut = nullptr;
	ControlData *m_positionDeg = nullptr;

	// Control requested
	ctre::phoenix6::controls::DutyCycleOut m_intakePercentOut{0.0};
	ctre::phoenix6::controls::DutyCycleOut m_extenderPercentOut{0.0};
	ctre::phoenix6::controls::PositionVoltage m_extenderPositionDeg{0.0_tr};
	ctre::phoenix6::controls::ControlRequest *m_intakeActiveTarget = &m_intakePercentOut;
	ctre::phoenix6::controls::ControlRequest *m_extenderActiveTarget = &m_extenderPercentOut;

	void RefreshCachedData();

	// Logging Paths
	static constexpr std::string_view m_intakeStatePath = "/Intake/State";
	static constexpr std::string_view m_loggingIntakeTargetPath = "/Intake/IntakeMotorTarget";
	static constexpr std::string_view m_loggingIntakeControlRequest = "/Intake/IntakeControlRequest";
	static constexpr std::string_view m_loggingExtenderTargetPath = "/Intake/ExtenderMotorTarget";
	static constexpr std::string_view m_loggingExtenderPositionPath = "/Intake/ExtenderPosition";
	static constexpr std::string_view m_loggingExtenderControlRequest = "/Intake/ExtenderControlRequest";

	// --- Handwritten Private Members ---
	bool m_isInClimbMode = false;
	bool m_isLaunching = false;
	bool m_prevIntakeSwitchState = false;
	bool m_hasEnabled = false;

	units::angle::turn_t m_intakeRetractedPositionTarget{80.0};
	units::angle::turn_t m_intakeExtendedPositionTarget{0.0};
	units::angle::turn_t m_cachedExtenderPositionDeg{0.0};

	static constexpr double m_percentModifier = 0.5;
	static constexpr units::angle::turn_t m_protectExtenderPositionDegDown{-20.0};
	static constexpr units::angle::turn_t m_protectExtenderPositionDegUp{50.0};
};