//====================================================================================================================================================
// Copyright 2026 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
// This file was automatically generated by the Team 302 code generator version 20.26.00.00
// Generated on Thursday, January 22, 2026 11:43:04 PM

// C++ Includes
#include <string>

// FRC includes

// Team 302 includes
#include "mechanisms/Intake/OffState.h"
#include "teleopcontrol/TeleopControl.h"
#include "teleopcontrol/TeleopControlFunctions.h"
#include "utils/logging/debug/Logger.h"
#include "wpi/driverstation/DriverStation.hpp"
#include "wpi/framework/RobotBase.hpp"

// Third Party Includes

using namespace std;
using namespace IntakeStates;

/// @class ExampleForwardState
/// @brief information about the control (open loop, closed loop position, closed loop velocity, etc.) for a mechanism state
OffState::OffState(std::string stateName,
				   int stateId,
				   Intake *mech,
				   RobotIdentifier activeRobotId) : State(stateName, stateId), m_mechanism(mech), m_RobotId(activeRobotId)
{
}

void OffState::Init()
{
	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, string("ArrivedAt"), string("OffState"), string("Init"));

	if (m_RobotId == RobotIdentifier::COMP_BOT_302)
		InitCompBot302();
	m_mechanism->PublishIntakeMode(false);
}

void OffState::InitCompBot302()
{
	m_mechanism->UpdateTargetIntakePercentOut(m_intakeTarget);
}

void OffState::Run()
{
	// Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, string("ArrivedAt"), string("OffState"), string("Run"));
	if (wpi::RobotBase::IsEnabled() && !m_hasEnabled)
	{
		m_hasEnabled = true;
		if (wpi::RobotBase::IsTeleop())
		{
			m_mechanism->UpdateTargetExtenderPercentOut(0.0);
			m_mechanism->GetExtender()->SetPosition(0.0_tr);
		}
		else
		{
			m_mechanism->UpdateTargetExtenderPositionDeg(0.0_tr);
		}
	}
}

void OffState::Exit()
{
	// Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, string("ArrivedAt"), string("OffState"), string("Exit"));
}

bool OffState::AtTarget()
{
	// Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, string("ArrivedAt"), string("OffState"), string("AtTarget"));

	bool atTarget = false;
	return atTarget;
}

bool OffState::IsTransitionCondition(bool considerGamepadTransitions)
{
	// To get the current state use m_mechanism->GetCurrentState()
	return ((considerGamepadTransitions && ((!TeleopControl::GetInstance()->IsButtonPressed(TeleopControlFunctions::EXPEL) && m_mechanism->GetCurrentState() == m_mechanism->STATE_EXPEL) ||
											(!TeleopControl::GetInstance()->IsButtonPressed(TeleopControlFunctions::INTAKE) && m_mechanism->GetCurrentState() == m_mechanism->STATE_INTAKE) ||
											(!TeleopControl::GetInstance()->IsButtonPressed(TeleopControlFunctions::DRIVE_TO_OUTPOST) && m_mechanism->GetCurrentState() == m_mechanism->STATE_LOAD_HOPPER) ||
											(m_mechanism->GetCurrentState() == m_mechanism->STATE_FORCE_INTAKE_AUTON))) ||
			(m_mechanism->IsIntakeIn() && m_mechanism->GetCurrentState() == m_mechanism->STATE_EMPTY_HOPPER) ||
			(!m_mechanism->IsLaunching() && m_mechanism->GetCurrentState() == m_mechanism->STATE_LAUNCH));
}
