//====================================================================================================================================================
// Copyright 2026 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
// This file was automatically generated by the Team 302 code generator version 2026.1.0

#include "mechanisms/launcher/commands/LauncherIdleCommand.h"
#include "mechanisms/launcher/Launcher.h"

using namespace LauncherCommands;

static constexpr double m_transferTarget{0.0};
static constexpr double m_indexerTarget{0.0};
static constexpr double m_spindexerTarget{0.0};

static constexpr units::angular_velocity::revolutions_per_minute_t m_scoringLauncherTarget{2000};
static constexpr units::angular_velocity::revolutions_per_minute_t m_passingLauncherTarget{4000};

LauncherIdleCommand::LauncherIdleCommand(Launcher *mechanism) : m_mechanism(mechanism)
{
    AddRequirements(m_mechanism);
    SetName("LauncherIdle");
}

void LauncherIdleCommand::Initialize()
{
    m_mechanism->SetCurrentState(Launcher::STATE_IDLE);

    // Motor targets for Idle
    m_mechanism->UpdateTargetTransferPercentOut(m_transferTarget);
    m_mechanism->UpdateTargetIndexerPercentOut(m_indexerTarget);
    m_mechanism->UpdateTargetSpindexerPercentOut(m_spindexerTarget);

    m_mechanism->PublishLaunchMode(false);
    m_mechanism->ResetLaunchCurrentTimer();
    m_mechanism->InitializeSpindexerTargets();
}

void LauncherIdleCommand::Execute()
{
    if (m_mechanism->GetDistanceToTarget() > 30_ft)
    {
        m_mechanism->UpdateTargetLauncherVelocityLauncher(m_passingLauncherTarget);
    }
    else
    {
        m_mechanism->UpdateTargetLauncherVelocityLauncher(m_scoringLauncherTarget);
    }
    if (m_mechanism->IsIntakingMode())
        m_mechanism->AgitateSpindexer();
}

void LauncherIdleCommand::End(bool interrupted)
{
}

bool LauncherIdleCommand::IsFinished()
{
    return false; // Default continuous execution
}