//====================================================================================================================================================
// Copyright 2026 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
// This file was automatically generated by the Team 302 code generator version 2026.1.0

#include "mechanisms/launcher/commands/LauncherManualLaunchCommand.h"
#include "mechanisms/launcher/Launcher.h"

// Unit Includes
#include "wpi/units/angle.hpp"
#include "wpi/units/angular_velocity.hpp"

using namespace LauncherCommands;

static constexpr wpi::units::angular_velocity::revolutions_per_minute_t m_launcherTarget{2200.0};
static constexpr wpi::units::angle::turn_t m_hoodTarget{0.4};
static constexpr wpi::units::angular_velocity::turns_per_second_t m_transferTarget{80.0};
static constexpr wpi::units::angular_velocity::turns_per_second_t m_indexerTarget{25.0};
static constexpr wpi::units::angular_velocity::turns_per_second_t m_spindexerTarget{22.0};
static constexpr double m_turretTarget{0.0};

LauncherManualLaunchCommand::LauncherManualLaunchCommand(Launcher *mechanism) : m_mechanism(mechanism)
{
    AddRequirements(m_mechanism);
    SetName("LauncherManualLaunch");
}

void LauncherManualLaunchCommand::Initialize()
{
    m_mechanism->SetCurrentState(Launcher::STATE_MANUAL_LAUNCH);

    // Motor targets for Manual Launch
    m_mechanism->UpdateTargetLauncherVelocityLauncher(m_launcherTarget);
    m_mechanism->UpdateTargetHoodPositionDegreesHood(m_hoodTarget);
    m_mechanism->UpdateTargetTransferVelocityTransfer(m_transferTarget);
    m_mechanism->UpdateTargetIndexerVelocityIndexer(m_indexerTarget);
    m_mechanism->UpdateTargetSpindexerVelocitySpindexer(m_spindexerTarget);
    m_mechanism->UpdateTargetTurretPercentOut(m_turretTarget);

    m_mechanism->PublishLaunchMode(true);
}

void LauncherManualLaunchCommand::Execute()
{
}

void LauncherManualLaunchCommand::End(bool interrupted)
{
}

bool LauncherManualLaunchCommand::IsFinished()
{
    return false; // Default continuous execution
}