//====================================================================================================================================================
// Copyright 2026 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
// This file was automatically generated by the Team 302 code generator version 2026.1.0

#include "mechanisms/launcher/commands/LauncherLaunchCommand.h"
#include "mechanisms/launcher/Launcher.h"
#include "teleopcontrol/TeleopControl.h"
#include "teleopcontrol/TeleopControlFunctions.h"
#include "wpi/framework/RobotBase.hpp"

// Unit Includes
#include "wpi/units/angular_velocity.hpp"

using namespace LauncherCommands;

static constexpr wpi::units::angular_velocity::revolutions_per_minute_t m_transferTarget{80.0};
static constexpr wpi::units::angular_velocity::revolutions_per_minute_t m_indexerTarget{25.0};
static constexpr wpi::units::angular_velocity::revolutions_per_minute_t m_spindexerTarget{22.0};
static constexpr wpi::units::angular_velocity::turns_per_second_t m_passingTransferTarget{160};
static constexpr wpi::units::angular_velocity::turns_per_second_t m_passingIndexerTarget{50};

LauncherLaunchCommand::LauncherLaunchCommand(Launcher *mechanism) : m_mechanism(mechanism)
{
    AddRequirements(m_mechanism);
    SetName("LauncherLaunch");
}

void LauncherLaunchCommand::Initialize()
{
    m_mechanism->SetCurrentState(Launcher::STATE_LAUNCH);

    // Motor targets for Launch

    m_mechanism->UpdateTargetSpindexerVelocitySpindexer(m_spindexerTarget);
    if (m_mechanism->GetDistanceToTarget() > 40_ft)
    {
        m_mechanism->UpdateTargetTransferVelocityTransfer(m_passingTransferTarget);
        m_mechanism->UpdateTargetIndexerVelocityIndexer(m_passingIndexerTarget);
    }
    else
    {
        m_mechanism->UpdateTargetTransferVelocityTransfer(m_transferTarget);
        m_mechanism->UpdateTargetIndexerVelocityIndexer(m_indexerTarget);
    }

    m_mechanism->PublishLaunchMode(true);
    m_mechanism->StartLaunchCurrentTimer();

    m_launchReleaseTimer.Stop();
    m_launchReleaseTimer.Reset();
}

void LauncherLaunchCommand::Execute()
{
    if (!TeleopControl::GetInstance()->IsButtonPressed(TeleopControlFunctions::LAUNCH) &&
        !TeleopControl::GetInstance()->IsButtonPressed(TeleopControlFunctions::LAUNCH_OVERRIDE) &&
        !TeleopControl::GetInstance()->IsButtonPressed(TeleopControlFunctions::MANUAL_LAUNCH) &&
        wpi::RobotBase::IsTeleop())
    {
        m_mechanism->UpdateTargetSpindexerPercentOut(0.0);
    }
}

void LauncherLaunchCommand::End(bool interrupted)
{
    m_launchReleaseTimer.Stop();
    m_launchReleaseTimer.Reset();
}

bool LauncherLaunchCommand::IsFinished()
{
    // Self-governed exit back to Idle (this command is bound with OnTrue, so the trigger never cancels
    // it). This replaces the old IdleState "launchingDone" timer logic.
    //
    // Auton has no driver buttons, so defer to the current-based launch detector like the old
    // IdleState auton clause (IsAutonomous() && IsFinishedLaunching()).
    if (wpi::RobotBase::IsAutonomous())
    {
        return m_mechanism->IsFinishedLaunching();
    }

    auto tc = TeleopControl::GetInstance();
    bool launchButtonsReleased = !tc->IsButtonPressed(TeleopControlFunctions::LAUNCH) &&
                                 !tc->IsButtonPressed(TeleopControlFunctions::LAUNCH_OVERRIDE) &&
                                 !tc->IsButtonPressed(TeleopControlFunctions::MANUAL_LAUNCH);

    if (launchButtonsReleased)
    {
        // Only finish once the launch buttons have been released for the full debounce window.
        m_launchReleaseTimer.Start();
        return m_launchReleaseTimer.Get() > m_launchReleaseTimeout;
    }

    // Still launching - keep the timer reset so the debounce window restarts on the next release.
    m_launchReleaseTimer.Stop();
    m_launchReleaseTimer.Reset();
    return false;
}