//====================================================================================================================================================
// Copyright 2026 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
// This file was automatically generated by the Team 302 code generator version 2026.1.0

#include "mechanisms/launcher/commands/LauncherPrepareToLaunchCommand.h"
#include "mechanisms/launcher/Launcher.h"

// Unit Includes
#include "units/angular_velocity.h"

using namespace LauncherCommands;

static constexpr units::angular_velocity::revolutions_per_minute_t m_transferTarget{80.0};
static constexpr double m_indexerTarget{0.0};
static constexpr double m_spindexerTarget{0.0};

LauncherPrepareToLaunchCommand::LauncherPrepareToLaunchCommand(Launcher *mechanism) : m_mechanism(mechanism)
{
    AddRequirements(m_mechanism);
    SetName("LauncherPrepareToLaunch");
}

void LauncherPrepareToLaunchCommand::Initialize()
{
    m_mechanism->SetCurrentState(Launcher::STATE_PREPARE_TO_LAUNCH);

    // Motor targets for Prepare To Launch
    m_mechanism->UpdateTargetTransferVelocityTransfer(m_transferTarget);
    m_mechanism->UpdateTargetIndexerPercentOut(m_indexerTarget);
    m_mechanism->UpdateTargetSpindexerPercentOut(m_spindexerTarget);

    m_mechanism->PublishLaunchMode(true);
}

void LauncherPrepareToLaunchCommand::Execute()
{
}

void LauncherPrepareToLaunchCommand::End(bool interrupted)
{
}

bool LauncherPrepareToLaunchCommand::IsFinished()
{
    return false; // Default continuous execution
}