//====================================================================================================================================================
// Copyright 2026 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
// This file was automatically generated by the Team 302 code generator version 2026.1.0

#include "mechanisms/launcher/commands/LauncherOffCommand.h"
#include "mechanisms/launcher/Launcher.h"
#include "teleopcontrol/TeleopControl.h"

using namespace LauncherCommands;

static constexpr double m_launcherTarget{0.0};
static constexpr double m_hoodTarget{0.0};
static constexpr double m_transferTarget{0.0};
static constexpr double m_indexerTarget{0.0};
static constexpr double m_spindexerTarget{0.0};
static constexpr double m_turretTarget{0.0};
static constexpr double m_manualControlModifier{0.25};

LauncherOffCommand::LauncherOffCommand(Launcher *mechanism) : m_mechanism(mechanism)
{
    AddRequirements(m_mechanism);
    SetName("LauncherOff");
}

void LauncherOffCommand::Initialize()
{
    m_mechanism->SetCurrentState(Launcher::STATE_OFF);

    // Motor targets for Off
    m_mechanism->UpdateTargetLauncherPercentOut(m_launcherTarget);
    m_mechanism->UpdateTargetHoodPercentOut(m_hoodTarget);
    m_mechanism->UpdateTargetTransferPercentOut(m_transferTarget);
    m_mechanism->UpdateTargetIndexerPercentOut(m_indexerTarget);
    m_mechanism->UpdateTargetSpindexerPercentOut(m_spindexerTarget);
    m_mechanism->UpdateTargetTurretPercentOut(m_turretTarget);

    m_mechanism->SetLauncherInitialized(false);
    m_mechanism->PublishLaunchMode(false);
}

void LauncherOffCommand::Execute()
{
    double manualHoodPercentOut = TeleopControl::GetInstance()->GetAxisValue(TeleopControlFunctions::UPDATE_DEPOT_PASSING_TARGET_X);
    if (abs(manualHoodPercentOut) < 0.075)
    {
        manualHoodPercentOut = 0;
    }
    double manualTurretPercentOut = TeleopControl::GetInstance()->GetAxisValue(TeleopControlFunctions::UPDATE_OUTPOST_PASSING_TARGET_Y);
    if (abs(manualTurretPercentOut) < 0.075)
    {
        manualTurretPercentOut = 0;
    }
    m_mechanism->UpdateTargetTurretPercentOut(manualTurretPercentOut * m_manualControlModifier);
    m_mechanism->UpdateTargetHoodPercentOut(manualHoodPercentOut);
    m_mechanism->UpdateTurretEnabled();
}

void LauncherOffCommand::End(bool interrupted)
{
}

bool LauncherOffCommand::IsFinished()
{
    return false; // Default continuous execution
}