//====================================================================================================================================================
// Copyright 2026 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
// This file was automatically generated by the Team 302 code generator version 2026.1.0

#include "mechanisms/launcher/commands/LauncherLaunchCommand.h"
#include "mechanisms/launcher/Launcher.h"
#include "teleopcontrol/TeleopControl.h"

// Unit Includes
#include "units/angular_velocity.h"

using namespace LauncherCommands;

static constexpr units::angular_velocity::revolutions_per_minute_t m_transferTarget{80.0};
static constexpr units::angular_velocity::revolutions_per_minute_t m_indexerTarget{25.0};
static constexpr units::angular_velocity::revolutions_per_minute_t m_spindexerTarget{22.0};
static constexpr units::angular_velocity::turns_per_second_t m_passingTransferTarget{160};
static constexpr units::angular_velocity::turns_per_second_t m_passingIndexerTarget{50};

LauncherLaunchCommand::LauncherLaunchCommand(Launcher *mechanism) : m_mechanism(mechanism)
{
    AddRequirements(m_mechanism);
    SetName("LauncherLaunch");
}

void LauncherLaunchCommand::Initialize()
{
    m_mechanism->SetCurrentState(Launcher::STATE_LAUNCH);

    // Motor targets for Launch

    m_mechanism->UpdateTargetSpindexerVelocitySpindexer(m_spindexerTarget);
    if (m_mechanism->GetDistanceToTarget() > 40_ft)
    {
        m_mechanism->UpdateTargetTransferVelocityTransfer(m_passingTransferTarget);
        m_mechanism->UpdateTargetIndexerVelocityIndexer(m_passingIndexerTarget);
    }
    else
    {
        m_mechanism->UpdateTargetTransferVelocityTransfer(m_transferTarget);
        m_mechanism->UpdateTargetIndexerVelocityIndexer(m_indexerTarget);
    }

    m_mechanism->PublishLaunchMode(true);
    m_mechanism->StartLaunchCurrentTimer();
}

void LauncherLaunchCommand::Execute()
{
    if (!TeleopControl::GetInstance()->IsButtonPressed(TeleopControlFunctions::LAUNCH) &&
        !TeleopControl::GetInstance()->IsButtonPressed(TeleopControlFunctions::LAUNCH_OVERRIDE) &&
        !TeleopControl::GetInstance()->IsButtonPressed(TeleopControlFunctions::MANUAL_LAUNCH) &&
        frc::DriverStation::IsTeleop())
    {
        m_mechanism->UpdateTargetSpindexerPercentOut(0.0);
    }
}

void LauncherLaunchCommand::End(bool interrupted)
{
}

bool LauncherLaunchCommand::IsFinished()
{
    return false; // Default continuous execution
}