//====================================================================================================================================================
// Copyright 2026 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
// This file was automatically generated by the Team 302 code generator version 2026.1.0

#include "mechanisms/launcher/commands/LauncherLauncherTuningCommand.h"
#include "mechanisms/launcher/Launcher.h"
#include "teleopcontrol/TeleopControl.h"
#include "utils/logging/debug/Logger.h"

// Unit Includes
#include "units/angular_velocity.h"

using namespace LauncherCommands;

units::angular_velocity::revolutions_per_minute_t m_launcherTarget{1000.0};
static constexpr double m_hoodTarget{0.0};
static constexpr double m_transferTarget{0.0};
static constexpr double m_indexerTarget{0.0};
static constexpr double m_spindexerTarget{0.0};
static constexpr double m_turretTarget{0.0};

LauncherLauncherTuningCommand::LauncherLauncherTuningCommand(Launcher *mechanism) : m_mechanism(mechanism)
{
    AddRequirements(m_mechanism);
    SetName("LauncherLauncherTuning");
}

void LauncherLauncherTuningCommand::Initialize()
{
    m_mechanism->SetCurrentState(Launcher::STATE_LAUNCHER_TUNING);

    // Motor targets for Launcher Tuning
    m_mechanism->UpdateTargetHoodPercentOut(m_hoodTarget);
    m_mechanism->UpdateTargetTransferPercentOut(m_transferTarget);
    m_mechanism->UpdateTargetIndexerPercentOut(m_indexerTarget);
    m_mechanism->UpdateTargetSpindexerPercentOut(m_spindexerTarget);
}

void LauncherLauncherTuningCommand::Execute()
{
    double manualHoodPercentOut = TeleopControl::GetInstance()->GetAxisValue(TeleopControlFunctions::UPDATE_DEPOT_PASSING_TARGET_X);
    if (abs(manualHoodPercentOut) < 0.075)
    {
        manualHoodPercentOut = 0;
    }

    if (TeleopControl::GetInstance()->IsButtonPressed(TeleopControlFunctions::UPDATE_TARGET_OFFSET_UP))
    {
        if (m_speedUpButtonReleased)
        {
            m_launcherPercentOut += 0.05;
            m_launcherTarget += units::angular_velocity::revolutions_per_minute_t(50);
        }
        m_speedUpButtonReleased = false;
    }
    else if (TeleopControl::GetInstance()->IsButtonPressed(TeleopControlFunctions::UPDATE_TARGET_OFFSET_DOWN))
    {
        if (m_speedDownButtonReleased)
        {
            m_launcherPercentOut -= 0.05;
            m_launcherTarget -= units::angular_velocity::revolutions_per_minute_t(50);
        }
        m_speedDownButtonReleased = false;
    }
    else
    {
        m_speedUpButtonReleased = true;
        m_speedDownButtonReleased = true;
    }

    if (m_tuningLauncherPercentOut)
    {
        m_mechanism->UpdateTargetLauncherPercentOut(m_launcherPercentOut);
        double manualTurretPercentOut = TeleopControl::GetInstance()->GetAxisValue(TeleopControlFunctions::UPDATE_OUTPOST_PASSING_TARGET_Y);
        if (abs(manualTurretPercentOut) < 0.075)
        {
            manualTurretPercentOut = 0;
        }
        m_mechanism->UpdateTargetTurretPercentOut(manualTurretPercentOut);
    }
    else
    {
        m_mechanism->UpdateTargetLauncherVelocityLauncher(m_launcherTarget);
        m_mechanism->UpdateTargetTurretPositionDegreesTurret(m_mechanism->GetTargetTurretAngle());
    }

    m_mechanism->UpdateTargetHoodPercentOut(manualHoodPercentOut);

    Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, "LauncherTuningState", "Launcher Target RPM", m_launcherTarget.value());
    Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, "LauncherTuningState", "Launcher Percent Out", m_launcherPercentOut);
    units::length::inch_t distanceToTarget = RebuiltTargetCalculator::GetInstance()->CalculateMechanismDistanceToTarget();
    Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, "LauncherTuningState", "Distance", distanceToTarget.value());
}

void LauncherLauncherTuningCommand::End(bool interrupted)
{
}

bool LauncherLauncherTuningCommand::IsFinished()
{
    return false; // Default continuous execution
}