//====================================================================================================================================================
// Copyright 2026 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
// This file was automatically generated by the Team 302 code generator version 20.26.00.00
// Generated on Friday, January 23, 2026 12:20:12 PM

#pragma once
#include "mechanisms/MechanismTypes.h"
#include "mechanisms/configs/MechanismConfig.h"
#include "mechanisms/intake/Intake.h"
#include "mechanisms/launcher/Launcher.h"
#include "state/StateMgr.h"

class MechanismConfigCompBot_302 : public MechanismConfig
{
public:
	MechanismConfigCompBot_302() = default;
	~MechanismConfigCompBot_302() = default;

	BaseMech *GetMechanism(MechanismTypes::MECHANISM_TYPE mechType);

protected:
	void DefineMechanisms() override;
	void DefineLEDs() override;
	void DefineCompressor() override;

private:
	Intake *m_theIntake = nullptr;
	Launcher *m_theLauncher = nullptr;

	std::unordered_map<MechanismTypes::MECHANISM_TYPE, BaseMech *> m_mechanismMap;
	static constexpr int m_ledCanID = 60;
	static constexpr int m_ledStripSize = 45;
	static constexpr double m_ledBrightness = 0.75;
};