//====================================================================================================================================================
// Copyright 2026 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
// This file was automatically generated by the Team 302 code generator version 20.26.00.00
// Generated on Friday, January 23, 2026 12:20:12 PM

#include <string>

#include "feedback/DragonCANdle.h"
#include "mechanisms/configs/MechanismConfigCompBot_302.h"
#include "mechanisms/configs/MechanismConfigMgr.h"
#include "mechanisms/configs/RobotElementNames.h"
#include "utils/PeriodicLooper.h"
#include "utils/logging/debug/Logger.h"
#include "wpi/framework/RobotBase.hpp"
#include "wpi/hardware/pneumatic/Compressor.hpp"

using ctre::phoenix6::signals::StripTypeValue;
using std::string;

void MechanismConfigCompBot_302::DefineMechanisms()
{
	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, string("Initializing mechanism"), string("Intake"), "");
	m_theIntake = new Intake(RobotIdentifier::COMP_BOT_302);
	m_theIntake->CreateCompBot302();
	m_theIntake->InitializeCompBot302();
	m_mechanismMap[MechanismTypes::MECHANISM_TYPE::INTAKE] = m_theIntake;

	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, string("Initializing mechanism"), string("Launcher"), "");
	m_theLauncher = new Launcher(RobotIdentifier::COMP_BOT_302);
	m_theLauncher->CreateCompBot302();
	m_theLauncher->InitializeCompBot302();
	m_mechanismMap[MechanismTypes::MECHANISM_TYPE::LAUNCHER] = m_theLauncher;
}

BaseMech *MechanismConfigCompBot_302::GetMechanism(MechanismTypes::MECHANISM_TYPE mechType)
{
	auto itr = m_mechanismMap.find(mechType);
	if (itr != m_mechanismMap.end())
	{
		return itr->second;
	}
	return nullptr;
}

void MechanismConfigCompBot_302::DefineLEDs()
{
	auto candle = DragonCANdle::GetInstance();
	candle->Initialize(m_ledCanID, m_ledStripSize, std::string("rio"), m_ledBrightness); // CAN ID 0, 45 LEDs external) Update with actual number of LEDs on the robot
}

void MechanismConfigCompBot_302::DefineCompressor()
{
}