//====================================================================================================================================================
// Copyright 2026 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
// This file was automatically generated by the Team 302 code generator version 20.26.00.00
// Generated on Thursday, January 22, 2026 11:43:04 PM

// C++ Includes
#include <string>

// FRC includes

// Team 302 includes
#include "mechanisms/Launcher/ClimbState.h"
#include "teleopcontrol/TeleopControl.h"
#include "teleopcontrol/TeleopControlFunctions.h"
#include "utils/logging/debug/Logger.h"

// Third Party Includes

using namespace std;
using namespace LauncherStates;

/// @class ExampleForwardState
/// @brief information about the control (open loop, closed loop position, closed loop velocity, etc.) for a mechanism state
ClimbState::ClimbState(std::string stateName,
					   int stateId,
					   Launcher *mech,
					   RobotIdentifier activeRobotId) : State(stateName, stateId), m_mechanism(mech), m_RobotId(activeRobotId)
{
}

void ClimbState::Init()
{
	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, string("ArrivedAt"), string("ClimbState"), string("Init"));

	if (m_RobotId == RobotIdentifier::COMP_BOT_302)
		InitCompBot302();
}

void ClimbState::InitCompBot302()
{
	m_mechanism->UpdateTargetLauncherPercentOut(m_launcherTarget);
	m_mechanism->UpdateTargetHoodPercentOut(m_hoodTarget);
	m_mechanism->UpdateTargetTransferPercentOut(m_transferTarget);
	m_mechanism->UpdateTargetTurretPercentOut(m_turretTarget);
	m_mechanism->UpdateTargetIndexerPercentOut(m_indexerTarget);
	m_mechanism->UpdateTargetSpindexerPercentOut(m_spindexerTarget);
}

void ClimbState::Run()
{
	// Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, string("ArrivedAt"), string("ClimbState"), string("Run"));
}

void ClimbState::Exit()
{
	// Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, string("ArrivedAt"), string("ClimbState"), string("Exit"));
}

bool ClimbState::AtTarget()
{
	// Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, string("ArrivedAt"), string("ClimbState"), string("AtTarget"));

	bool atTarget = false;
	return atTarget;
}

bool ClimbState::IsTransitionCondition(bool considerGamepadTransitions)
{
	// To get the current state use m_mechanism->GetCurrentState()
	return (m_mechanism->IsAllowedToClimb() && m_mechanism->IsInClimbMode() && !TeleopControl::GetInstance()->IsButtonPressed(TeleopControlFunctions::LAUNCH) && !TeleopControl::GetInstance()->IsButtonPressed(TeleopControlFunctions::LAUNCH_OVERRIDE));
}
