//====================================================================================================================================================
// Copyright 2026 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
// This file was automatically generated by the Team 302 code generator version 20.26.00.00
// Generated on Thursday, January 22, 2026 11:43:04 PM

// C++ Includes
#include <string>

// FRC includes

// Team 302 includes
#include "mechanisms/Launcher/IdleState.h"
#include "teleopcontrol/TeleopControl.h"
#include "teleopcontrol/TeleopControlFunctions.h"
#include "utils/logging/debug/Logger.h"
#include "wpi/framework/RobotBase.hpp"

// Third Party Includes

using namespace std;
using namespace LauncherStates;

/// @class ExampleForwardState
/// @brief information about the control (open loop, closed loop position, closed loop velocity, etc.) for a mechanism state
IdleState::IdleState(std::string stateName,
					 int stateId,
					 Launcher *mech,
					 RobotIdentifier activeRobotId) : State(stateName, stateId), m_mechanism(mech), m_RobotId(activeRobotId), m_Timer(new wpi::Timer())
{
}

void IdleState::Init()
{
	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, string("ArrivedAt"), string("IdleState"), string("Init"));

	if (m_RobotId == RobotIdentifier::COMP_BOT_302)
		InitCompBot302();
	m_mechanism->PublishLaunchMode(false);

	m_mechanism->ResetLaunchCurrentTimer();
}

void IdleState::InitCompBot302()
{
	m_mechanism->UpdateTargetTransferPercentOut(m_transferTarget);
	m_mechanism->UpdateTargetIndexerPercentOut(m_indexerTarget);
	m_mechanism->UpdateTargetSpindexerPercentOut(m_spindexerTarget);
}

void IdleState::Run()
{
	if (m_mechanism->GetDistanceToTarget() > 30_ft)
	{
		m_mechanism->UpdateTargetLauncherVelocityRPS(m_passingLauncherTarget);
	}
	else
	{
		m_mechanism->UpdateTargetLauncherVelocityRPS(m_launcherTarget);
	}
}
void IdleState::Exit()
{
	// Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, string("ArrivedAt"), string("IdleState"), string("Exit"));
}

bool IdleState::AtTarget()
{
	// Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, string("ArrivedAt"), string("IdleState"), string("AtTarget"));

	bool atTarget = false;
	return atTarget;
}

bool IdleState::IsTransitionCondition(bool considerGamepadTransitions)
{
	// To get the current state use m_mechanism->GetCurrentState()
	bool launchingDone = false;

	if (considerGamepadTransitions && (!TeleopControl::GetInstance()->IsButtonPressed(TeleopControlFunctions::LAUNCH) && !TeleopControl::GetInstance()->IsButtonPressed(TeleopControlFunctions::LAUNCH_OVERRIDE) && !TeleopControl::GetInstance()->IsButtonPressed(TeleopControlFunctions::MANUAL_LAUNCH)) &&
		((m_mechanism->GetCurrentState() == Launcher::STATE_LAUNCH) || (m_mechanism->GetCurrentState() == Launcher::STATE_PREPARE_TO_LAUNCH) || (m_mechanism->GetCurrentState() == Launcher::STATE_MANUAL_LAUNCH)))
	{
		m_Timer->Start();
		if (m_Timer->Get() > m_launchTimer)
		{
			launchingDone = true;
			m_Timer->Stop();
			m_Timer->Reset();
		}
	}
	return (m_mechanism->IsLauncherInitialized() && m_mechanism->GetCurrentState() == Launcher::STATE_INITIALIZE) ||
		   (launchingDone) ||
		   (!m_mechanism->IsIntakingMode() && m_mechanism->GetCurrentState() == Launcher::STATE_AGITATOR) ||
		   (!m_mechanism->IsInClimbMode() && (m_mechanism->GetCurrentState() == Launcher::STATE_CLIMB || m_mechanism->GetCurrentState() == Launcher::STATE_EMPTY_HOPPER)) ||
		   (wpi::RobotBase::IsAutonomous() && m_mechanism->IsFinishedLaunching() && (m_mechanism->GetCurrentState() == Launcher::STATE_LAUNCH));
}
