//====================================================================================================================================================
// Copyright 2026 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
// This file was automatically generated by the Team 302 code generator version 20.26.00.00
// Generated on Thursday, January 22, 2026 11:43:04 PM

#pragma once
#include "wpi/system/Timer.hpp"
#include <string>

#include "mechanisms/Launcher/Launcher.h"
#include "state/State.h"

using namespace std;

namespace LauncherStates
{
	class IdleState : public State
	{
	public:
		IdleState() = delete;
		IdleState(std::string stateName,
				  int stateId,
				  Launcher *mech,
				  RobotIdentifier activeRobotId);
		~IdleState() = default;
		void Init() override;
		void Run() override;
		void Exit() override;
		bool AtTarget() override;
		bool IsTransitionCondition(bool considerGamepadTransitions) override;
		void AgitateSpindexer();

	private:
		Launcher *m_mechanism;
		void InitCompBot302();
		RobotIdentifier m_RobotId;

		const wpi::units::angular_velocity::revolutions_per_minute_t m_launcherTarget{2000};
		const wpi::units::angular_velocity::revolutions_per_minute_t m_passingLauncherTarget{4000};
		const wpi::units::angle::turn_t m_hoodTarget{0.0};
		const double m_transferTarget{0.0};
		const wpi::units::angle::turn_t m_turretTarget{0.0};
		const double m_indexerTarget{0.0};
		const double m_spindexerTarget{0.0};
		wpi::Timer *m_Timer;
		static constexpr wpi::units::time::second_t m_launchTimer{0.25};
	};
}
