//====================================================================================================================================================
// Copyright 2026 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
// This file was automatically generated by the Team 302 code generator version 20.26.00.01
// Generated on Saturday, January 31, 2026 2:50:23 PM

#pragma once
#include <string>

#include "state/State.h"
#include "mechanisms/Launcher/Launcher.h"

using namespace std;

namespace LauncherStates
{
	class LauncherTuningState : public State
	{
	public:
		LauncherTuningState() = delete;
		LauncherTuningState(std::string stateName,
							int stateId,
							Launcher *mech,
							RobotIdentifier activeRobotId);
		~LauncherTuningState() = default;
		void Init() override;
		void Run() override;
		void Exit() override;
		bool AtTarget() override;
		bool IsTransitionCondition(bool considerGamepadTransitions) override;

	private:
		Launcher *m_mechanism;
		void InitCompBot302();
		RobotIdentifier m_RobotId;

		wpi::units::angular_velocity::revolutions_per_minute_t m_launcherTarget = wpi::units::angular_velocity::revolutions_per_minute_t(1000);
		const double m_hoodTarget = double(0);
		const double m_transferTarget = double(0);
		const double m_turretTarget = double(0);
		const double m_indexerTarget = double(0);

		double m_launcherPercentOut = 0.4;

		bool m_speedUpButtonReleased = true;
		bool m_speedDownButtonReleased = true;
		bool m_tuningLauncherPercentOut = false;
	};
}
