//====================================================================================================================================================
// Copyright 2026 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
// This file was automatically generated by the Team 302 code generator version 2026.1.0

// FRC Includes
#include "mechanisms/launcher/Launcher.h"
#include "frc/DriverStation.h"
#include "frc/RobotBase.h"
#include "frc2/command/Commands.h"
#include "networktables/NetworkTableInstance.h"

#include "state/RobotState.h"
#include "teleopcontrol/TeleopControl.h"
#include "units/math.h"
#include "utils/InterpolateUtils.h"
#include "utils/logging/debug/Logger.h"
#include "utils/logging/signals/DragonDataLogger.h"

#include "ctre/phoenix6/TalonFX.hpp"
#include "ctre/phoenix6/TalonFXS.hpp"
#include "ctre/phoenix6/configs/Configuration.hpp"

using ctre::phoenix6::configs::CANdiConfiguration;
using ctre::phoenix6::configs::TalonFXConfiguration;
using ctre::phoenix6::configs::TalonFXSConfiguration;

using std::string;

Launcher::Launcher(RobotIdentifier id) : BaseMechSubsystem(MechanismTypes::MECHANISM_TYPE::LAUNCHER, std::string("Launcher")),
										 m_activeRobotId(id),
										 m_stateMap(),
										 m_autonCommand(frc2::cmd::None()),
										 m_chassis(ChassisConfigMgr::GetInstance()->GetSwerveChassis())
{
	RobotState::GetInstance()->RegisterForStateChanges(this, RobotStateChanges::StateChange::AllowedToClimbStatus_Bool);
	RobotState::GetInstance()->RegisterForStateChanges(this, RobotStateChanges::StateChange::ClimbModeStatus_Bool);
	RobotState::GetInstance()->RegisterForStateChanges(this, RobotStateChanges::StateChange::HubActive_Bool);
	RobotState::GetInstance()->RegisterForStateChanges(this, RobotStateChanges::StateChange::IsIntaking_Bool);
	RobotState::GetInstance()->RegisterForStateChanges(this, RobotStateChanges::StateChange::StartLaunching_Bool);
	RobotState::GetInstance()->PublishStateChange(RobotStateChanges::StateChange::TurretEnabled_Bool, m_turretEnabled);
	m_targetCalculator = RebuiltTargetCalculator::GetInstance();
	m_allianceZoneManager = AllianceZoneManager::GetInstance();
	m_deadZoneManager = DeadZoneManager::GetInstance();

	m_launcherVelocityLauncher.EnableFOC = true;
	m_spindexerVelocityLauncher.EnableFOC = true;
	m_indexerVelocityIndexer.EnableFOC = true;
	m_transferVelocityTransfer.EnableFOC = true;
	m_hoodPositionDegreesHood.EnableFOC = true;
	m_turretPositionDegreesTurret.EnableFOC = true;
}

std::map<std::string, Launcher::STATE_NAMES>
	Launcher::stringToSTATE_NAMESEnumMap{
		{"STATE_OFF", Launcher::STATE_NAMES::STATE_OFF},
		{"STATE_INITIALIZE", Launcher::STATE_NAMES::STATE_INITIALIZE},
		{"STATE_IDLE", Launcher::STATE_NAMES::STATE_IDLE},
		{"STATE_PREPARE_TO_LAUNCH", Launcher::STATE_NAMES::STATE_PREPARE_TO_LAUNCH},
		{"STATE_LAUNCH", Launcher::STATE_NAMES::STATE_LAUNCH},
		{"STATE_LAUNCHER_TUNING", Launcher::STATE_NAMES::STATE_LAUNCHER_TUNING},
		{"STATE_MANUAL_LAUNCH", Launcher::STATE_NAMES::STATE_MANUAL_LAUNCH}};

std::map<Launcher::STATE_NAMES, std::string>
	Launcher::STATE_NAMESEnumToStringMap{
		{Launcher::STATE_NAMES::STATE_OFF, "STATE_OFF"},
		{Launcher::STATE_NAMES::STATE_INITIALIZE, "STATE_INITIALIZE"},
		{Launcher::STATE_NAMES::STATE_IDLE, "STATE_IDLE"},
		{Launcher::STATE_NAMES::STATE_PREPARE_TO_LAUNCH, "STATE_PREPARE_TO_LAUNCH"},
		{Launcher::STATE_NAMES::STATE_LAUNCH, "STATE_LAUNCH"},
		{Launcher::STATE_NAMES::STATE_LAUNCHER_TUNING, "STATE_LAUNCHER_TUNING"},
		{Launcher::STATE_NAMES::STATE_MANUAL_LAUNCH, "STATE_MANUAL_LAUNCH"}};

void Launcher::CreateCompBot302()
{
	m_ntName = "Launcher";
	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, string("Initializing mechanism"), string("Launcher for COMPBOT_302"), "");

	// --- Hardware Setup ---
	m_launcherMotor = new ctre::phoenix6::hardware::TalonFX(8, ctre::phoenix6::CANBus("canivore"));
	m_hoodMotor = new ctre::phoenix6::hardware::TalonFXS(7, ctre::phoenix6::CANBus("canivore"));
	m_transferMotor = new ctre::phoenix6::hardware::TalonFX(4, ctre::phoenix6::CANBus("canivore"));
	m_indexerMotor = new ctre::phoenix6::hardware::TalonFX(5, ctre::phoenix6::CANBus("canivore"));
	m_spindexerMotor = new ctre::phoenix6::hardware::TalonFX(18, ctre::phoenix6::CANBus("canivore"));
	m_hoodCANdi = new ctre::phoenix6::hardware::CANdi(7, ctre::phoenix6::CANBus("canivore"));
	m_turretCANdi = new ctre::phoenix6::hardware::CANdi(6, ctre::phoenix6::CANBus("canivore"));
	m_turretMotor = new ctre::phoenix6::hardware::TalonFXS(6, ctre::phoenix6::CANBus("canivore"));

	// --- Control Data Setup ---
	m_percentOut = new ControlData(
		"m_percentOut",											 // std::string indentifier
		0.0,													 // double proportional
		0.0,													 // double integral
		0.0,													 // double derivative
		0.0,													 // double feedforward
		0.0,													 // double velocityGain
		0.0,													 // double accelartionGain
		0.0,													 // double staticFrictionGain,
		0.0,													 // double integralZone
		0.0,													 // double maxAcceleration
		0.0,													 // double cruiseVelocity
		ControlData::GravityTypeValue::Arm_Cosine,				 // Gravity type
		ControlData::StaticFeedforwardSignValue::UseVelocitySign // Static feedforward sign
	);
	m_velocityLauncher = new ControlData(
		"m_velocityLauncher",									 // std::string indentifier
		0.45,													 // double proportional
		0.0,													 // double integral
		0.0,													 // double derivative
		0.0,													 // double feedforward
		0.125,													 // double velocityGain
		0.0,													 // double accelartionGain
		0.375,													 // double staticFrictionGain,
		0.0,													 // double integralZone
		0.0,													 // double maxAcceleration
		0.0,													 // double cruiseVelocity
		ControlData::GravityTypeValue::Elevator_Static,			 // Gravity type
		ControlData::StaticFeedforwardSignValue::UseVelocitySign // Static feedforward sign
	);
	m_velocityLauncherFullField = new ControlData(
		"m_velocityLauncherFullField",							 // std::string indentifier
		5.0,													 // double proportional
		3.0,													 // double integral
		0.0,													 // double derivative
		0.0,													 // double feedforward
		0.15,													 // double velocityGain
		0.0,													 // double accelartionGain
		0.375,													 // double staticFrictionGain,
		0.0,													 // double integralZone
		0.0,													 // double maxAcceleration
		0.0,													 // double cruiseVelocity
		ControlData::GravityTypeValue::Elevator_Static,			 // Gravity type
		ControlData::StaticFeedforwardSignValue::UseVelocitySign // Static feedforward sign
	);
	m_velocityIndexer = new ControlData(
		"m_velocityIndexer",									 // std::string indentifier
		1.0,													 // double proportional
		0.0,													 // double integral
		0.0,													 // double derivative
		0.0,													 // double feedforward
		0.365,													 // double velocityGain
		0.0,													 // double accelartionGain
		0.4,													 // double staticFrictionGain,
		0.0,													 // double integralZone
		0.0,													 // double maxAcceleration
		0.0,													 // double cruiseVelocity
		ControlData::GravityTypeValue::Elevator_Static,			 // Gravity type
		ControlData::StaticFeedforwardSignValue::UseVelocitySign // Static feedforward sign
	);
	m_velocitySpindexer = new ControlData(
		"m_velocitySpindexer",									 // std::string indentifier
		1.0,													 // double proportional
		0.0,													 // double integral
		0.0,													 // double derivative
		0.0,													 // double feedforward
		0.35,													 // double velocityGain
		0.0,													 // double accelartionGain
		0.325,													 // double staticFrictionGain,
		0.0,													 // double integralZone
		0.0,													 // double maxAcceleration
		0.0,													 // double cruiseVelocity
		ControlData::GravityTypeValue::Elevator_Static,			 // Gravity type
		ControlData::StaticFeedforwardSignValue::UseVelocitySign // Static feedforward sign
	);
	m_velocityTransfer = new ControlData(
		"m_velocityTransfer",									 // std::string indentifier
		2.0,													 // double proportional
		0.0,													 // double integral
		0.0,													 // double derivative
		0.0,													 // double feedforward
		0.0,													 // double velocityGain
		0.12,													 // double accelartionGain
		0.3,													 // double staticFrictionGain,
		0.0,													 // double integralZone
		0.0,													 // double maxAcceleration
		0.0,													 // double cruiseVelocity
		ControlData::GravityTypeValue::Elevator_Static,			 // Gravity type
		ControlData::StaticFeedforwardSignValue::UseVelocitySign // Static feedforward sign
	);
	m_positionDegreesHood = new ControlData(
		"m_positionDegreesHood",								 // std::string indentifier
		3.0,													 // double proportional
		0.0,													 // double integral
		0.0,													 // double derivative
		0.0,													 // double feedforward
		0.385,													 // double velocityGain
		0.01,													 // double accelartionGain
		0.2,													 // double staticFrictionGain,
		0.0,													 // double integralZone
		200.0,													 // double maxAcceleration
		52.5,													 // double cruiseVelocity
		ControlData::GravityTypeValue::Elevator_Static,			 // Gravity type
		ControlData::StaticFeedforwardSignValue::UseVelocitySign // Static feedforward sign
	);
	m_positionDegreesTurret = new ControlData(
		"m_positionDegreesTurret",								 // std::string indentifier
		0.2,													 // double proportional
		0.0,													 // double integral
		0.0,													 // double derivative
		0.0,													 // double feedforward
		0.0125,													 // double velocityGain
		0.0,													 // double accelartionGain
		0.25,													 // double staticFrictionGain,
		0.0,													 // double integralZone
		2000.0,													 // double maxAcceleration
		1000.0,													 // double cruiseVelocity
		ControlData::GravityTypeValue::Arm_Cosine,				 // Gravity type
		ControlData::StaticFeedforwardSignValue::UseVelocitySign // Static feedforward sign
	);
	m_positionTurnSpindexer = new ControlData(
		"m_positionTurnSpindexer",								 // std::string indentifier
		15.0,													 // double proportional
		0.0,													 // double integral
		0.0,													 // double derivative
		0.0,													 // double feedforward
		0.0,													 // double velocityGain
		0.0,													 // double accelartionGain
		0.0,													 // double staticFrictionGain,
		0.0,													 // double integralZone
		0.0,													 // double maxAcceleration
		0.0,													 // double cruiseVelocity
		ControlData::GravityTypeValue::Elevator_Static,			 // Gravity type
		ControlData::StaticFeedforwardSignValue::UseVelocitySign // Static feedforward sign
	);

	ReadConstants("Launcher.xml", 302);
}

void Launcher::InitializeCompBot302()
{
	// Initializtion Mehtods of all of the hardware in this robot
	InitializeTalonFXLauncherCompBot302();
	InitializeTalonFXSHoodCompBot302();
	InitializeTalonFXTransferCompBot302();
	InitializeTalonFXIndexerCompBot302();
	InitializeTalonFXSpindexerCompBot302();
	InitializeCANdiHoodCompBot302();
	InitializeCANdiTurretCompBot302();
	if (m_turretEnabled)
		InitializeTalonFXSTurretCompBot302();
}

// All of the Initializtion Mehtods for all of the robots

void Launcher::InitializeTalonFXLauncherCompBot302()
{
	TalonFXConfiguration configs{};
	configs.CurrentLimits.StatorCurrentLimit = units::current::ampere_t(120.0);
	configs.CurrentLimits.StatorCurrentLimitEnable = true;
	configs.CurrentLimits.SupplyCurrentLimit = units::current::ampere_t(70.0);
	configs.CurrentLimits.SupplyCurrentLimitEnable = true;
	configs.CurrentLimits.SupplyCurrentLowerLimit = units::current::ampere_t(40.0);
	configs.CurrentLimits.SupplyCurrentLowerTime = units::time::second_t(0.0);

	configs.Voltage.PeakForwardVoltage = units::voltage::volt_t(16.0);
	configs.Voltage.PeakReverseVoltage = units::voltage::volt_t(4.5);
	configs.ClosedLoopRamps.VoltageClosedLoopRampPeriod = units::time::second_t(0.1);
	configs.OpenLoopRamps.DutyCycleOpenLoopRampPeriod = units::time::second_t(0.1);

	configs.HardwareLimitSwitch.ForwardLimitEnable = false;
	configs.HardwareLimitSwitch.ForwardLimitRemoteSensorID = 0;
	configs.HardwareLimitSwitch.ForwardLimitAutosetPositionEnable = false;
	configs.HardwareLimitSwitch.ForwardLimitAutosetPositionValue = units::angle::turn_t(0.0);
	configs.HardwareLimitSwitch.ForwardLimitSource = ctre::phoenix6::signals::ForwardLimitSourceValue::LimitSwitchPin;
	configs.HardwareLimitSwitch.ForwardLimitType = ctre::phoenix6::signals::ForwardLimitTypeValue::NormallyOpen;

	configs.HardwareLimitSwitch.ReverseLimitEnable = false;
	configs.HardwareLimitSwitch.ReverseLimitRemoteSensorID = 0;
	configs.HardwareLimitSwitch.ReverseLimitAutosetPositionEnable = false;
	configs.HardwareLimitSwitch.ReverseLimitAutosetPositionValue = units::angle::turn_t(0.0);
	configs.HardwareLimitSwitch.ReverseLimitSource = ctre::phoenix6::signals::ReverseLimitSourceValue::LimitSwitchPin;
	configs.HardwareLimitSwitch.ReverseLimitType = ctre::phoenix6::signals::ReverseLimitTypeValue::NormallyOpen;

	configs.MotorOutput.Inverted = ctre::phoenix6::signals::InvertedValue::CounterClockwise_Positive;
	configs.MotorOutput.NeutralMode = ctre::phoenix6::signals::NeutralModeValue::Coast;
	configs.MotorOutput.PeakForwardDutyCycle = 1.0;
	configs.MotorOutput.PeakReverseDutyCycle = -1.0;
	configs.MotorOutput.DutyCycleNeutralDeadband = 0.0;

	configs.Feedback.FeedbackSensorSource = ctre::phoenix6::signals::FeedbackSensorSourceValue::RotorSensor;
	configs.Feedback.SensorToMechanismRatio = 1.0;

	configs.Slot0.kI = m_velocityLauncher->GetI();
	configs.Slot0.kD = m_velocityLauncher->GetD();
	configs.Slot0.kG = m_velocityLauncher->GetF();
	configs.Slot0.kS = m_velocityLauncher->GetS();
	configs.Slot0.kV = m_velocityLauncher->GetV();
	configs.Slot0.kP = m_velocityLauncher->GetP();
	configs.Slot0.kA = m_velocityLauncher->GetA();
	configs.Slot0.GravityType = ctre::phoenix6::signals::GravityTypeValue::Elevator_Static;
	configs.Slot0.StaticFeedforwardSign = ctre::phoenix6::signals::StaticFeedforwardSignValue::UseVelocitySign;

	ctre::phoenix::StatusCode status = ctre::phoenix::StatusCode::StatusCodeNotInitialized;
	for (int i = 0; i < 5; ++i)
	{
		status = m_launcherMotor->GetConfigurator().Apply(configs, units::time::second_t(0.25));
		if (status.IsOK())
			break;
	}
	if (!status.IsOK())
		Logger::GetLogger()->LogData(LOGGER_LEVEL::ERROR, "m_launcherMotor", "m_launcherMotor Status", status.GetName());
}

void Launcher::InitializeTalonFXSHoodCompBot302()
{
	TalonFXSConfiguration configs{};
	configs.CurrentLimits.StatorCurrentLimit = units::current::ampere_t(100.0);
	configs.CurrentLimits.StatorCurrentLimitEnable = true;
	configs.CurrentLimits.SupplyCurrentLimit = units::current::ampere_t(70.0);
	configs.CurrentLimits.SupplyCurrentLimitEnable = true;
	configs.CurrentLimits.SupplyCurrentLowerLimit = units::current::ampere_t(35.0);
	configs.CurrentLimits.SupplyCurrentLowerTime = units::time::second_t(0.0);

	configs.Voltage.PeakForwardVoltage = units::voltage::volt_t(11.0);
	configs.Voltage.PeakReverseVoltage = units::voltage::volt_t(-11.0);
	configs.ClosedLoopRamps.VoltageClosedLoopRampPeriod = units::time::second_t(0.1);
	configs.OpenLoopRamps.VoltageOpenLoopRampPeriod = units::time::second_t(0.1);

	configs.HardwareLimitSwitch.ForwardLimitEnable = false;
	configs.HardwareLimitSwitch.ForwardLimitRemoteSensorID = 0;
	configs.HardwareLimitSwitch.ForwardLimitAutosetPositionEnable = false;
	configs.HardwareLimitSwitch.ForwardLimitAutosetPositionValue = units::angle::turn_t(0.0);
	configs.HardwareLimitSwitch.ForwardLimitSource = ctre::phoenix6::signals::ForwardLimitSourceValue::RemoteCANifier;
	configs.HardwareLimitSwitch.ForwardLimitType = ctre::phoenix6::signals::ForwardLimitTypeValue::NormallyClosed;

	configs.HardwareLimitSwitch.ReverseLimitEnable = true;
	configs.HardwareLimitSwitch.ReverseLimitRemoteSensorID = 7;
	configs.HardwareLimitSwitch.ReverseLimitAutosetPositionEnable = true;
	configs.HardwareLimitSwitch.ReverseLimitAutosetPositionValue = units::angle::turn_t(0.0);
	configs.HardwareLimitSwitch.ReverseLimitSource = ctre::phoenix6::signals::ReverseLimitSourceValue::RemoteCANdiS1;
	configs.HardwareLimitSwitch.ReverseLimitType = ctre::phoenix6::signals::ReverseLimitTypeValue::NormallyOpen;

	configs.MotorOutput.Inverted = ctre::phoenix6::signals::InvertedValue::CounterClockwise_Positive;
	configs.MotorOutput.NeutralMode = ctre::phoenix6::signals::NeutralModeValue::Brake;
	configs.MotorOutput.PeakForwardDutyCycle = 1.0;
	configs.MotorOutput.PeakReverseDutyCycle = -1.0;
	configs.MotorOutput.DutyCycleNeutralDeadband = 0.0;

	configs.MotionMagic.MotionMagicCruiseVelocity = units::angular_velocity::turns_per_second_t(m_positionDegreesHood->GetCruiseVelocity());
	configs.MotionMagic.MotionMagicAcceleration = units::angular_acceleration::turns_per_second_squared_t(m_positionDegreesHood->GetMaxAcceleration());

	configs.Commutation.MotorArrangement = ctre::phoenix6::signals::MotorArrangementValue::Minion_JST;

	configs.ExternalFeedback.ExternalFeedbackSensorSource = ctre::phoenix6::signals::FeedbackSensorSourceValue::RotorSensor;
	configs.ExternalFeedback.SensorToMechanismRatio = 2.293864077669903;

	configs.Slot0.kI = m_positionDegreesHood->GetI();
	configs.Slot0.kD = m_positionDegreesHood->GetD();
	configs.Slot0.kG = m_positionDegreesHood->GetF();
	configs.Slot0.kS = m_positionDegreesHood->GetS();
	configs.Slot0.kV = m_positionDegreesHood->GetV();
	configs.Slot0.kP = m_positionDegreesHood->GetP();
	configs.Slot0.kA = m_positionDegreesHood->GetA();
	configs.Slot0.GravityType = ctre::phoenix6::signals::GravityTypeValue::Elevator_Static;
	configs.Slot0.StaticFeedforwardSign = ctre::phoenix6::signals::StaticFeedforwardSignValue::UseVelocitySign;

	ctre::phoenix::StatusCode status = ctre::phoenix::StatusCode::StatusCodeNotInitialized;
	for (int i = 0; i < 5; ++i)
	{
		status = m_hoodMotor->GetConfigurator().Apply(configs, units::time::second_t(0.25));
		if (status.IsOK())
			break;
	}
	if (!status.IsOK())
		Logger::GetLogger()->LogData(LOGGER_LEVEL::ERROR, "m_hoodMotor", "m_hoodMotor Status", status.GetName());
}

void Launcher::InitializeTalonFXTransferCompBot302()
{
	TalonFXConfiguration configs{};
	configs.CurrentLimits.StatorCurrentLimit = units::current::ampere_t(100.0);
	configs.CurrentLimits.StatorCurrentLimitEnable = true;
	configs.CurrentLimits.SupplyCurrentLimit = units::current::ampere_t(70.0);
	configs.CurrentLimits.SupplyCurrentLimitEnable = true;
	configs.CurrentLimits.SupplyCurrentLowerLimit = units::current::ampere_t(35.0);
	configs.CurrentLimits.SupplyCurrentLowerTime = units::time::second_t(0.0);

	configs.Voltage.PeakForwardVoltage = units::voltage::volt_t(11.0);
	configs.Voltage.PeakReverseVoltage = units::voltage::volt_t(-11.0);
	configs.ClosedLoopRamps.VoltageClosedLoopRampPeriod = units::time::second_t(0.25);
	configs.OpenLoopRamps.DutyCycleOpenLoopRampPeriod = units::time::second_t(0.1);

	configs.HardwareLimitSwitch.ForwardLimitEnable = false;
	configs.HardwareLimitSwitch.ForwardLimitRemoteSensorID = 0;
	configs.HardwareLimitSwitch.ForwardLimitAutosetPositionEnable = false;
	configs.HardwareLimitSwitch.ForwardLimitAutosetPositionValue = units::angle::turn_t(0.0);
	configs.HardwareLimitSwitch.ForwardLimitSource = ctre::phoenix6::signals::ForwardLimitSourceValue::LimitSwitchPin;
	configs.HardwareLimitSwitch.ForwardLimitType = ctre::phoenix6::signals::ForwardLimitTypeValue::NormallyOpen;

	configs.HardwareLimitSwitch.ReverseLimitEnable = false;
	configs.HardwareLimitSwitch.ReverseLimitRemoteSensorID = 0;
	configs.HardwareLimitSwitch.ReverseLimitAutosetPositionEnable = false;
	configs.HardwareLimitSwitch.ReverseLimitAutosetPositionValue = units::angle::turn_t(0.0);
	configs.HardwareLimitSwitch.ReverseLimitSource = ctre::phoenix6::signals::ReverseLimitSourceValue::LimitSwitchPin;
	configs.HardwareLimitSwitch.ReverseLimitType = ctre::phoenix6::signals::ReverseLimitTypeValue::NormallyOpen;

	configs.MotorOutput.Inverted = ctre::phoenix6::signals::InvertedValue::Clockwise_Positive;
	configs.MotorOutput.NeutralMode = ctre::phoenix6::signals::NeutralModeValue::Coast;
	configs.MotorOutput.PeakForwardDutyCycle = 1.0;
	configs.MotorOutput.PeakReverseDutyCycle = -1.0;
	configs.MotorOutput.DutyCycleNeutralDeadband = 0.0;

	configs.Feedback.FeedbackSensorSource = ctre::phoenix6::signals::FeedbackSensorSourceValue::RotorSensor;
	configs.Feedback.SensorToMechanismRatio = 1.0;

	configs.Slot0.kI = m_velocityTransfer->GetI();
	configs.Slot0.kD = m_velocityTransfer->GetD();
	configs.Slot0.kG = m_velocityTransfer->GetF();
	configs.Slot0.kS = m_velocityTransfer->GetS();
	configs.Slot0.kV = m_velocityTransfer->GetV();
	configs.Slot0.kP = m_velocityTransfer->GetP();
	configs.Slot0.kA = m_velocityTransfer->GetA();
	configs.Slot0.GravityType = ctre::phoenix6::signals::GravityTypeValue::Elevator_Static;
	configs.Slot0.StaticFeedforwardSign = ctre::phoenix6::signals::StaticFeedforwardSignValue::UseVelocitySign;

	ctre::phoenix::StatusCode status = ctre::phoenix::StatusCode::StatusCodeNotInitialized;
	for (int i = 0; i < 5; ++i)
	{
		status = m_transferMotor->GetConfigurator().Apply(configs, units::time::second_t(0.25));
		if (status.IsOK())
			break;
	}
	if (!status.IsOK())
		Logger::GetLogger()->LogData(LOGGER_LEVEL::ERROR, "m_transferMotor", "m_transferMotor Status", status.GetName());
}

void Launcher::InitializeTalonFXIndexerCompBot302()
{
	TalonFXConfiguration configs{};
	configs.CurrentLimits.StatorCurrentLimit = units::current::ampere_t(100.0);
	configs.CurrentLimits.StatorCurrentLimitEnable = true;
	configs.CurrentLimits.SupplyCurrentLimit = units::current::ampere_t(70.0);
	configs.CurrentLimits.SupplyCurrentLimitEnable = true;
	configs.CurrentLimits.SupplyCurrentLowerLimit = units::current::ampere_t(35.0);
	configs.CurrentLimits.SupplyCurrentLowerTime = units::time::second_t(0.0);

	configs.Voltage.PeakForwardVoltage = units::voltage::volt_t(11.0);
	configs.Voltage.PeakReverseVoltage = units::voltage::volt_t(-11.0);
	configs.ClosedLoopRamps.VoltageClosedLoopRampPeriod = units::time::second_t(0.25);
	configs.OpenLoopRamps.DutyCycleOpenLoopRampPeriod = units::time::second_t(0.1);

	configs.HardwareLimitSwitch.ForwardLimitEnable = false;
	configs.HardwareLimitSwitch.ForwardLimitRemoteSensorID = 0;
	configs.HardwareLimitSwitch.ForwardLimitAutosetPositionEnable = false;
	configs.HardwareLimitSwitch.ForwardLimitAutosetPositionValue = units::angle::turn_t(0.0);
	configs.HardwareLimitSwitch.ForwardLimitSource = ctre::phoenix6::signals::ForwardLimitSourceValue::LimitSwitchPin;
	configs.HardwareLimitSwitch.ForwardLimitType = ctre::phoenix6::signals::ForwardLimitTypeValue::NormallyOpen;

	configs.HardwareLimitSwitch.ReverseLimitEnable = false;
	configs.HardwareLimitSwitch.ReverseLimitRemoteSensorID = 0;
	configs.HardwareLimitSwitch.ReverseLimitAutosetPositionEnable = false;
	configs.HardwareLimitSwitch.ReverseLimitAutosetPositionValue = units::angle::turn_t(0.0);
	configs.HardwareLimitSwitch.ReverseLimitSource = ctre::phoenix6::signals::ReverseLimitSourceValue::LimitSwitchPin;
	configs.HardwareLimitSwitch.ReverseLimitType = ctre::phoenix6::signals::ReverseLimitTypeValue::NormallyOpen;

	configs.MotorOutput.Inverted = ctre::phoenix6::signals::InvertedValue::CounterClockwise_Positive;
	configs.MotorOutput.NeutralMode = ctre::phoenix6::signals::NeutralModeValue::Coast;
	configs.MotorOutput.PeakForwardDutyCycle = 1.0;
	configs.MotorOutput.PeakReverseDutyCycle = -1.0;
	configs.MotorOutput.DutyCycleNeutralDeadband = 0.0;

	configs.Feedback.FeedbackSensorSource = ctre::phoenix6::signals::FeedbackSensorSourceValue::RotorSensor;
	configs.Feedback.SensorToMechanismRatio = 3.0;

	configs.Slot0.kI = m_velocityIndexer->GetI();
	configs.Slot0.kD = m_velocityIndexer->GetD();
	configs.Slot0.kG = m_velocityIndexer->GetF();
	configs.Slot0.kS = m_velocityIndexer->GetS();
	configs.Slot0.kV = m_velocityIndexer->GetV();
	configs.Slot0.kP = m_velocityIndexer->GetP();
	configs.Slot0.kA = m_velocityIndexer->GetA();
	configs.Slot0.GravityType = ctre::phoenix6::signals::GravityTypeValue::Elevator_Static;
	configs.Slot0.StaticFeedforwardSign = ctre::phoenix6::signals::StaticFeedforwardSignValue::UseVelocitySign;

	ctre::phoenix::StatusCode status = ctre::phoenix::StatusCode::StatusCodeNotInitialized;
	for (int i = 0; i < 5; ++i)
	{
		status = m_indexerMotor->GetConfigurator().Apply(configs, units::time::second_t(0.25));
		if (status.IsOK())
			break;
	}
	if (!status.IsOK())
		Logger::GetLogger()->LogData(LOGGER_LEVEL::ERROR, "m_indexerMotor", "m_indexerMotor Status", status.GetName());
}

void Launcher::InitializeTalonFXSpindexerCompBot302()
{
	TalonFXConfiguration configs{};
	configs.CurrentLimits.StatorCurrentLimit = units::current::ampere_t(100.0);
	configs.CurrentLimits.StatorCurrentLimitEnable = true;
	configs.CurrentLimits.SupplyCurrentLimit = units::current::ampere_t(70.0);
	configs.CurrentLimits.SupplyCurrentLimitEnable = true;
	configs.CurrentLimits.SupplyCurrentLowerLimit = units::current::ampere_t(35.0);
	configs.CurrentLimits.SupplyCurrentLowerTime = units::time::second_t(0.0);

	configs.Voltage.PeakForwardVoltage = units::voltage::volt_t(11.0);
	configs.Voltage.PeakReverseVoltage = units::voltage::volt_t(-11.0);
	configs.ClosedLoopRamps.VoltageClosedLoopRampPeriod = units::time::second_t(0.25);
	configs.OpenLoopRamps.DutyCycleOpenLoopRampPeriod = units::time::second_t(0.1);

	configs.HardwareLimitSwitch.ForwardLimitEnable = false;
	configs.HardwareLimitSwitch.ForwardLimitRemoteSensorID = 0;
	configs.HardwareLimitSwitch.ForwardLimitAutosetPositionEnable = false;
	configs.HardwareLimitSwitch.ForwardLimitAutosetPositionValue = units::angle::turn_t(0.0);
	configs.HardwareLimitSwitch.ForwardLimitSource = ctre::phoenix6::signals::ForwardLimitSourceValue::LimitSwitchPin;
	configs.HardwareLimitSwitch.ForwardLimitType = ctre::phoenix6::signals::ForwardLimitTypeValue::NormallyOpen;

	configs.HardwareLimitSwitch.ReverseLimitEnable = false;
	configs.HardwareLimitSwitch.ReverseLimitRemoteSensorID = 0;
	configs.HardwareLimitSwitch.ReverseLimitAutosetPositionEnable = false;
	configs.HardwareLimitSwitch.ReverseLimitAutosetPositionValue = units::angle::turn_t(0.0);
	configs.HardwareLimitSwitch.ReverseLimitSource = ctre::phoenix6::signals::ReverseLimitSourceValue::LimitSwitchPin;
	configs.HardwareLimitSwitch.ReverseLimitType = ctre::phoenix6::signals::ReverseLimitTypeValue::NormallyOpen;

	configs.MotorOutput.Inverted = ctre::phoenix6::signals::InvertedValue::CounterClockwise_Positive;
	configs.MotorOutput.NeutralMode = ctre::phoenix6::signals::NeutralModeValue::Coast;
	configs.MotorOutput.PeakForwardDutyCycle = 1.0;
	configs.MotorOutput.PeakReverseDutyCycle = -1.0;
	configs.MotorOutput.DutyCycleNeutralDeadband = 0.0;

	configs.Feedback.FeedbackSensorSource = ctre::phoenix6::signals::FeedbackSensorSourceValue::RotorSensor;
	configs.Feedback.SensorToMechanismRatio = 3.0;

	configs.Slot0.kI = m_velocityLauncher->GetI();
	configs.Slot0.kD = m_velocityLauncher->GetD();
	configs.Slot0.kG = m_velocityLauncher->GetF();
	configs.Slot0.kS = m_velocityLauncher->GetS();
	configs.Slot0.kV = m_velocityLauncher->GetV();
	configs.Slot0.kP = m_velocityLauncher->GetP();
	configs.Slot0.kA = m_velocityLauncher->GetA();
	configs.Slot0.GravityType = ctre::phoenix6::signals::GravityTypeValue::Elevator_Static;
	configs.Slot0.StaticFeedforwardSign = ctre::phoenix6::signals::StaticFeedforwardSignValue::UseVelocitySign;

	ctre::phoenix::StatusCode status = ctre::phoenix::StatusCode::StatusCodeNotInitialized;
	for (int i = 0; i < 5; ++i)
	{
		status = m_spindexerMotor->GetConfigurator().Apply(configs, units::time::second_t(0.25));
		if (status.IsOK())
			break;
	}
	if (!status.IsOK())
		Logger::GetLogger()->LogData(LOGGER_LEVEL::ERROR, "m_spindexerMotor", "m_spindexerMotor Status", status.GetName());
}

void Launcher::InitializeCANdiHoodCompBot302()
{
	CANdiConfiguration CANdiConfig{};

	CANdiConfig.DigitalInputs.S1CloseState = ctre::phoenix6::signals::S1CloseStateValue::CloseWhenNotFloating;
	CANdiConfig.DigitalInputs.S1FloatState = ctre::phoenix6::signals::S1FloatStateValue::BusKeeper;
	CANdiConfig.DigitalInputs.S2CloseState = ctre::phoenix6::signals::S2CloseStateValue::CloseWhenNotLow;
	CANdiConfig.DigitalInputs.S2FloatState = ctre::phoenix6::signals::S2FloatStateValue::FloatDetect;

	ctre::phoenix::StatusCode status = ctre::phoenix::StatusCode::StatusCodeNotInitialized;
	for (int i = 0; i < 5; ++i)
	{
		status = m_hoodCANdi->GetConfigurator().Apply(CANdiConfig, units::time::second_t(0.25));
		if (status.IsOK())
			break;
	}
	if (!status.IsOK())
		Logger::GetLogger()->LogData(LOGGER_LEVEL::ERROR, "m_hoodCANdi", "m_hoodCANdi Status", status.GetName());
}

void Launcher::InitializeCANdiTurretCompBot302()
{
	CANdiConfiguration CANdiConfig{};

	CANdiConfig.DigitalInputs.S1CloseState = ctre::phoenix6::signals::S1CloseStateValue::CloseWhenFloating;
	CANdiConfig.DigitalInputs.S1FloatState = ctre::phoenix6::signals::S1FloatStateValue::FloatDetect;
	CANdiConfig.DigitalInputs.S2CloseState = ctre::phoenix6::signals::S2CloseStateValue::CloseWhenFloating;
	CANdiConfig.DigitalInputs.S2FloatState = ctre::phoenix6::signals::S2FloatStateValue::FloatDetect;

	ctre::phoenix::StatusCode status = ctre::phoenix::StatusCode::StatusCodeNotInitialized;
	for (int i = 0; i < 5; ++i)
	{
		status = m_turretCANdi->GetConfigurator().Apply(CANdiConfig, units::time::second_t(0.25));
		if (status.IsOK())
			break;
	}
	if (!status.IsOK())
		Logger::GetLogger()->LogData(LOGGER_LEVEL::ERROR, "m_turretCANdi", "m_turretCANdi Status", status.GetName());
}

void Launcher::InitializeTalonFXSTurretCompBot302()
{
	TalonFXSConfiguration configs{};
	configs.CurrentLimits.StatorCurrentLimit = units::current::ampere_t(45.0);
	configs.CurrentLimits.StatorCurrentLimitEnable = true;
	configs.CurrentLimits.SupplyCurrentLimit = units::current::ampere_t(70.0);
	configs.CurrentLimits.SupplyCurrentLimitEnable = true;
	configs.CurrentLimits.SupplyCurrentLowerLimit = units::current::ampere_t(35.0);
	configs.CurrentLimits.SupplyCurrentLowerTime = units::time::second_t(0.0);

	configs.Voltage.PeakForwardVoltage = units::voltage::volt_t(11.0);
	configs.Voltage.PeakReverseVoltage = units::voltage::volt_t(-11.0);
	configs.ClosedLoopRamps.VoltageClosedLoopRampPeriod = units::time::second_t(0.25);
	configs.OpenLoopRamps.DutyCycleOpenLoopRampPeriod = units::time::second_t(0.1);

	configs.HardwareLimitSwitch.ForwardLimitEnable = true;
	configs.HardwareLimitSwitch.ForwardLimitRemoteSensorID = 6;
	configs.HardwareLimitSwitch.ForwardLimitAutosetPositionEnable = false;
	configs.HardwareLimitSwitch.ForwardLimitAutosetPositionValue = units::angle::turn_t(0.0);
	configs.HardwareLimitSwitch.ForwardLimitSource = ctre::phoenix6::signals::ForwardLimitSourceValue::RemoteCANdiS2;
	configs.HardwareLimitSwitch.ForwardLimitType = ctre::phoenix6::signals::ForwardLimitTypeValue::NormallyOpen;

	configs.HardwareLimitSwitch.ReverseLimitEnable = true;
	configs.HardwareLimitSwitch.ReverseLimitRemoteSensorID = 6;
	configs.HardwareLimitSwitch.ReverseLimitAutosetPositionEnable = false;
	configs.HardwareLimitSwitch.ReverseLimitAutosetPositionValue = units::angle::turn_t(0.0);
	configs.HardwareLimitSwitch.ReverseLimitSource = ctre::phoenix6::signals::ReverseLimitSourceValue::RemoteCANdiS1;
	configs.HardwareLimitSwitch.ReverseLimitType = ctre::phoenix6::signals::ReverseLimitTypeValue::NormallyOpen;

	configs.MotorOutput.Inverted = ctre::phoenix6::signals::InvertedValue::CounterClockwise_Positive;
	configs.MotorOutput.NeutralMode = ctre::phoenix6::signals::NeutralModeValue::Brake;
	configs.MotorOutput.PeakForwardDutyCycle = 1.0;
	configs.MotorOutput.PeakReverseDutyCycle = -1.0;
	configs.MotorOutput.DutyCycleNeutralDeadband = 0.0;

	configs.MotionMagic.MotionMagicCruiseVelocity = units::angular_velocity::turns_per_second_t(m_positionDegreesTurret->GetCruiseVelocity());
	configs.MotionMagic.MotionMagicAcceleration = units::angular_acceleration::turns_per_second_squared_t(m_positionDegreesTurret->GetMaxAcceleration());

	configs.Commutation.MotorArrangement = ctre::phoenix6::signals::MotorArrangementValue::Minion_JST;

	configs.ExternalFeedback.ExternalFeedbackSensorSource = ctre::phoenix6::signals::FeedbackSensorSourceValue::RotorSensor;
	configs.ExternalFeedback.SensorToMechanismRatio = 0.1343032550470101;

	configs.Slot0.kI = m_positionDegreesTurret->GetI();
	configs.Slot0.kD = m_positionDegreesTurret->GetD();
	configs.Slot0.kG = m_positionDegreesTurret->GetF();
	configs.Slot0.kS = m_positionDegreesTurret->GetS();
	configs.Slot0.kV = m_positionDegreesTurret->GetV();
	configs.Slot0.kP = m_positionDegreesTurret->GetP();
	configs.Slot0.kA = m_positionDegreesTurret->GetA();
	configs.Slot0.GravityType = ctre::phoenix6::signals::GravityTypeValue::Arm_Cosine;
	configs.Slot0.StaticFeedforwardSign = ctre::phoenix6::signals::StaticFeedforwardSignValue::UseVelocitySign;

	ctre::phoenix::StatusCode status = ctre::phoenix::StatusCode::StatusCodeNotInitialized;
	for (int i = 0; i < 5; ++i)
	{
		status = m_turretMotor->GetConfigurator().Apply(configs, units::time::second_t(0.25));
		if (status.IsOK())
			break;
	}
	if (!status.IsOK())
		Logger::GetLogger()->LogData(LOGGER_LEVEL::ERROR, "m_turretMotor", "m_turretMotor Status", status.GetName());
}

void Launcher::SetCurrentState(int state, bool run)
{
	// Autonomous bridge: schedule the command that corresponds to the requested state.
	// Cancel the previous auton command first so its requirement on this subsystem is released
	// before the owning CommandPtr is replaced.
	m_autonCommand.Cancel();
	m_autonCommand = GetCommandForState(static_cast<STATE_NAMES>(state));
	if (run)
	{
		frc2::CommandScheduler::GetInstance().Schedule(m_autonCommand);
	}
}

void Launcher::RefreshCachedData()
{
	m_cachedLauncherVelocity = m_launcherMotor->GetVelocity().GetValue();
	m_cachedHoodPosition = m_hoodMotor->GetPosition().GetValue();
	m_cachedTurretPosition = m_turretEnabled ? units::angle::degree_t(m_turretMotor->GetPosition().GetValueAsDouble()) : 180.0_deg;
	m_cachedLauncherCurrent = m_launcherMotor->GetStatorCurrent().GetValue();

	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, m_ntName, "Launcher Speed", units::angular_velocity::revolutions_per_minute_t(m_cachedLauncherVelocity).value());
	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, m_ntName, "Hood Position", m_cachedHoodPosition.value());
	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, m_ntName, "turret position", m_cachedTurretPosition.value());
}

void Launcher::Periodic()
{
	// This function is called once per loop by the CommandScheduler (all modes) before any
	// scheduled command's execute(). It performs the per-loop housekeeping that used to live
	// in StateMgr::RunCommonTasks(): refresh cached sensor data, apply manual control, and
	// push the active control requests to the motors.
	RefreshCachedData();
	UpdateCachedLoggingValues();

	Update();

	if (frc::DriverStation::IsDisabled())
	{
		InitializeLauncher();
		m_targetCalculator->ForceUpdateChassisPose();
	}

	SetLauncherProtect();

	if (!m_tuningLauncher)
	{
		m_targetCalculator->UpdateTargetOffset();
	}
	CalculateTargets();
	UpdateLauncherTargets();

	// Logging
	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, m_ntName, "Current State", GetCurrentStateName());
}

/// @brief update the output to the mechanism using the current controller and target value(s)
/// @return void
void Launcher::Update()
{
	m_launcherMotor->SetControl(*m_launcherActiveTarget);
	m_hoodMotor->SetControl(*m_hoodActiveTarget);
	m_transferMotor->SetControl(*m_transferActiveTarget);
	m_indexerMotor->SetControl(*m_indexerActiveTarget);
	m_spindexerMotor->SetControl(*m_spindexerActiveTarget);
	m_turretMotor->SetControl(*m_turretActiveTarget);
}

ControlData *Launcher::GetControlData(string name)
{
	if (name.compare("m_percentOut") == 0)
		return m_percentOut;
	else if (name.compare("m_velocityLauncher") == 0)
		return m_velocityLauncher;
	else if (name.compare("m_velocityLauncherFullField") == 0)
		return m_velocityLauncherFullField;
	else if (name.compare("m_velocityIndexer") == 0)
		return m_velocityIndexer;
	else if (name.compare("m_velocitySpindexer") == 0)
		return m_velocitySpindexer;
	else if (name.compare("m_velocityTransfer") == 0)
		return m_velocityTransfer;
	else if (name.compare("m_positionDegreesHood") == 0)
		return m_positionDegreesHood;
	else if (name.compare("m_positionDegreesTurret") == 0)
		return m_positionDegreesTurret;
	else if (name.compare("m_positionTurnSpindexer") == 0)
		return m_positionTurnSpindexer;
	return nullptr;
}

void Launcher::DataLog(uint64_t timestamp)
{
	// Mechanism State
	LogStringData(timestamp, m_launcherStatePath, GetCurrentStateName());

	// Control Requests/Targets
	LogDoubleData(timestamp, m_loggingLauncherTargetPath, m_launcherVelocityLauncher.Velocity.value());
	LogDoubleData(timestamp, m_loggingLauncherVelocityPath, m_cachedLauncherVelocityLauncher.value());
	LogStringData(timestamp, m_loggingLauncherControlRequest, std::string(m_launcherActiveTarget->GetName()));
	LogDoubleData(timestamp, m_loggingHoodTargetPath, m_hoodPositionDegreesHood.Position.value());
	LogDoubleData(timestamp, m_loggingHoodPositionPath, m_cachedHoodPositionDegreesHood.value());
	LogStringData(timestamp, m_loggingHoodControlRequest, std::string(m_hoodActiveTarget->GetName()));
	LogDoubleData(timestamp, m_loggingTransferTargetPath, m_transferVelocityTransfer.Velocity.value());
	LogDoubleData(timestamp, m_loggingTransferVelocityPath, m_cachedTransferVelocityTransfer.value());
	LogStringData(timestamp, m_loggingTransferControlRequest, std::string(m_transferActiveTarget->GetName()));
	LogDoubleData(timestamp, m_loggingIndexerTargetPath, m_indexerVelocityIndexer.Velocity.value());
	LogDoubleData(timestamp, m_loggingIndexerVelocityPath, m_cachedIndexerVelocityIndexer.value());
	LogStringData(timestamp, m_loggingIndexerControlRequest, std::string(m_indexerActiveTarget->GetName()));
	LogDoubleData(timestamp, m_loggingSpindexerTargetPath, m_spindexerVelocityLauncher.Velocity.value());
	LogDoubleData(timestamp, m_loggingSpindexerVelocityPath, m_cachedSpindexerVelocityLauncher.value());
	LogStringData(timestamp, m_loggingSpindexerControlRequest, std::string(m_spindexerActiveTarget->GetName()));
	LogDoubleData(timestamp, m_loggingTurretTargetPath, m_turretPositionDegreesTurret.Position.value());
	LogDoubleData(timestamp, m_loggingTurretPositionPath, m_cachedTurretPositionDegreesTurret.value());
	LogStringData(timestamp, m_loggingTurretControlRequest, std::string(m_turretActiveTarget->GetName()));
}

// --- Handwritten Methods ---

void Launcher::NotifyStateUpdate(RobotStateChanges::StateChange statechange, bool value)
{
	if (statechange == RobotStateChanges::StateChange::ClimbModeStatus_Bool)
	{
		m_isClimbMode = value;
	}
	else if (statechange == RobotStateChanges::StateChange::AllowedToClimbStatus_Bool)
	{
		m_isAllowedToClimb = value;
	}
	else if (statechange == RobotStateChanges::StateChange::HubActive_Bool)
	{
		m_isHubActive = value;
	}
	else if (statechange == RobotStateChanges::StateChange::StartLaunching_Bool)
	{
		m_startLaunching = value;
	}
	else if (statechange == RobotStateChanges::StateChange::IsIntaking_Bool)
	{
		m_isIntaking = value;
	}
}

void Launcher::PublishLaunchMode(bool launching)
{
	RobotState::GetInstance()->PublishStateChange(RobotStateChanges::StateChange::IsLaunching_Bool, launching);
}

bool Launcher::IsLauncherAtTarget()
{
	if (frc::RobotBase::IsSimulation() && !(GetCurrentState() == STATE_NAMES::STATE_LAUNCHER_TUNING))
	{
		return m_cachedinLaunchzone;
	}
	else
	{
		return (m_cachedHoodError && m_cachedinLaunchzone && m_cachedIsChassisSpeed && m_cachedLauncherSpeedError && m_cachedTurretAtTarget);
	}
}

bool Launcher::IsInLaunchZone() const
{
	if (!m_deadZoneManager->IsInDeadZone())
	{
		return !(m_allianceZoneManager->IsInAllianceZone() && !(m_isHubActive || m_startLaunching));
	}
	return false;
}

void Launcher::CalculateTargets()
{

	if (m_turretEnabled)
	{
		m_targetTurretAngle = m_targetCalculator->GetLauncherTarget(m_cachedTurretPosition);
	}
	else
	{
		m_targetTurretAngle = 180_deg;
		m_chassis->SetTargetChassisRotation(m_targetCalculator->GetChassisTargetForLaunching());
	}
	m_distanceToTarget = m_targetCalculator->GetLauncherDistanceToTarget();
	if (m_allianceZoneManager->IsInAllianceZone())
	{
		m_targetHoodAngle = InterpolateUtils::linearInterpolate(m_scoringDistanceArray, m_scoringHoodAngleArray, m_distanceToTarget);
		m_targetLauncherAngularVelocity = InterpolateUtils::linearInterpolate(m_scoringDistanceArray, m_scoringLauncherVelocityArray, m_distanceToTarget);
	}
	else
	{
		m_targetHoodAngle = InterpolateUtils::linearInterpolate(m_passingDistanceArray, m_passingHoodAngleArray, units::length::foot_t(m_distanceToTarget));
		m_targetLauncherAngularVelocity = InterpolateUtils::linearInterpolate(m_passingDistanceArray, m_passingLauncherVelocityArray, units::length::foot_t(m_distanceToTarget));
	}

	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, m_ntName, "Distance", m_distanceToTarget.value());
	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, m_ntName, "Target Hood", m_targetHoodAngle.value());
	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, m_ntName, "Target Launcher Velocity", m_targetLauncherAngularVelocity.value());
	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, m_ntName, "turret Target", m_targetTurretAngle.value());
}

void Launcher::UpdateLauncherTargets()
{
	int currentState = GetCurrentState();

	if (currentState == STATE_NAMES::STATE_OFF || currentState == STATE_NAMES::STATE_INITIALIZE || currentState == STATE_NAMES::STATE_MANUAL_LAUNCH || m_tuningLauncher)
	{
		return;
	}

	UpdateTargetHoodPositionDegreesHood(m_targetHoodAngle);

	if (m_turretEnabled)
	{
		UpdateTargetTurretPositionDegreesTurret(m_targetTurretAngle);
	}

	if (currentState == STATE_NAMES::STATE_LAUNCH || currentState == STATE_NAMES::STATE_PREPARE_TO_LAUNCH)
	{
		UpdateTargetLauncherVelocityLauncher(m_targetLauncherAngularVelocity);
	}
}

void Launcher::InitializeLauncher()
{
	bool turretReverseLimitSwitchTripped = false;
	bool turretForwardLimitSwitchTripped = false;

	if (m_turretEnabled)
	{
		turretReverseLimitSwitchTripped = m_turretMotor->GetReverseLimit().GetValue() == ctre::phoenix6::signals::ReverseLimitValue::ClosedToGround;
		turretForwardLimitSwitchTripped = m_turretMotor->GetForwardLimit().GetValue() == ctre::phoenix6::signals::ForwardLimitValue::ClosedToGround;
		if (turretForwardLimitSwitchTripped)
		{
			m_turretMotor->SetPosition(m_maxTurretAngle);
			m_turretHasReset = true;
		}
		else if (turretReverseLimitSwitchTripped)
		{
			m_turretMotor->SetPosition(m_minTurretAngle);
			m_turretHasReset = true;
		}
	}

	auto hoodReverseLimitSwitchTripped = m_hoodMotor->GetReverseLimit().GetValue() == ctre::phoenix6::signals::ReverseLimitValue::ClosedToGround;

	if ((m_turretEnabled && m_turretHasReset && hoodReverseLimitSwitchTripped) ||
		(!m_turretEnabled && hoodReverseLimitSwitchTripped) ||
		frc::RobotBase::IsSimulation())
	{
		m_launcherInitialized = true;
	}
}

void Launcher::SetLauncherProtect()
{
	if (TeleopControl::GetInstance()->IsButtonPressed(TeleopControlFunctions::LAUNCHER_OFF))
	{
		if (m_launcherOffButtonReleased)
		{
			m_launcherProtectedMode = !m_launcherProtectedMode;
		}
		m_launcherOffButtonReleased = false;
	}
	else
	{
		m_launcherOffButtonReleased = true;
	}
}

bool Launcher::IsTurretAtTarget()
{
	m_cachedTurretAtTarget = false;
	if (frc::RobotBase::IsSimulation() && !(GetCurrentState() == STATE_NAMES::STATE_LAUNCHER_TUNING))
	{
		return true;
	}
	if (m_turretEnabled)
	{
		if (m_hasValidTurretAngle)
		{
			units::angle::degree_t turretError = m_cachedTurretPosition - m_targetTurretAngle;
			m_cachedTurretAtTarget = ((units::math::abs(turretError) < m_turretAngleThreshold));
		}
	}
	else
	{
		m_cachedTurretAtTarget = true; // m_chassis->IsChassisAtRotationTarget();
	}

	return m_cachedTurretAtTarget;
}

void Launcher::UpdateTurretEnabled()
{
	if (TeleopControl::GetInstance()->IsButtonPressed(TeleopControlFunctions::TURRET_ENABLE) && m_turretEnabledButtonReleased)
	{
		if (m_turretEnabledButtonReleased)
			m_turretEnabled = !m_turretEnabled;
	}
	m_turretEnabledButtonReleased = !TeleopControl::GetInstance()->IsButtonPressed(TeleopControlFunctions::TURRET_ENABLE);
	RobotState::GetInstance()->PublishStateChange(RobotStateChanges::StateChange::TurretEnabled_Bool, m_turretEnabled);
}

bool Launcher::IsFinishedLaunching()
{

	if (m_cachedLauncherCurrent > m_isLaunchingCurrentThreshold)
	{
		m_launchCurrentTimer.Reset();
		m_launchCurrentTimer.Start();
	}
	else if (m_launchCurrentTimer.Get() > m_isLaunchingTimeThreshold)
	{
		return true;
	}

	return false;
}

void Launcher::UpdateCachedLoggingValues()
{
	units::angle::degree_t hoodError = units::angle::degree_t(std::abs((m_cachedHoodPosition - m_targetHoodAngle).value()));
	units::angular_velocity::revolutions_per_minute_t launcherSpeedError = units::math::abs((m_cachedLauncherVelocity - m_targetLauncherAngularVelocity));
	bool inLaunchzone = IsInLaunchZone();
	auto chassisSpeeds = m_chassis != nullptr ? m_chassis->GetState().Speeds : frc::ChassisSpeeds();
	auto Speed = units::math::sqrt(units::math::abs(chassisSpeeds.vx * chassisSpeeds.vx) + units::math::abs(chassisSpeeds.vy * chassisSpeeds.vy));

	m_hasValidTurretAngle = m_targetCalculator->IsValidTurretAngle();
	m_cachedHoodError = (hoodError < m_hoodAngleThreshold);
	m_cachedLauncherSpeedError = launcherSpeedError < m_launcherVelocityThreshold;
	m_cachedinLaunchzone = (inLaunchzone);
	m_cachedIsChassisSpeed = !AllianceZoneManager::GetInstance()->IsInAllianceZone() ? true : (Speed < m_chassisSpeedThreshold);
	bool turretAtTarget = IsTurretAtTarget();
	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, m_ntName, "m_cachedHoodError", m_cachedHoodError);
	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, m_ntName, "m_cachedLauncherSpeedError", m_cachedLauncherSpeedError);
	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, m_ntName, "m_cachedinLaunchzone", m_cachedinLaunchzone);
	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, m_ntName, "m_targetTurretAngle", turretAtTarget);
}

void Launcher::AgitateSpindexer()
{

	auto currentSpindexerPosition = m_spindexerMotor->GetPosition().GetValue();

	UpdateTargetSpindexerPositionTurnSpindexer(m_minReached ? m_maxSpindexerTarget : m_minSpindexerTarget);

	if (currentSpindexerPosition <= m_minSpindexerTarget)
	{
		m_minReached = true;
	}
	else if (currentSpindexerPosition >= m_maxSpindexerTarget)
	{
		m_minReached = false;
	}
}

void Launcher::InitializeSpindexerTargets()
{
	m_maxSpindexerTarget = m_spindexerMotor->GetPosition().GetValue();
	m_minSpindexerTarget = m_maxSpindexerTarget - m_spindexerTargetAng;
	m_minReached = false;
}