//====================================================================================================================================================
// Copyright 2026 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
// This file was automatically generated by the Team 302 code generator version 20.26.00.00
// Generated on Thursday, January 22, 2026 11:43:04 PM

#pragma once
#include <string>

#include "mechanisms/Launcher/Launcher.h"
#include "state/State.h"

using namespace std;

namespace LauncherStates
{
	class LaunchState : public State
	{
	public:
		LaunchState() = delete;
		LaunchState(std::string stateName,
					int stateId,
					Launcher *mech,
					RobotIdentifier activeRobotId);
		~LaunchState() = default;
		void Init() override;
		void Run() override;
		void Exit() override;
		bool AtTarget() override;
		bool IsTransitionCondition(bool considerGamepadTransitions) override;

	private:
		Launcher *m_mechanism;
		void InitCompBot302();
		RobotIdentifier m_RobotId;

		const wpi::units::angular_velocity::turns_per_second_t m_launcherTarget = wpi::units::angular_velocity::turns_per_second_t(0);
		const wpi::units::angle::turn_t m_hoodTarget = wpi::units::angle::turn_t(0);
		const wpi::units::angular_velocity::turns_per_second_t m_passingTransferTarget{160};
		const wpi::units::angular_velocity::turns_per_second_t m_scoringTransferTarget{80};

		const wpi::units::angle::turn_t m_turretTarget = wpi::units::angle::turn_t(0);
		const wpi::units::angular_velocity::turns_per_second_t m_passingIndexerTarget{50};
		const wpi::units::angular_velocity::turns_per_second_t m_scoringIndexerTarget{25};

		const wpi::units::angular_velocity::turns_per_second_t m_spindexerTarget{22};
	};
}
