//====================================================================================================================================================
// Copyright 2026 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
// This file was automatically generated by the Team 302 code generator version 20.26.00.00
// Generated on Thursday, January 22, 2026 11:43:04 PM

#include <string>

// FRC Includes
#include "wpi/nt/NetworkTableInstance.hpp"
#include <wpi/system/Timer.hpp>

#include "Launcher.h"
#include "state/RobotState.h"
#include "utils/DragonPower.h"
#include "utils/PeriodicLooper.h"
#include "utils/logging/debug/Logger.h"

#include "ctre/phoenix6/TalonFX.hpp"
#include "ctre/phoenix6/TalonFXS.hpp"
#include "ctre/phoenix6/configs/Configuration.hpp"
#include "ctre/phoenix6/controls/Follower.hpp"
#include "mechanisms/Launcher/AgitatorState.h"
#include "mechanisms/Launcher/ClimbState.h"
#include "mechanisms/Launcher/EmptyHopperState.h"
#include "mechanisms/Launcher/IdleState.h"
#include "mechanisms/Launcher/InitializeState.h"
#include "mechanisms/Launcher/LaunchState.h"
#include "mechanisms/Launcher/LauncherTuningState.h"
#include "mechanisms/Launcher/ManualLaunchState.h"
#include "mechanisms/Launcher/OffState.h"
#include "mechanisms/Launcher/PrepareToLaunchState.h"

#include "teleopcontrol/TeleopControl.h"
#include "utils/InterpolateUtils.h"
#include "wpi/framework/RobotBase.hpp"
#include "wpi/units/math.hpp"

using ctre::phoenix6::configs::CANdiConfiguration;
using ctre::phoenix6::configs::Slot0Configs;
using ctre::phoenix6::configs::Slot1Configs;
using ctre::phoenix6::configs::TalonFXConfiguration;
using ctre::phoenix6::configs::TalonFXSConfiguration;
using ctre::phoenix6::signals::FeedbackSensorSourceValue;
using ctre::phoenix6::signals::ForwardLimitSourceValue;
using ctre::phoenix6::signals::ForwardLimitTypeValue;
using ctre::phoenix6::signals::GravityTypeValue;
using ctre::phoenix6::signals::InvertedValue;
using ctre::phoenix6::signals::MotorArrangementValue;
using ctre::phoenix6::signals::NeutralModeValue;
using ctre::phoenix6::signals::ReverseLimitSourceValue;
using ctre::phoenix6::signals::ReverseLimitTypeValue;
using ctre::phoenix6::signals::StaticFeedforwardSignValue;

using std::string;
using namespace LauncherStates;

void Launcher::CreateAndRegisterStates()
{
	OffState *OffStateInst = new OffState(string("Off"), 0, this, m_activeRobotId);
	AddToStateVector(OffStateInst);

	InitializeState *InitializeStateInst = new InitializeState(string("Initialize"), 1, this, m_activeRobotId);
	AddToStateVector(InitializeStateInst);

	IdleState *IdleStateInst = new IdleState(string("Idle"), 2, this, m_activeRobotId);
	AddToStateVector(IdleStateInst);

	PrepareToLaunchState *PrepareToLaunchStateInst = new PrepareToLaunchState(string("PrepareToLaunch"), 3, this, m_activeRobotId);
	AddToStateVector(PrepareToLaunchStateInst);

	LaunchState *LaunchStateInst = new LaunchState(string("Launch"), 4, this, m_activeRobotId);
	AddToStateVector(LaunchStateInst);

	EmptyHopperState *EmptyHopperStateInst = new EmptyHopperState(string("EmptyHopper"), 5, this, m_activeRobotId);
	AddToStateVector(EmptyHopperStateInst);

	ClimbState *ClimbStateInst = new ClimbState(string("Climb"), 6, this, m_activeRobotId);
	AddToStateVector(ClimbStateInst);

	LauncherTuningState *LauncherTuningStateInst = new LauncherTuningState(string("LauncherTuning"), 7, this, m_activeRobotId);
	AddToStateVector(LauncherTuningStateInst);

	ManualLaunchState *ManualLaunchStateInst = new ManualLaunchState(string("ManualLaunch"), 8, this, m_activeRobotId);
	AddToStateVector(ManualLaunchStateInst);

	AgitatorState *AgitatorStateInst = new AgitatorState(string("Agitator"), 9, this, m_activeRobotId);
	AddToStateVector(AgitatorStateInst);

	OffStateInst->RegisterTransitionState(InitializeStateInst);
	InitializeStateInst->RegisterTransitionState(IdleStateInst);
	IdleStateInst->RegisterTransitionState(OffStateInst);
	IdleStateInst->RegisterTransitionState(PrepareToLaunchStateInst);
	IdleStateInst->RegisterTransitionState(EmptyHopperStateInst);
	IdleStateInst->RegisterTransitionState(ClimbStateInst);
	IdleStateInst->RegisterTransitionState(LauncherTuningStateInst);
	IdleStateInst->RegisterTransitionState(ManualLaunchStateInst);
	IdleStateInst->RegisterTransitionState(AgitatorStateInst);
	PrepareToLaunchStateInst->RegisterTransitionState(OffStateInst);
	PrepareToLaunchStateInst->RegisterTransitionState(IdleStateInst);
	PrepareToLaunchStateInst->RegisterTransitionState(LaunchStateInst);
	PrepareToLaunchStateInst->RegisterTransitionState(EmptyHopperStateInst);
	PrepareToLaunchStateInst->RegisterTransitionState(ClimbStateInst);
	LaunchStateInst->RegisterTransitionState(OffStateInst);
	LaunchStateInst->RegisterTransitionState(IdleStateInst);
	LaunchStateInst->RegisterTransitionState(PrepareToLaunchStateInst);
	EmptyHopperStateInst->RegisterTransitionState(OffStateInst);
	EmptyHopperStateInst->RegisterTransitionState(IdleStateInst);
	EmptyHopperStateInst->RegisterTransitionState(ClimbStateInst);
	ClimbStateInst->RegisterTransitionState(OffStateInst);
	ClimbStateInst->RegisterTransitionState(IdleStateInst);
	ClimbStateInst->RegisterTransitionState(PrepareToLaunchStateInst);
	LauncherTuningStateInst->RegisterTransitionState(OffStateInst);
	LauncherTuningStateInst->RegisterTransitionState(LaunchStateInst);
	ManualLaunchStateInst->RegisterTransitionState(OffStateInst);
	ManualLaunchStateInst->RegisterTransitionState(IdleStateInst);
	AgitatorStateInst->RegisterTransitionState(OffStateInst);
	AgitatorStateInst->RegisterTransitionState(IdleStateInst);
	AgitatorStateInst->RegisterTransitionState(PrepareToLaunchStateInst);
	AgitatorStateInst->RegisterTransitionState(ManualLaunchStateInst);
}

Launcher::Launcher(RobotIdentifier activeRobotId) : BaseMech(MechanismTypes::MECHANISM_TYPE::LAUNCHER, std::string("Launcher")),
													m_activeRobotId(activeRobotId),
													m_stateMap(),
													m_chassis(ChassisConfigMgr::GetInstance()->GetSwerveChassis())
{
	PeriodicLooper::GetInstance()->RegisterAll(this);
	RobotState::GetInstance()->RegisterForStateChanges(this, RobotStateChanges::StateChange::AllowedToClimbStatus_Bool);
	RobotState::GetInstance()->RegisterForStateChanges(this, RobotStateChanges::StateChange::ClimbModeStatus_Bool);
	RobotState::GetInstance()->RegisterForStateChanges(this, RobotStateChanges::StateChange::HubActive_Bool);
	RobotState::GetInstance()->RegisterForStateChanges(this, RobotStateChanges::StateChange::IsIntaking_Bool);
	RobotState::GetInstance()->RegisterForStateChanges(this, RobotStateChanges::StateChange::StartLaunching_Bool);
	RobotState::GetInstance()->PublishStateChange(RobotStateChanges::StateChange::TurretEnabled_Bool, m_turretEnabled);
	m_targetCalculator = RebuiltTargetCalculator::GetInstance();
	m_allianceZoneManager = AllianceZoneManager::GetInstance();
	m_deadZoneManager = DeadZoneManager::GetInstance();

	m_launcherVelocityRPS.EnableFOC = true;
	m_spindexerVelocityRPS.EnableFOC = true;
	m_indexerVelocityRPS.EnableFOC = true;
	m_transferVelocityRPS.EnableFOC = true;
	m_turretPositionDegreesTurret.EnableFOC = true;
}

std::map<std::string, Launcher::STATE_NAMES>
	Launcher::stringToSTATE_NAMESEnumMap{
		{"STATE_OFF", Launcher::STATE_NAMES::STATE_OFF},
		{"STATE_INITIALIZE", Launcher::STATE_NAMES::STATE_INITIALIZE},
		{"STATE_IDLE", Launcher::STATE_NAMES::STATE_IDLE},
		{"STATE_PREPARE_TO_LAUNCH", Launcher::STATE_NAMES::STATE_PREPARE_TO_LAUNCH},
		{"STATE_LAUNCH", Launcher::STATE_NAMES::STATE_LAUNCH},
		{"STATE_EMPTY_HOPPER", Launcher::STATE_NAMES::STATE_EMPTY_HOPPER},
		{"STATE_CLIMB", Launcher::STATE_NAMES::STATE_CLIMB},
		{"STATE_LAUNCHER_TUNING", Launcher::STATE_NAMES::STATE_LAUNCHER_TUNING},
		{"STATE_MANUAL_LAUNCH", Launcher::STATE_NAMES::STATE_MANUAL_LAUNCH},
		{"STATE_AGITATOR", Launcher::STATE_NAMES::STATE_AGITATOR}};

std::map<Launcher::STATE_NAMES, std::string>
	Launcher::STATE_NAMESEnumToStringMap{
		{Launcher::STATE_NAMES::STATE_OFF, "STATE_OFF"},
		{Launcher::STATE_NAMES::STATE_INITIALIZE, "STATE_INITIALIZE"},
		{Launcher::STATE_NAMES::STATE_IDLE, "STATE_IDLE"},
		{Launcher::STATE_NAMES::STATE_PREPARE_TO_LAUNCH, "STATE_PREPARE_TO_LAUNCH"},
		{Launcher::STATE_NAMES::STATE_LAUNCH, "STATE_LAUNCH"},
		{Launcher::STATE_NAMES::STATE_EMPTY_HOPPER, "STATE_EMPTY_HOPPER"},
		{Launcher::STATE_NAMES::STATE_CLIMB, "STATE_CLIMB"},
		{Launcher::STATE_NAMES::STATE_LAUNCHER_TUNING, "STATE_LAUNCHER_TUNING"},
		{Launcher::STATE_NAMES::STATE_MANUAL_LAUNCH, "STATE_MANUAL_LAUNCH"},
		{Launcher::STATE_NAMES::STATE_AGITATOR, "STATE_AGITATOR"}};

void Launcher::CreateCompBot302()
{
	m_ntName = "Launcher";
	m_launcher = new ctre::phoenix6::hardware::TalonFX(8, ctre::phoenix6::CANBus("canivore"));
	m_hood = new ctre::phoenix6::hardware::TalonFXS(7, ctre::phoenix6::CANBus("canivore"));
	m_transfer = new ctre::phoenix6::hardware::TalonFX(4, ctre::phoenix6::CANBus("canivore"));
	m_indexer = new ctre::phoenix6::hardware::TalonFX(5, ctre::phoenix6::CANBus("canivore"));
	m_spindexer = new ctre::phoenix6::hardware::TalonFX(18, ctre::phoenix6::CANBus("canivore"));
	m_hoodCANdi = new ctre::phoenix6::hardware::CANdi(7, ctre::phoenix6::CANBus("canivore"));
	m_turretCANdi = new ctre::phoenix6::hardware::CANdi(6, ctre::phoenix6::CANBus("canivore"));
	m_turret = m_turretEnabled ? new ctre::phoenix6::hardware::TalonFXS(6, ctre::phoenix6::CANBus("canivore")) : nullptr;
	// m_turretAngleSensor = new ctre::phoenix6::hardware::CANcoder(6, ctre::phoenix6::CANBus("canivore"));

	m_percentOut = new ControlData(
		ControlModes::CONTROL_TYPE::PERCENT_OUTPUT,		  // ControlModes::CONTROL_TYPE mode
		ControlModes::CONTROL_RUN_LOCS::MOTOR_CONTROLLER, // ControlModes::CONTROL_RUN_LOCS server
		"m_percentOut",									  // std::string indentifier
		0,												  // double proportional
		0,												  // double integral
		0,												  // double derivative
		0,												  // double feedforward
		0,												  // double velocityGain
		0,												  // double accelartionGain
		0,												  // double staticFrictionGain,

		ControlData::FEEDFORWARD_TYPE::DUTY_CYCLE,				 // FEEDFORWARD_TYPE feedforwadType
		0,														 // double integralZone
		0,														 // double maxAcceleration
		0,														 // double cruiseVelocity
		0,														 // double peakValue
		0,														 // double nominalValue
		false,													 // bool enableFOC
		ControlData::GravityTypeValue::Elevator_Static,			 // Gravity type
		ControlData::StaticFeedforwardSignValue::UseVelocitySign // Static feedforward sign
	);
	m_velocityLauncher = new ControlData(				  // MECH_TODO: Retune PIDs
		ControlModes::CONTROL_TYPE::VELOCITY_REV_PER_SEC, // ControlModes::CONTROL_TYPE mode
		ControlModes::CONTROL_RUN_LOCS::MOTOR_CONTROLLER, // ControlModes::CONTROL_RUN_LOCS server
		"m_velocityLauncher",							  // std::string indentifier
		0,												  // double proportional
		0,												  // double integral
		0,												  // double derivative
		0,												  // double feedforward
		0,												  // double velocityGain
		0,												  // double accelartionGain
		0,												  // double staticFrictionGain,

		ControlData::FEEDFORWARD_TYPE::DUTY_CYCLE,				 // FEEDFORWARD_TYPE feedforwadType
		0,														 // double integralZone
		0,														 // double maxAcceleration
		0,														 // double cruiseVelocity
		0,														 // double peakValue
		0,														 // double nominalValue
		false,													 // bool enableFOC
		ControlData::GravityTypeValue::Elevator_Static,			 // Gravity type
		ControlData::StaticFeedforwardSignValue::UseVelocitySign // Static feedforward sign
	);
	m_velocityLauncherFullField = new ControlData(		  // MECH_TODO: Retune PIDs
		ControlModes::CONTROL_TYPE::VELOCITY_REV_PER_SEC, // ControlModes::CONTROL_TYPE mode
		ControlModes::CONTROL_RUN_LOCS::MOTOR_CONTROLLER, // ControlModes::CONTROL_RUN_LOCS server
		"m_velocityLauncherFullField",					  // std::string indentifier
		0,												  // double proportional
		0,												  // double integral
		0,												  // double derivative
		0,												  // double feedforward
		0,												  // double velocityGain
		0,												  // double accelartionGain
		0,												  // double staticFrictionGain,

		ControlData::FEEDFORWARD_TYPE::DUTY_CYCLE,				 // FEEDFORWARD_TYPE feedforwadType
		0,														 // double integralZone
		0,														 // double maxAcceleration
		0,														 // double cruiseVelocity
		0,														 // double peakValue
		0,														 // double nominalValue
		false,													 // bool enableFOC
		ControlData::GravityTypeValue::Elevator_Static,			 // Gravity type
		ControlData::StaticFeedforwardSignValue::UseVelocitySign // Static feedforward sign
	);
	m_velocityIndexer = new ControlData(				  // MECH_TODO: Retune PIDs
		ControlModes::CONTROL_TYPE::VELOCITY_REV_PER_SEC, // ControlModes::CONTROL_TYPE mode
		ControlModes::CONTROL_RUN_LOCS::MOTOR_CONTROLLER, // ControlModes::CONTROL_RUN_LOCS server
		"m_velocityIndexer",							  // std::string indentifier
		0,												  // double proportional
		0,												  // double integral
		0,												  // double derivative
		0,												  // double feedforward
		0,												  // double velocityGain
		0,												  // double accelartionGain
		0,												  // double staticFrictionGain,

		ControlData::FEEDFORWARD_TYPE::DUTY_CYCLE,				 // FEEDFORWARD_TYPE feedforwadType
		0,														 // double integralZone
		0,														 // double maxAcceleration
		0,														 // double cruiseVelocity
		0,														 // double peakValue
		0,														 // double nominalValue
		false,													 // bool enableFOC
		ControlData::GravityTypeValue::Elevator_Static,			 // Gravity type
		ControlData::StaticFeedforwardSignValue::UseVelocitySign // Static feedforward sign
	);
	m_velocitySpindexer = new ControlData(				  // MECH_TODO: Retune PIDs
		ControlModes::CONTROL_TYPE::VELOCITY_REV_PER_SEC, // ControlModes::CONTROL_TYPE mode
		ControlModes::CONTROL_RUN_LOCS::MOTOR_CONTROLLER, // ControlModes::CONTROL_RUN_LOCS server
		"m_velocitySpindexer",							  // std::string indentifier
		0,												  // double proportional
		0,												  // double integral
		0,												  // double derivative
		0,												  // double feedforward
		0,												  // double velocityGain
		0,												  // double accelartionGain
		0,												  // double staticFrictionGain,

		ControlData::FEEDFORWARD_TYPE::DUTY_CYCLE,				 // FEEDFORWARD_TYPE feedforwadType
		0,														 // double integralZone
		0,														 // double maxAcceleration
		0,														 // double cruiseVelocity
		0,														 // double peakValue
		0,														 // double nominalValue
		false,													 // bool enableFOC
		ControlData::GravityTypeValue::Elevator_Static,			 // Gravity type
		ControlData::StaticFeedforwardSignValue::UseVelocitySign // Static feedforward sign
	);
	m_velocityTransfer = new ControlData(				  // MECH_TODO: Retune PIDs
		ControlModes::CONTROL_TYPE::VELOCITY_REV_PER_SEC, // ControlModes::CONTROL_TYPE mode
		ControlModes::CONTROL_RUN_LOCS::MOTOR_CONTROLLER, // ControlModes::CONTROL_RUN_LOCS server
		"m_velocityTransfer",							  // std::string indentifier
		0,												  // double proportional
		0,												  // double integral
		0,												  // double derivative
		0,												  // double feedforward
		0,												  // double velocityGain
		0,												  // double accelartionGain
		0,												  // double staticFrictionGain,

		ControlData::FEEDFORWARD_TYPE::DUTY_CYCLE,				 // FEEDFORWARD_TYPE feedforwadType
		0,														 // double integralZone
		0,														 // double maxAcceleration
		0,														 // double cruiseVelocity
		0,														 // double peakValue
		0,														 // double nominalValue
		false,													 // bool enableFOC
		ControlData::GravityTypeValue::Elevator_Static,			 // Gravity type
		ControlData::StaticFeedforwardSignValue::UseVelocitySign // Static feedforward sign
	);
	m_positionDegreesHood = new ControlData(
		ControlModes::CONTROL_TYPE::POSITION_DEGREES,	  // ControlModes::CONTROL_TYPE mode
		ControlModes::CONTROL_RUN_LOCS::MOTOR_CONTROLLER, // ControlModes::CONTROL_RUN_LOCS server
		"m_positionDegreesHood",						  // std::string indentifier
		0,												  // double proportional
		0,												  // double integral
		0,												  // double derivative
		0,												  // double feedforward
		0,												  // double velocityGain
		0,												  // double accelartionGain
		0,												  // double staticFrictionGain,

		ControlData::FEEDFORWARD_TYPE::DUTY_CYCLE,				 // FEEDFORWARD_TYPE feedforwadType
		0,														 // double integralZone
		0,														 // double maxAcceleration
		0,														 // double cruiseVelocity
		0,														 // double peakValue
		0,														 // double nominalValue
		false,													 // bool enableFOC
		ControlData::GravityTypeValue::Elevator_Static,			 // Gravity type
		ControlData::StaticFeedforwardSignValue::UseVelocitySign // Static feedforward sign
	);
	m_positionDegreesTurret = new ControlData(
		ControlModes::CONTROL_TYPE::POSITION_DEGREES,	  // ControlModes::CONTROL_TYPE mode
		ControlModes::CONTROL_RUN_LOCS::MOTOR_CONTROLLER, // ControlModes::CONTROL_RUN_LOCS server
		"m_positionDegreesTurret",						  // std::string indentifier
		0,												  // double proportional
		0,												  // double integral
		0,												  // double derivative
		0,												  // double feedforward
		0,												  // double velocityGain
		0,												  // double accelartionGain
		0,												  // double staticFrictionGain,

		ControlData::FEEDFORWARD_TYPE::DUTY_CYCLE,				 // FEEDFORWARD_TYPE feedforwadType
		0,														 // double integralZone
		0,														 // double maxAcceleration
		0,														 // double cruiseVelocity
		0,														 // double peakValue
		0,														 // double nominalValue
		false,													 // bool enableFOC
		ControlData::GravityTypeValue::Elevator_Static,			 // Gravity type
		ControlData::StaticFeedforwardSignValue::UseVelocitySign // Static feedforward sign
	);
	m_positionDegreesSpindexer = new ControlData(
		ControlModes::CONTROL_TYPE::POSITION_DEGREES,	  // ControlModes::CONTROL_TYPE mode
		ControlModes::CONTROL_RUN_LOCS::MOTOR_CONTROLLER, // ControlModes::CONTROL_RUN_LOCS server
		"m_positionDegreesSpindexer",					  // std::string indentifier
		0,												  // double proportional
		0,												  // double integral
		0,												  // double derivative
		0,												  // double feedforward
		0,												  // double velocityGain
		0,												  // double accelartionGain
		0,												  // double staticFrictionGain,

		ControlData::FEEDFORWARD_TYPE::DUTY_CYCLE,				 // FEEDFORWARD_TYPE feedforwadType
		0,														 // double integralZone
		0,														 // double maxAcceleration
		0,														 // double cruiseVelocity
		0,														 // double peakValue
		0,														 // double nominalValue
		false,													 // bool enableFOC
		ControlData::GravityTypeValue::Elevator_Static,			 // Gravity type
		ControlData::StaticFeedforwardSignValue::UseVelocitySign // Static feedforward sign
	);

	ReadConstants("Launcher.xml", 302);
}

void Launcher::InitializeCompBot302()
{
	InitializeTalonFXLauncherCompBot302();
	InitializeTalonFXSHoodCompBot302();
	InitializeTalonFXTransferCompBot302();
	InitializeTalonFXIndexerCompBot302();
	InitializeTalonFXSpindexerCompBot302();
	if (m_turretEnabled)
		InitializeTalonFXSTurretCompBot302();
}

void Launcher::InitializeTalonFXLauncherCompBot302()
{
	TalonFXConfiguration configs{};
	configs.CurrentLimits.StatorCurrentLimit = wpi::units::current::ampere_t(120);
	configs.CurrentLimits.StatorCurrentLimitEnable = true;
	configs.CurrentLimits.SupplyCurrentLimit = wpi::units::current::ampere_t(70);
	configs.CurrentLimits.SupplyCurrentLimitEnable = true;
	configs.CurrentLimits.SupplyCurrentLowerLimit = wpi::units::current::ampere_t(40);
	configs.CurrentLimits.SupplyCurrentLowerTime = wpi::units::time::second_t(0);

	configs.Voltage.PeakForwardVoltage = wpi::units::voltage::volt_t(16.0);
	configs.Voltage.PeakReverseVoltage = wpi::units::voltage::volt_t(4.5); // -3.5 V
	configs.ClosedLoopRamps.VoltageClosedLoopRampPeriod = wpi::units::time::second_t(0.0);

	configs.HardwareLimitSwitch.ForwardLimitEnable = false;
	configs.HardwareLimitSwitch.ForwardLimitRemoteSensorID = 0;
	configs.HardwareLimitSwitch.ForwardLimitAutosetPositionEnable = false;
	configs.HardwareLimitSwitch.ForwardLimitAutosetPositionValue = wpi::units::angle::degree_t(0);
	configs.HardwareLimitSwitch.ForwardLimitSource = ForwardLimitSourceValue::LimitSwitchPin;
	configs.HardwareLimitSwitch.ForwardLimitType = ForwardLimitTypeValue::NormallyOpen;

	configs.HardwareLimitSwitch.ReverseLimitEnable = false;
	configs.HardwareLimitSwitch.ReverseLimitRemoteSensorID = 0;
	configs.HardwareLimitSwitch.ReverseLimitAutosetPositionEnable = false;
	configs.HardwareLimitSwitch.ReverseLimitAutosetPositionValue = wpi::units::angle::degree_t(0);
	configs.HardwareLimitSwitch.ReverseLimitSource = ReverseLimitSourceValue::LimitSwitchPin;
	configs.HardwareLimitSwitch.ReverseLimitType = ReverseLimitTypeValue::NormallyOpen;

	configs.MotorOutput.Inverted = InvertedValue::CounterClockwise_Positive;
	configs.MotorOutput.NeutralMode = NeutralModeValue::Coast;
	configs.MotorOutput.PeakForwardDutyCycle = 1;
	configs.MotorOutput.PeakReverseDutyCycle = -1;
	configs.MotorOutput.DutyCycleNeutralDeadband = 0;

	configs.Feedback.FeedbackSensorSource = FeedbackSensorSourceValue::RotorSensor;
	configs.Feedback.SensorToMechanismRatio = 1;

	configs.Slot0.kI = m_velocityLauncher->GetI();
	configs.Slot0.kD = m_velocityLauncher->GetD();
	configs.Slot0.kG = m_velocityLauncher->GetF();
	configs.Slot0.kS = m_velocityLauncher->GetS();
	configs.Slot0.kV = m_velocityLauncher->GetV();
	configs.Slot0.kP = m_velocityLauncher->GetP();
	configs.Slot0.kA = m_velocityLauncher->GetA();
	configs.Slot0.GravityType = m_velocityLauncher->GetGravityType();
	configs.Slot0.StaticFeedforwardSign = m_velocityLauncher->GetStaticFeedforwardSign();

	configs.Slot1.kI = m_velocityLauncherFullField->GetI();
	configs.Slot1.kD = m_velocityLauncherFullField->GetD();
	configs.Slot1.kG = m_velocityLauncherFullField->GetF();
	configs.Slot1.kS = m_velocityLauncherFullField->GetS();
	configs.Slot1.kV = m_velocityLauncherFullField->GetV();
	configs.Slot1.kP = m_velocityLauncherFullField->GetP();
	configs.Slot1.kA = m_velocityLauncherFullField->GetA();
	configs.Slot1.GravityType = m_velocityLauncherFullField->GetGravityType();
	configs.Slot1.StaticFeedforwardSign = m_velocityLauncherFullField->GetStaticFeedforwardSign();
	ctre::phoenix::StatusCode status = ctre::phoenix::StatusCode::StatusCodeNotInitialized;
	for (int i = 0; i < 5; ++i)
	{
		status = m_launcher->GetConfigurator().Apply(configs, wpi::units::time::second_t(0.25));
		if (status.IsOK())
			break;
	}
	if (!status.IsOK())
		Logger::GetLogger()->LogData(LOGGER_LEVEL::ERROR, "m_launcher", "m_launcher Status", status.GetName());
}

void Launcher::InitializeTalonFXSHoodCompBot302()
{
	TalonFXSConfiguration configs{};
	configs.CurrentLimits.StatorCurrentLimit = wpi::units::current::ampere_t(100); // MECH_TODO: Go to full speed and find current draw, then set limits accordingly
	configs.CurrentLimits.StatorCurrentLimitEnable = true;
	configs.CurrentLimits.SupplyCurrentLimit = wpi::units::current::ampere_t(70);
	configs.CurrentLimits.SupplyCurrentLimitEnable = true;
	configs.CurrentLimits.SupplyCurrentLowerLimit = wpi::units::current::ampere_t(35);
	configs.CurrentLimits.SupplyCurrentLowerTime = wpi::units::time::second_t(0);

	configs.Voltage.PeakForwardVoltage = wpi::units::voltage::volt_t(11.0);
	configs.Voltage.PeakReverseVoltage = wpi::units::voltage::volt_t(-11.0);
	configs.ClosedLoopRamps.TorqueClosedLoopRampPeriod = wpi::units::time::second_t(0.25);

	configs.HardwareLimitSwitch.ForwardLimitEnable = false;
	configs.HardwareLimitSwitch.ForwardLimitRemoteSensorID = 7;
	configs.HardwareLimitSwitch.ForwardLimitAutosetPositionEnable = false;
	configs.HardwareLimitSwitch.ForwardLimitAutosetPositionValue = wpi::units::angle::degree_t(0);
	configs.HardwareLimitSwitch.ForwardLimitSource = ForwardLimitSourceValue::RemoteCANdiS2;
	configs.HardwareLimitSwitch.ForwardLimitType = ForwardLimitTypeValue::NormallyOpen;

	configs.HardwareLimitSwitch.ReverseLimitEnable = true;
	configs.HardwareLimitSwitch.ReverseLimitRemoteSensorID = 7;
	configs.HardwareLimitSwitch.ReverseLimitAutosetPositionEnable = true; // MECH_TODO: verify this works again with new launcher (may have to turn off again and set in LauncherInitialize)
	configs.HardwareLimitSwitch.ReverseLimitAutosetPositionValue = wpi::units::angle::turn_t(0);
	configs.HardwareLimitSwitch.ReverseLimitSource = ReverseLimitSourceValue::RemoteCANdiS1;
	configs.HardwareLimitSwitch.ReverseLimitType = ReverseLimitTypeValue::NormallyOpen;

	configs.MotorOutput.Inverted = InvertedValue::CounterClockwise_Positive;
	configs.MotorOutput.NeutralMode = NeutralModeValue::Brake;
	configs.MotorOutput.PeakForwardDutyCycle = 1;
	configs.MotorOutput.PeakReverseDutyCycle = -1;
	configs.MotorOutput.DutyCycleNeutralDeadband = 0;

	configs.MotionMagic.MotionMagicCruiseVelocity = wpi::units::angular_velocity::turns_per_second_t(52.5);
	configs.MotionMagic.MotionMagicAcceleration = wpi::units::angular_acceleration::turns_per_second_squared_t(200);
	configs.MotionMagic.MotionMagicJerk = wpi::units::angular_jerk::radians_per_second_cubed_t(0);
	configs.Commutation.MotorArrangement = MotorArrangementValue::Minion_JST;

	configs.ExternalFeedback.ExternalFeedbackSensorSource = FeedbackSensorSourceValue::RotorSensor;
	configs.ExternalFeedback.SensorToMechanismRatio = 2.293864077669903;

	configs.Slot0.kI = m_positionDegreesHood->GetI();
	configs.Slot0.kD = m_positionDegreesHood->GetD();
	configs.Slot0.kG = m_positionDegreesHood->GetF();
	configs.Slot0.kS = m_positionDegreesHood->GetS();
	configs.Slot0.kV = m_positionDegreesHood->GetV();
	configs.Slot0.kP = m_positionDegreesHood->GetP();
	configs.Slot0.kA = m_positionDegreesHood->GetA();
	configs.Slot0.GravityType = m_positionDegreesHood->GetGravityType();
	configs.Slot0.StaticFeedforwardSign = m_positionDegreesHood->GetStaticFeedforwardSign();

	ctre::phoenix::StatusCode statusMotor = ctre::phoenix::StatusCode::StatusCodeNotInitialized;
	for (int i = 0; i < 5; ++i)
	{
		statusMotor = m_hood->GetConfigurator().Apply(configs, wpi::units::time::second_t(0.25));
		if (statusMotor.IsOK())
			break;
	}
	if (!statusMotor.IsOK())
		Logger::GetLogger()->LogData(LOGGER_LEVEL::ERROR, "m_hood", "m_hood Status", statusMotor.GetName());

	CANdiConfiguration CANdiConfig{};

	CANdiConfig.DigitalInputs.S1CloseState = signals::S1CloseStateValue::CloseWhenFloating;
	CANdiConfig.DigitalInputs.S1FloatState = signals::S1FloatStateValue::FloatDetect;

	ctre::phoenix::StatusCode statusCANdi = ctre::phoenix::StatusCode::StatusCodeNotInitialized;
	for (int i = 0; i < 5; ++i)
	{
		statusCANdi = m_hoodCANdi->GetConfigurator().Apply(CANdiConfig, wpi::units::time::second_t(0.25));
		if (statusCANdi.IsOK())
			break;
	}
	if (!statusCANdi.IsOK())
		Logger::GetLogger()->LogData(LOGGER_LEVEL::ERROR, "m_hood", "m_hoodCANdi Status", statusCANdi.GetName());
}

void Launcher::InitializeTalonFXTransferCompBot302()
{
	TalonFXConfiguration configs{};
	configs.CurrentLimits.StatorCurrentLimit = wpi::units::current::ampere_t(100);
	configs.CurrentLimits.StatorCurrentLimitEnable = true;
	configs.CurrentLimits.SupplyCurrentLimit = wpi::units::current::ampere_t(70);
	configs.CurrentLimits.SupplyCurrentLimitEnable = true;
	configs.CurrentLimits.SupplyCurrentLowerLimit = wpi::units::current::ampere_t(35);
	configs.CurrentLimits.SupplyCurrentLowerTime = wpi::units::time::second_t(0);

	configs.Voltage.PeakForwardVoltage = wpi::units::voltage::volt_t(11.0);
	configs.Voltage.PeakReverseVoltage = wpi::units::voltage::volt_t(-11.0);
	configs.ClosedLoopRamps.TorqueClosedLoopRampPeriod = wpi::units::time::second_t(0.25);

	configs.HardwareLimitSwitch.ForwardLimitEnable = false;
	configs.HardwareLimitSwitch.ForwardLimitRemoteSensorID = 0;
	configs.HardwareLimitSwitch.ForwardLimitAutosetPositionEnable = false;
	configs.HardwareLimitSwitch.ForwardLimitAutosetPositionValue = wpi::units::angle::degree_t(0);
	configs.HardwareLimitSwitch.ForwardLimitSource = ForwardLimitSourceValue::LimitSwitchPin;
	configs.HardwareLimitSwitch.ForwardLimitType = ForwardLimitTypeValue::NormallyOpen;

	configs.HardwareLimitSwitch.ReverseLimitEnable = false;
	configs.HardwareLimitSwitch.ReverseLimitRemoteSensorID = 0;
	configs.HardwareLimitSwitch.ReverseLimitAutosetPositionEnable = false;
	configs.HardwareLimitSwitch.ReverseLimitAutosetPositionValue = wpi::units::angle::degree_t(0);
	configs.HardwareLimitSwitch.ReverseLimitSource = ReverseLimitSourceValue::LimitSwitchPin;
	configs.HardwareLimitSwitch.ReverseLimitType = ReverseLimitTypeValue::NormallyOpen;

	configs.MotorOutput.Inverted = InvertedValue::Clockwise_Positive;
	configs.MotorOutput.NeutralMode = NeutralModeValue::Coast;
	configs.MotorOutput.PeakForwardDutyCycle = 1;
	configs.MotorOutput.PeakReverseDutyCycle = -1;
	configs.MotorOutput.DutyCycleNeutralDeadband = 0;

	configs.Feedback.FeedbackSensorSource = FeedbackSensorSourceValue::RotorSensor;
	configs.Feedback.SensorToMechanismRatio = 1;

	configs.Slot0.kI = m_velocityTransfer->GetI();
	configs.Slot0.kD = m_velocityTransfer->GetD();
	configs.Slot0.kG = m_velocityTransfer->GetF();
	configs.Slot0.kS = m_velocityTransfer->GetS();
	configs.Slot0.kV = m_velocityTransfer->GetV();
	configs.Slot0.kP = m_velocityTransfer->GetP();
	configs.Slot0.kA = m_velocityTransfer->GetA();
	configs.Slot0.GravityType = m_velocityTransfer->GetGravityType();
	configs.Slot0.StaticFeedforwardSign = m_velocityTransfer->GetStaticFeedforwardSign();

	ctre::phoenix::StatusCode status = ctre::phoenix::StatusCode::StatusCodeNotInitialized;
	for (int i = 0; i < 5; ++i)
	{
		status = m_transfer->GetConfigurator().Apply(configs, wpi::units::time::second_t(0.25));
		if (status.IsOK())
			break;
	}
	if (!status.IsOK())
		Logger::GetLogger()->LogData(LOGGER_LEVEL::ERROR, "m_transfer", "m_transfer Status", status.GetName());
}

void Launcher::InitializeTalonFXSTurretCompBot302()
{
	TalonFXSConfiguration configs{};
	configs.CurrentLimits.StatorCurrentLimit = wpi::units::current::ampere_t(45);
	configs.CurrentLimits.StatorCurrentLimitEnable = true;
	configs.CurrentLimits.SupplyCurrentLimit = wpi::units::current::ampere_t(70);
	configs.CurrentLimits.SupplyCurrentLimitEnable = true;
	configs.CurrentLimits.SupplyCurrentLowerLimit = wpi::units::current::ampere_t(35);
	configs.CurrentLimits.SupplyCurrentLowerTime = wpi::units::time::second_t(0);

	configs.Voltage.PeakForwardVoltage = wpi::units::voltage::volt_t(11.0);
	configs.Voltage.PeakReverseVoltage = wpi::units::voltage::volt_t(-11.0);
	configs.ClosedLoopRamps.TorqueClosedLoopRampPeriod = wpi::units::time::second_t(0.25);

	configs.HardwareLimitSwitch.ForwardLimitEnable = true;
	configs.HardwareLimitSwitch.ForwardLimitRemoteSensorID = 6;
	configs.HardwareLimitSwitch.ForwardLimitAutosetPositionEnable = false;
	configs.HardwareLimitSwitch.ForwardLimitSource = ForwardLimitSourceValue::RemoteCANdiS2;
	configs.HardwareLimitSwitch.ForwardLimitAutosetPositionValue = wpi::units::angle::turn_t(m_maxTurretAngle);
	configs.HardwareLimitSwitch.ForwardLimitType = ForwardLimitTypeValue::NormallyOpen;

	configs.HardwareLimitSwitch.ReverseLimitEnable = true;
	configs.HardwareLimitSwitch.ReverseLimitRemoteSensorID = 6;
	configs.HardwareLimitSwitch.ReverseLimitAutosetPositionEnable = false;
	configs.HardwareLimitSwitch.ReverseLimitAutosetPositionValue = m_minTurretAngle;
	configs.HardwareLimitSwitch.ReverseLimitSource = ReverseLimitSourceValue::RemoteCANdiS1;
	configs.HardwareLimitSwitch.ReverseLimitType = ReverseLimitTypeValue::NormallyOpen;

	configs.SoftwareLimitSwitch.ForwardSoftLimitEnable = true;
	configs.SoftwareLimitSwitch.ForwardSoftLimitThreshold = m_maxTurretSoftLimit;

	configs.SoftwareLimitSwitch.ReverseSoftLimitEnable = true;
	configs.SoftwareLimitSwitch.ReverseSoftLimitThreshold = m_minTurretSoftLimit;

	configs.MotorOutput.Inverted = InvertedValue::CounterClockwise_Positive;
	configs.MotorOutput.NeutralMode = NeutralModeValue::Brake;
	configs.MotorOutput.PeakForwardDutyCycle = 1;
	configs.MotorOutput.PeakReverseDutyCycle = -1;
	configs.MotorOutput.DutyCycleNeutralDeadband = 0;

	configs.MotionMagic.MotionMagicCruiseVelocity = wpi::units::angular_velocity::turns_per_second_t(1000);
	configs.MotionMagic.MotionMagicAcceleration = wpi::units::angular_acceleration::turns_per_second_squared_t(2000);
	configs.MotionMagic.MotionMagicJerk = wpi::units::angular_jerk::radians_per_second_cubed_t(0);
	configs.Commutation.MotorArrangement = MotorArrangementValue::Minion_JST;

	configs.ExternalFeedback.ExternalFeedbackSensorSource = FeedbackSensorSourceValue::RotorSensor;
	configs.ExternalFeedback.SensorToMechanismRatio = 0.1343032550470101; // 0.16959640223397357413;
	// configs.ExternalFeedback.FeedbackRemoteSensorID = 6;
	// configs.ExternalFeedback.ExternalFeedbackSensorSource = FeedbackSensorSourceValue::RemoteCANcoder;
	// configs.ExternalFeedback.SensorToMechanismRatio = 7.251952;
	// configs.ExternalFeedback.RotorToSensorRatio = 1; // Uncomment and use if fused/sync feedback

	configs.Slot0.kI = m_positionDegreesTurret->GetI();
	configs.Slot0.kD = m_positionDegreesTurret->GetD();
	configs.Slot0.kG = m_positionDegreesTurret->GetF();
	configs.Slot0.kS = m_positionDegreesTurret->GetS();
	configs.Slot0.kV = m_positionDegreesTurret->GetV();
	configs.Slot0.kP = m_positionDegreesTurret->GetP();
	configs.Slot0.kA = m_positionDegreesTurret->GetA();
	configs.Slot0.GravityType = m_positionDegreesTurret->GetGravityType();
	configs.Slot0.StaticFeedforwardSign = m_positionDegreesTurret->GetStaticFeedforwardSign();

	// ctre::phoenix6::configs::CANcoderConfiguration turretAngleSensorConfig{};
	// turretAngleSensorConfig.MagnetSensor.MagnetOffset = 0.1633377777778_tr;
	// turretAngleSensorConfig.MagnetSensor.AbsoluteSensorDiscontinuityPoint = 1_tr;
	// turretAngleSensorConfig.MagnetSensor.SensorDirection = ctre::phoenix6::signals::SensorDirectionValue::Clockwise_Positive;

	// ctre::phoenix::StatusCode statusCANCoder = ctre::phoenix::StatusCode::StatusCodeNotInitialized;
	// for (int i = 0; i < 5; ++i)
	// {
	// 	statusCANCoder = m_turretAngleSensor->GetConfigurator().Apply(turretAngleSensorConfig, wpi::units::time::second_t(0.25));
	// 	if (statusCANCoder.IsOK())
	// 		break;
	// }
	// if (!statusCANCoder.IsOK())
	// 	Logger::GetLogger()->LogData(LOGGER_LEVEL::ERROR, "m_turret", "m_turretCACoder Status", statusCANCoder.GetName());

	ctre::phoenix::StatusCode statusMotor = ctre::phoenix::StatusCode::StatusCodeNotInitialized;
	for (int i = 0; i < 5; ++i)
	{
		statusMotor = m_turret->GetConfigurator().Apply(configs, wpi::units::time::second_t(0.25));
		if (statusMotor.IsOK())
			break;
	}
	if (!statusMotor.IsOK())
		Logger::GetLogger()->LogData(LOGGER_LEVEL::ERROR, "m_turret", "m_turret Status", statusMotor.GetName());

	CANdiConfiguration CANdiConfig{};

	CANdiConfig.DigitalInputs.S1CloseState = signals::S1CloseStateValue::CloseWhenFloating;
	CANdiConfig.DigitalInputs.S1FloatState = signals::S1FloatStateValue::FloatDetect;
	CANdiConfig.DigitalInputs.S2CloseState = signals::S2CloseStateValue::CloseWhenFloating;
	CANdiConfig.DigitalInputs.S2FloatState = signals::S2FloatStateValue::FloatDetect;

	ctre::phoenix::StatusCode statusCANdi = ctre::phoenix::StatusCode::StatusCodeNotInitialized;
	for (int i = 0; i < 5; ++i)
	{
		statusCANdi = m_turretCANdi->GetConfigurator().Apply(CANdiConfig, wpi::units::time::second_t(0.25));
		if (statusCANdi.IsOK())
			break;
	}
	if (!statusCANdi.IsOK())
		Logger::GetLogger()->LogData(LOGGER_LEVEL::ERROR, "m_turret", "m_turretCANdi Status", statusCANdi.GetName());

	m_turret->SetPosition(m_maxTurretAngle);
}

void Launcher::InitializeTalonFXIndexerCompBot302()
{
	TalonFXConfiguration configs{};
	configs.CurrentLimits.StatorCurrentLimit = wpi::units::current::ampere_t(100);
	configs.CurrentLimits.StatorCurrentLimitEnable = true;
	configs.CurrentLimits.SupplyCurrentLimit = wpi::units::current::ampere_t(70);
	configs.CurrentLimits.SupplyCurrentLimitEnable = true;
	configs.CurrentLimits.SupplyCurrentLowerLimit = wpi::units::current::ampere_t(35);
	configs.CurrentLimits.SupplyCurrentLowerTime = wpi::units::time::second_t(0);

	configs.Voltage.PeakForwardVoltage = wpi::units::voltage::volt_t(11.0);
	configs.Voltage.PeakReverseVoltage = wpi::units::voltage::volt_t(-11.0);
	configs.ClosedLoopRamps.TorqueClosedLoopRampPeriod = wpi::units::time::second_t(0.25);

	configs.HardwareLimitSwitch.ForwardLimitEnable = false;
	configs.HardwareLimitSwitch.ForwardLimitRemoteSensorID = 0;
	configs.HardwareLimitSwitch.ForwardLimitAutosetPositionEnable = false;
	configs.HardwareLimitSwitch.ForwardLimitAutosetPositionValue = wpi::units::angle::degree_t(0);
	configs.HardwareLimitSwitch.ForwardLimitSource = ForwardLimitSourceValue::LimitSwitchPin;
	configs.HardwareLimitSwitch.ForwardLimitType = ForwardLimitTypeValue::NormallyOpen;

	configs.HardwareLimitSwitch.ReverseLimitEnable = false;
	configs.HardwareLimitSwitch.ReverseLimitRemoteSensorID = 0;
	configs.HardwareLimitSwitch.ReverseLimitAutosetPositionEnable = false;
	configs.HardwareLimitSwitch.ReverseLimitAutosetPositionValue = wpi::units::angle::degree_t(0);
	configs.HardwareLimitSwitch.ReverseLimitSource = ReverseLimitSourceValue::LimitSwitchPin;
	configs.HardwareLimitSwitch.ReverseLimitType = ReverseLimitTypeValue::NormallyOpen;

	configs.MotorOutput.Inverted = InvertedValue::CounterClockwise_Positive;
	configs.MotorOutput.NeutralMode = NeutralModeValue::Coast;
	configs.MotorOutput.PeakForwardDutyCycle = 1;
	configs.MotorOutput.PeakReverseDutyCycle = -1;
	configs.MotorOutput.DutyCycleNeutralDeadband = 0;

	configs.Feedback.FeedbackSensorSource = FeedbackSensorSourceValue::RotorSensor;
	configs.Feedback.SensorToMechanismRatio = 3;

	configs.Slot0.kI = m_velocityIndexer->GetI();
	configs.Slot0.kD = m_velocityIndexer->GetD();
	configs.Slot0.kG = m_velocityIndexer->GetF();
	configs.Slot0.kS = m_velocityIndexer->GetS();
	configs.Slot0.kV = m_velocityIndexer->GetV();
	configs.Slot0.kP = m_velocityIndexer->GetP();
	configs.Slot0.kA = m_velocityIndexer->GetA();
	configs.Slot0.GravityType = m_velocityIndexer->GetGravityType();
	configs.Slot0.StaticFeedforwardSign = m_velocityIndexer->GetStaticFeedforwardSign();
	ctre::phoenix::StatusCode status = ctre::phoenix::StatusCode::StatusCodeNotInitialized;
	for (int i = 0; i < 5; ++i)
	{
		status = m_indexer->GetConfigurator().Apply(configs, wpi::units::time::second_t(0.25));
		if (status.IsOK())
			break;
	}
	if (!status.IsOK())
		Logger::GetLogger()->LogData(LOGGER_LEVEL::ERROR, "m_indexer", "m_indexer Status", status.GetName());
}

void Launcher::InitializeTalonFXSpindexerCompBot302()
{
	TalonFXConfiguration configs{};
	configs.CurrentLimits.StatorCurrentLimit = wpi::units::current::ampere_t(100);
	configs.CurrentLimits.StatorCurrentLimitEnable = true;
	configs.CurrentLimits.SupplyCurrentLimit = wpi::units::current::ampere_t(70);
	configs.CurrentLimits.SupplyCurrentLimitEnable = true;
	configs.CurrentLimits.SupplyCurrentLowerLimit = wpi::units::current::ampere_t(35);
	configs.CurrentLimits.SupplyCurrentLowerTime = wpi::units::time::second_t(0);

	configs.Voltage.PeakForwardVoltage = wpi::units::voltage::volt_t(11.0);
	configs.Voltage.PeakReverseVoltage = wpi::units::voltage::volt_t(-11.0);
	configs.ClosedLoopRamps.VoltageClosedLoopRampPeriod = wpi::units::time::second_t(0.1);

	configs.HardwareLimitSwitch.ForwardLimitEnable = false;
	configs.HardwareLimitSwitch.ForwardLimitRemoteSensorID = 0;
	configs.HardwareLimitSwitch.ForwardLimitAutosetPositionEnable = false;
	configs.HardwareLimitSwitch.ForwardLimitAutosetPositionValue = wpi::units::angle::degree_t(0);
	configs.HardwareLimitSwitch.ForwardLimitSource = ForwardLimitSourceValue::LimitSwitchPin;
	configs.HardwareLimitSwitch.ForwardLimitType = ForwardLimitTypeValue::NormallyOpen;

	configs.HardwareLimitSwitch.ReverseLimitEnable = false;
	configs.HardwareLimitSwitch.ReverseLimitRemoteSensorID = 0;
	configs.HardwareLimitSwitch.ReverseLimitAutosetPositionEnable = false;
	configs.HardwareLimitSwitch.ReverseLimitAutosetPositionValue = wpi::units::angle::degree_t(0);
	configs.HardwareLimitSwitch.ReverseLimitSource = ReverseLimitSourceValue::LimitSwitchPin;
	configs.HardwareLimitSwitch.ReverseLimitType = ReverseLimitTypeValue::NormallyOpen;

	configs.MotorOutput.Inverted = InvertedValue::Clockwise_Positive;
	configs.MotorOutput.NeutralMode = NeutralModeValue::Coast;
	configs.MotorOutput.PeakForwardDutyCycle = 1;
	configs.MotorOutput.PeakReverseDutyCycle = -1;
	configs.MotorOutput.DutyCycleNeutralDeadband = 0;

	configs.Feedback.FeedbackSensorSource = FeedbackSensorSourceValue::RotorSensor;
	configs.Feedback.SensorToMechanismRatio = 3;

	configs.Slot0.kI = m_positionDegreesSpindexer->GetI();
	configs.Slot0.kD = m_positionDegreesSpindexer->GetD();
	configs.Slot0.kG = m_positionDegreesSpindexer->GetF();
	configs.Slot0.kS = m_positionDegreesSpindexer->GetS();
	configs.Slot0.kV = m_positionDegreesSpindexer->GetV();
	configs.Slot0.kP = m_positionDegreesSpindexer->GetP();
	configs.Slot0.kA = m_positionDegreesSpindexer->GetA();
	configs.Slot0.GravityType = m_positionDegreesSpindexer->GetGravityType();
	configs.Slot0.StaticFeedforwardSign = m_positionDegreesSpindexer->GetStaticFeedforwardSign();

	configs.Slot1.kI = m_velocitySpindexer->GetI();
	configs.Slot1.kD = m_velocitySpindexer->GetD();
	configs.Slot1.kG = m_velocitySpindexer->GetF();
	configs.Slot1.kS = m_velocitySpindexer->GetS();
	configs.Slot1.kV = m_velocitySpindexer->GetV();
	configs.Slot1.kP = m_velocitySpindexer->GetP();
	configs.Slot1.kA = m_velocitySpindexer->GetA();
	configs.Slot1.GravityType = m_velocitySpindexer->GetGravityType();
	configs.Slot1.StaticFeedforwardSign = m_velocitySpindexer->GetStaticFeedforwardSign();

	ctre::phoenix::StatusCode status = ctre::phoenix::StatusCode::StatusCodeNotInitialized;
	for (int i = 0; i < 5; ++i)
	{
		status = m_spindexer->GetConfigurator().Apply(configs, wpi::units::time::second_t(0.25));
		if (status.IsOK())
			break;
	}
	if (!status.IsOK())
		Logger::GetLogger()->LogData(LOGGER_LEVEL::ERROR, "m_spindexer", "m_spindexer Status", status.GetName());

	m_spindexer->SetPosition(0.0_tr);
}

void Launcher::SetCurrentState(int state, bool run)
{
	StateMgr::SetCurrentState(state, run);
}

void Launcher::RefreshCachedMotorData()
{
	m_cachedLauncherVelocity = m_launcher->GetVelocity().GetValue();
	m_cachedHoodPosition = m_hood->GetPosition().GetValue();
	m_cachedTurretPosition = m_turretEnabled ? wpi::units::angle::degree_t(m_turret->GetPosition().GetValueAsDouble()) : 180.0_deg;
	m_cachedLauncherCurrent = m_launcher->GetStatorCurrent().GetValue();

	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, m_ntName, "Launcher Speed", wpi::units::angular_velocity::revolutions_per_minute_t(m_cachedLauncherVelocity).value());
	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, m_ntName, "Hood Position", m_cachedHoodPosition.value());
	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, m_ntName, "turret position", m_cachedTurretPosition.value());
}

void Launcher::RunCommonTasks()
{
	// Refresh all motor data once at the start of the loop to avoid multiple CAN bus queries
	RefreshCachedMotorData();
	UpdateCachedLoggingValues(); // MECH_TODO rename
	if (wpi::RobotBase::IsDisabled())
	{
		InitilaizeLauncher();
		m_targetCalculator->ForceUpdateChassisPose();
	}

	// This function is called once per loop before the current state Run()
	Cyclic();
	SetLauncherProtect();

	// Update Launcher Targets/Field
	if (!m_tuningLauncher)
	{
		m_targetCalculator->UpdateTargetOffset();
	}
	CalculateTargets();
	UpdateLauncherTargets();
	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, m_ntName, "Current State", GetCurrentStateName());
}

/// @brief  Set the control constants (e.g. PIDF values).
/// @param [in] ControlData*                                   pid:  the control constants
/// @return void
void Launcher::SetControlConstants(RobotElementNames::MOTOR_CONTROLLER_USAGE identifier, int slot, ControlData pid)
{
}

/// @brief update the output to the mechanism using the current controller and target value(s)
/// @return void
void Launcher::Update()
{
	m_launcher->SetControl(*m_launcherActiveTarget);
	m_hood->SetControl(*m_hoodActiveTarget);
	m_transfer->SetControl(*m_transferActiveTarget);
	m_indexer->SetControl(*m_indexerActiveTarget);
	m_spindexer->SetControl(*m_spindexerActiveTarget);
	if (m_turretEnabled)
		m_turret->SetControl(*m_turretActiveTarget);
}

void Launcher::Cyclic()
{
	Update();
}

ControlData *Launcher::GetControlData(string name)
{
	if (name.compare("PercentOut") == 0)
		return m_percentOut;
	if (name.compare("VelocityLauncher") == 0)
		return m_velocityLauncher;
	if (name.compare("VelocityLauncherFullField") == 0)
		return m_velocityLauncherFullField;
	if (name.compare("VelocityIndexer") == 0)
		return m_velocityIndexer;
	if (name.compare("VelocitySpindexer") == 0)
		return m_velocitySpindexer;
	if (name.compare("VelocityTransfer") == 0)
		return m_velocityTransfer;
	if (name.compare("PositionDegreesHood") == 0)
		return m_positionDegreesHood;
	if (name.compare("PositionDegreesTurret") == 0)
		return m_positionDegreesTurret;
	if (name.compare("PositionDegreesSpindexer") == 0)
		return m_positionDegreesSpindexer;

	return nullptr;
}

void Launcher::PublishLaunchMode(bool launching)
{
	RobotState::GetInstance()->PublishStateChange(RobotStateChanges::StateChange::IsLaunching_Bool, launching);
}

void Launcher::NotifyStateUpdate(RobotStateChanges::StateChange statechange, bool value)
{
	if (statechange == RobotStateChanges::StateChange::ClimbModeStatus_Bool)
	{
		m_isClimbMode = value;
	}
	else if (statechange == RobotStateChanges::StateChange::AllowedToClimbStatus_Bool)
	{
		m_isAllowedToClimb = value;
	}
	else if (statechange == RobotStateChanges::StateChange::HubActive_Bool)
	{
		m_isHubActive = value;
	}
	else if (statechange == RobotStateChanges::StateChange::StartLaunching_Bool)
	{
		m_startLaunching = value;
	}
	else if (statechange == RobotStateChanges::StateChange::IsIntaking_Bool)
	{
		m_isIntaking = value;
	}
}

bool Launcher::IsLauncherAtTarget()
{
	if (wpi::RobotBase::IsSimulation() && !(GetCurrentState() == STATE_NAMES::STATE_LAUNCHER_TUNING))
	{
		return m_cachedinLaunchzone;
	}
	else
	{
		return (m_cachedHoodError && m_cachedinLaunchzone && m_cachedIsChassisVelocities && m_cachedLauncherSpeedError && m_cachedTurretAtTarget);
	}
}

bool Launcher::IsInLaunchZone() const
{
	if (!m_deadZoneManager->IsInDeadZone())
	{
		return !(m_allianceZoneManager->IsInAllianceZone() && !(m_isHubActive || m_startLaunching));
	}
	return false;
}

void Launcher::CalculateTargets()
{

	if (m_turretEnabled)
	{
		m_targetTurretAngle = m_targetCalculator->GetLauncherTarget(m_cachedTurretPosition);
	}
	else
	{
		m_targetTurretAngle = 180_deg;
		m_chassis->SetTargetChassisRotation(m_targetCalculator->GetChassisTargetForLaunching());
	}
	m_distanceToTarget = m_targetCalculator->GetLauncherDistanceToTarget();
	if (m_allianceZoneManager->IsInAllianceZone())
	{
		m_targetHoodAngle = InterpolateUtils::linearInterpolate(m_scoringDistanceArray, m_scoringHoodAngleArray, m_distanceToTarget);
		m_targetLauncherAngularVelocity = InterpolateUtils::linearInterpolate(m_scoringDistanceArray, m_scoringLauncherVelocityArray, m_distanceToTarget);
	}
	else
	{
		m_targetHoodAngle = InterpolateUtils::linearInterpolate(m_passingDistanceArray, m_passingHoodAngleArray, wpi::units::length::foot_t(m_distanceToTarget));
		m_targetLauncherAngularVelocity = InterpolateUtils::linearInterpolate(m_passingDistanceArray, m_passingLauncherVelocityArray, wpi::units::length::foot_t(m_distanceToTarget));
	}

	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, m_ntName, "Distance", m_distanceToTarget.value());
	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, m_ntName, "Target Hood", m_targetHoodAngle.value());
	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, m_ntName, "Target Launcher Velocity", m_targetLauncherAngularVelocity.value());
	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, m_ntName, "turret Target", m_targetTurretAngle.value());
}

void Launcher::UpdateLauncherTargets()
{
	int currentState = GetCurrentState();

	if (currentState == STATE_NAMES::STATE_OFF || currentState == STATE_NAMES::STATE_INITIALIZE || currentState == STATE_NAMES::STATE_CLIMB || currentState == STATE_NAMES::STATE_MANUAL_LAUNCH || m_tuningLauncher)
	{
		return;
	}

	UpdateTargetHoodPositionDegreesHood(m_targetHoodAngle);

	if (m_turretEnabled)
	{
		UpdateTargetTurretPositionDegreesTurret(m_targetTurretAngle);
	}

	if (currentState == STATE_NAMES::STATE_LAUNCH || currentState == STATE_NAMES::STATE_PREPARE_TO_LAUNCH)
	{
		UpdateTargetLauncherVelocityRPS(m_targetLauncherAngularVelocity);
	}
}

void Launcher::InitilaizeLauncher()
{
	bool turretReverseLimitSwitchTripped = false;
	bool turretForwardLimitSwitchTripped = false;

	if (m_turretEnabled)
	{
		turretReverseLimitSwitchTripped = m_turret->GetReverseLimit().GetValue() == ctre::phoenix6::signals::ReverseLimitValue::ClosedToGround;
		turretForwardLimitSwitchTripped = m_turret->GetForwardLimit().GetValue() == ctre::phoenix6::signals::ForwardLimitValue::ClosedToGround;
		if (turretForwardLimitSwitchTripped)
		{
			m_turret->SetPosition(m_maxTurretAngle);
			m_turretHasReset = true;
		}
		else if (turretReverseLimitSwitchTripped)
		{
			m_turret->SetPosition(m_minTurretAngle);
			m_turretHasReset = true;
		}
	}

	auto hoodReverseLimitSwitchTripped = m_hood->GetReverseLimit().GetValue() == ctre::phoenix6::signals::ReverseLimitValue::ClosedToGround;

	if ((m_turretEnabled && m_turretHasReset && hoodReverseLimitSwitchTripped) ||
		(!m_turretEnabled && hoodReverseLimitSwitchTripped) ||
		wpi::RobotBase::IsSimulation())
	{
		m_launcherInitialized = true;
	}
}
void Launcher::SetLauncherProtect()
{
	if (TeleopControl::GetInstance()->IsButtonPressed(TeleopControlFunctions::LAUNCHER_OFF))
	{
		if (m_launcherOffButtonReleased)
		{
			m_launcherProtectedMode = !m_launcherProtectedMode;
		}
		m_launcherOffButtonReleased = false;
	}
	else
	{
		m_launcherOffButtonReleased = true;
	}
}
/* SystemCore TO DO: Figure out how logging works in SystemCore

void Launcher::DataLog(uint64_t timestamp)
{
	// Control targets
	LogDoubleData(timestamp, m_loggingLauncherTargetPath, m_targetLauncherAngularVelocity.value(), m_loggingRPMUnits);
	LogDoubleData(timestamp, m_loggingHoodTargetPath, m_targetHoodAngle.value(), m_loggingTurnsUnits);
	LogDoubleData(timestamp, m_loggingTurretAngleTargetPath, m_targetTurretAngle.value(), m_loggingTurnsUnits);

	// Mechanism state
	LogStringData(timestamp, m_loggingLauncherStatePath, GetCurrentStateName());
	LogBoolData(timestamp, m_loggingProtectedModePath, m_launcherProtectedMode);

	// Is At Target Conditions
	LogBoolData(timestamp, m_loggingChassisVelocitiesPath, m_cachedIsChassisVelocities);
	LogBoolData(timestamp, m_loggingHoodErrorPath, m_cachedHoodError);
	LogBoolData(timestamp, m_loggingLauncherSpeedErrorPath, m_cachedLauncherSpeedError);
	LogBoolData(timestamp, m_loggingTurretAtTargetPath, m_cachedTurretAtTarget);
	LogBoolData(timestamp, m_loggingLaunchingZonePath, m_cachedinLaunchzone);
}*/
std::string Launcher::GetCurrentStateName()
{
	STATE_NAMES state = static_cast<STATE_NAMES>(GetCurrentState());
	return (STATE_NAMESEnumToStringMap.find(state) == STATE_NAMESEnumToStringMap.end()) ? "Unknown State" : STATE_NAMESEnumToStringMap.at(state);
}

bool Launcher::IsTurretAtTarget()
{
	m_cachedTurretAtTarget = false;
	if (wpi::RobotBase::IsSimulation() && !(GetCurrentState() == STATE_NAMES::STATE_LAUNCHER_TUNING))
	{
		return true;
	}
	if (m_turretEnabled)
	{
		if (m_hasValidTurretAngle)
		{
			wpi::units::angle::degree_t turretError = m_cachedTurretPosition - m_targetTurretAngle;
			m_cachedTurretAtTarget = ((wpi::units::math::abs(turretError) < m_turretAngleThreshold));
		}
	}
	else
	{
		m_cachedTurretAtTarget = true; // m_chassis->IsChassisAtRotationTarget();
	}

	return m_cachedTurretAtTarget;
}
void Launcher::UpdateTurretEnabled()
{
	if (TeleopControl::GetInstance()->IsButtonPressed(TeleopControlFunctions::TURRET_ENABLE) && m_turretEnabledButtonReleased)
	{
		if (m_turretEnabledButtonReleased)
			m_turretEnabled = !m_turretEnabled;
	}
	m_turretEnabledButtonReleased = !TeleopControl::GetInstance()->IsButtonPressed(TeleopControlFunctions::TURRET_ENABLE);
	RobotState::GetInstance()->PublishStateChange(RobotStateChanges::StateChange::TurretEnabled_Bool, m_turretEnabled);
}
bool Launcher::IsFinishedLaunching()
{

	if (m_cachedLauncherCurrent > m_isLaunchingCurrentThreshold)
	{
		m_launchCurrentTimer.Reset();
		m_launchCurrentTimer.Start();
	}
	else if (m_launchCurrentTimer.Get() > m_isLaunchingTimeThreshold)
	{
		return true;
	}

	return false;
}
void Launcher::UpdateCachedLoggingValues()
{
	wpi::units::angle::degree_t hoodError = wpi::units::angle::degree_t(std::abs((m_cachedHoodPosition - m_targetHoodAngle).value()));
	wpi::units::angular_velocity::revolutions_per_minute_t launcherSpeedError = wpi::units::math::abs((m_cachedLauncherVelocity - m_targetLauncherAngularVelocity));
	bool inLaunchzone = IsInLaunchZone();
	auto chassisVelocities = m_chassis != nullptr ? m_chassis->GetState().Velocity : wpi::math::ChassisVelocities();
	auto Speed = wpi::units::math::sqrt(wpi::units::math::abs(chassisVelocities.vx * chassisVelocities.vx) + wpi::units::math::abs(chassisVelocities.vy * chassisVelocities.vy));

	m_hasValidTurretAngle = m_targetCalculator->IsValidTurretAngle();
	m_cachedHoodError = (hoodError < m_hoodAngleThreshold);
	m_cachedLauncherSpeedError = launcherSpeedError < m_launcherVelocityThreshold;
	m_cachedinLaunchzone = (inLaunchzone);
	m_cachedIsChassisVelocities = !AllianceZoneManager::GetInstance()->IsInAllianceZone() ? true : (Speed < m_chassisVelocitiesThreshold);
	bool turretAtTarget = IsTurretAtTarget();
	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, m_ntName, "m_cachedHoodError", m_cachedHoodError);
	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, m_ntName, "m_cachedLauncherSpeedError", m_cachedLauncherSpeedError);
	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, m_ntName, "m_cachedinLaunchzone", m_cachedinLaunchzone);
	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, m_ntName, "m_targetTurretAngle", turretAtTarget);
}
void Launcher::AgitateSpindexer()
{
	auto currentSpindexerPosition = m_spindexer->GetPosition().GetValue();

	UpdateTargetSpindexerPositionTurns(m_minReached ? m_maxSpindexerTarget : m_minSpindexerTarget);

	if (currentSpindexerPosition <= m_minSpindexerTarget)
	{
		m_minReached = true;
	}
	else if (currentSpindexerPosition >= m_maxSpindexerTarget)
	{
		m_minReached = false;
	}
}
void Launcher::InitializeSpindexerTargets()
{
	m_maxSpindexerTarget = m_spindexer->GetPosition().GetValue();
	m_minSpindexerTarget = m_maxSpindexerTarget - m_spindexerTargetAng;
	m_minReached = false;
}
