//====================================================================================================================================================
// Copyright 2026 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
// This file was automatically generated by the Team 302 code generator version 2026.1.0

#pragma once

#include <string>

// FRC Includes
#include <networktables/NetworkTable.h>

#include "RobotIdentifier.h"
#include "auton/AllianceZoneManager.h"
#include "auton/DeadZoneManager.h"
#include "chassis/generated/CommandSwerveDrivetrain.h"
#include "mechanisms/base/BaseMech.h"
#include "mechanisms/base/BaseMechSubsystem.h"
#include "mechanisms/configs/MechanismConfigMgr.h"
#include "mechanisms/configs/RobotElementNames.h"
#include "mechanisms/controllers/ControlData.h"
#include "state/IRobotStateChangeSubscriber.h"
#include "state/RobotStateChanges.h"
#include "utils/RebuiltTargetCalculator.h"

// Hardware Includes
#include "ctre/phoenix6/CANdi.hpp"
#include "ctre/phoenix6/TalonFX.hpp"
#include "ctre/phoenix6/TalonFXS.hpp"
#include "ctre/phoenix6/configs/Configuration.hpp"
#include "utils/logging/signals/DragonDataLogger.h"

// Launcher command classes
#include "mechanisms/launcher/commands/LauncherIdleCommand.h"
#include "mechanisms/launcher/commands/LauncherInitializeCommand.h"
#include "mechanisms/launcher/commands/LauncherLaunchCommand.h"
#include "mechanisms/launcher/commands/LauncherLauncherTuningCommand.h"
#include "mechanisms/launcher/commands/LauncherManualLaunchCommand.h"
#include "mechanisms/launcher/commands/LauncherOffCommand.h"
#include "mechanisms/launcher/commands/LauncherPrepareToLaunchCommand.h"

class Launcher : public BaseMechSubsystem, public IRobotStateChangeSubscriber, public DragonDataLogger
{
public:
    enum STATE_NAMES
    {
        STATE_OFF,
        STATE_INITIALIZE,
        STATE_IDLE,
        STATE_PREPARE_TO_LAUNCH,
        STATE_LAUNCH,
        STATE_LAUNCHER_TUNING,
        STATE_MANUAL_LAUNCH,
    };

    Launcher(RobotIdentifier id);
    Launcher() = delete;
    ~Launcher() = default;

    // Creation Methods per Robot
    void CreateCompBot302();
    void InitializeCompBot302();

    static std::map<std::string, STATE_NAMES> stringToSTATE_NAMESEnumMap;
    static std::map<STATE_NAMES, std::string> STATE_NAMESEnumToStringMap;

    RobotIdentifier getActiveRobotId() { return m_activeRobotId; }

    void Periodic() override;
    void DataLog(uint64_t timestamp) override;

    // Command Getters
    frc2::CommandPtr GetOffCommand() { return LauncherCommands::LauncherOffCommand(this).ToPtr(); }
    frc2::CommandPtr GetInitializeCommand() { return LauncherCommands::LauncherInitializeCommand(this).ToPtr(); }
    frc2::CommandPtr GetIdleCommand() { return LauncherCommands::LauncherIdleCommand(this).ToPtr(); }
    frc2::CommandPtr GetPrepareToLaunchCommand() { return LauncherCommands::LauncherPrepareToLaunchCommand(this).ToPtr(); }
    frc2::CommandPtr GetLaunchCommand() { return LauncherCommands::LauncherLaunchCommand(this).ToPtr(); }
    frc2::CommandPtr GetLauncherTuningCommand() { return LauncherCommands::LauncherLauncherTuningCommand(this).ToPtr(); }
    frc2::CommandPtr GetManualLaunchCommand() { return LauncherCommands::LauncherManualLaunchCommand(this).ToPtr(); }

    /// @brief Map a STATE_NAMES value to the matching command (used by the autonomous bridge).
    frc2::CommandPtr GetCommandForState(STATE_NAMES state)
    {
        switch (state)
        {
        case STATE_INITIALIZE:
            return GetInitializeCommand();
        case STATE_IDLE:
            return GetIdleCommand();
        case STATE_PREPARE_TO_LAUNCH:
            return GetPrepareToLaunchCommand();
        case STATE_LAUNCH:
            return GetLaunchCommand();
        case STATE_LAUNCHER_TUNING:
            return GetLauncherTuningCommand();
        case STATE_MANUAL_LAUNCH:
            return GetManualLaunchCommand();
        case STATE_OFF:
        default:
            return GetOffCommand();
        }
    }

    // Update Target Methods
    void UpdateTargetLauncherPercentOut(double percentOut)
    {
        m_launcherPercentOut.Output = percentOut;
        m_launcherActiveTarget = &m_launcherPercentOut;
    }
    void UpdateTargetHoodPercentOut(double percentOut)
    {
        m_hoodPercentOut.Output = percentOut;
        m_hoodActiveTarget = &m_hoodPercentOut;
    }
    void UpdateTargetTransferPercentOut(double percentOut)
    {
        m_transferPercentOut.Output = percentOut;
        m_transferActiveTarget = &m_transferPercentOut;
    }
    void UpdateTargetIndexerPercentOut(double percentOut)
    {
        m_indexerPercentOut.Output = percentOut;
        m_indexerActiveTarget = &m_indexerPercentOut;
    }
    void UpdateTargetSpindexerPercentOut(double percentOut)
    {
        m_spindexerPercentOut.Output = percentOut;
        m_spindexerActiveTarget = &m_spindexerPercentOut;
    }
    void UpdateTargetTurretPercentOut(double percentOut)
    {
        m_turretPercentOut.Output = percentOut;
        m_turretActiveTarget = &m_turretPercentOut;
    }
    void UpdateTargetSpindexerVelocityLauncher(units::angular_velocity::revolutions_per_minute_t value)
    {
        m_spindexerVelocityLauncher.Velocity = value;
        m_spindexerActiveTarget = &m_spindexerVelocityLauncher.WithSlot(0);
    }
    void UpdateTargetLauncherVelocityLauncher(units::angular_velocity::revolutions_per_minute_t value)
    {
        m_launcherVelocityLauncher.Velocity = value;
        m_launcherActiveTarget = &m_launcherVelocityLauncher.WithSlot(0);
    }
    void UpdateTargetHoodPositionDegreesHood(units::angle::turn_t value)
    {
        m_hoodPositionDegreesHood.Position = value;
        m_hoodActiveTarget = &m_hoodPositionDegreesHood.WithSlot(0);
    }
    void UpdateTargetSpindexerPositionTurnSpindexer(units::angle::turn_t position)
    {
        m_spindexerPositionTurnSpindexer.Position = position;
        m_spindexerActiveTarget = &m_spindexerPositionTurnSpindexer.WithSlot(0);
    }
    void UpdateTargetTurretPositionDegreesTurret(units::angle::turn_t value)
    {
        m_turretPositionDegreesTurret.Position = value;
        m_turretActiveTarget = &m_turretPositionDegreesTurret.WithSlot(0);
    }
    void UpdateTargetTransferVelocityTransfer(units::angular_velocity::revolutions_per_minute_t value)
    {
        m_transferVelocityTransfer.Velocity = value;
        m_transferActiveTarget = &m_transferVelocityTransfer.WithSlot(0);
    }
    void UpdateTargetIndexerVelocityIndexer(units::angular_velocity::revolutions_per_minute_t value)
    {
        m_indexerVelocityIndexer.Velocity = value;
        m_indexerActiveTarget = &m_indexerVelocityIndexer.WithSlot(0);
    }
    void UpdateTargetSpindexerVelocitySpindexer(units::angular_velocity::revolutions_per_minute_t value)
    {
        m_spindexerVelocitySpindexer.Velocity = value;
        m_spindexerActiveTarget = &m_spindexerVelocitySpindexer.WithSlot(0);
    }

    // Hardware Getters
    ctre::phoenix6::hardware::TalonFX *GetLauncherTalonFX() const { return m_launcherMotor; }
    ctre::phoenix6::hardware::TalonFXS *GetHoodTalonFXS() const { return m_hoodMotor; }
    ctre::phoenix6::hardware::TalonFX *GetTransferTalonFX() const { return m_transferMotor; }
    ctre::phoenix6::hardware::TalonFX *GetIndexerTalonFX() const { return m_indexerMotor; }
    ctre::phoenix6::hardware::TalonFX *GetSpindexerTalonFX() const { return m_spindexerMotor; }
    ctre::phoenix6::hardware::CANdi *GetHoodCANdi() const { return m_hoodCANdi; }
    ctre::phoenix6::hardware::CANdi *GetTurretCANdi() const { return m_turretCANdi; }
    ctre::phoenix6::hardware::TalonFXS *GetTurretTalonFXS() const { return m_turretMotor; }

    // ControlData Getters
    ControlData *GetPercentOutControlData() const { return m_percentOut; }
    ControlData *GetVelocityLauncherControlData() const { return m_velocityLauncher; }
    ControlData *GetVelocityLauncherFullFieldControlData() const { return m_velocityLauncherFullField; }
    ControlData *GetVelocityIndexerControlData() const { return m_velocityIndexer; }
    ControlData *GetVelocitySpindexerControlData() const { return m_velocitySpindexer; }
    ControlData *GetVelocityTransferControlData() const { return m_velocityTransfer; }
    ControlData *GetPositionDegreesHoodControlData() const { return m_positionDegreesHood; }
    ControlData *GetPositionDegreesTurretControlData() const { return m_positionDegreesTurret; }
    ControlData *GetPositionTurnSpindexerControlData() const { return m_positionTurnSpindexer; }

    /// @brief Autonomous bridge: schedule the command matching the requested state.
    /// @details Keeps the same signature the old StateMgr exposed so CyclePrimitives and
    ///          the auton XML pipeline continue to work unchanged.
    void SetCurrentState(int state, bool run);

    /// @brief Set the active mode tracker. Used by the Intake command classes in their Initialize().
    void SetCurrentState(int mode) { m_currentState = mode; }

    std::string GetCurrentStateName()
    {
        STATE_NAMES state = static_cast<STATE_NAMES>(GetCurrentState());
        return (STATE_NAMESEnumToStringMap.find(state) == STATE_NAMESEnumToStringMap.end()) ? "Unknown State" : STATE_NAMESEnumToStringMap.at(state);
    }

    int GetCurrentState() const { return m_currentState; }

    // --- Handwritten Public Members ---
    bool IsLauncherInProtectedMode() const { return m_launcherProtectedMode; }
    void PublishLaunchMode(bool launching);
    void NotifyStateUpdate(RobotStateChanges::StateChange statechange, bool value) override;
    bool IsInClimbMode() const { return m_isClimbMode; }
    bool IsAllowedToClimb() const { return m_isAllowedToClimb; }
    bool IsLauncherAtTarget();
    bool IsInLaunchZone() const;
    bool IsLauncherInitialized() const { return m_launcherInitialized; }
    void SetLauncherInitialized(bool initialized) { m_launcherInitialized = initialized; }
    bool IsTuningLauncherMode() const { return m_tuningLauncher; }
    bool IsIntakingMode() const { return m_isIntaking; };
    void UpdateLauncherTargets();
    void InitializeLauncher();
    void SetLauncherProtect();
    bool IsTurretAtTarget();
    units::angle::degree_t GetTargetTurretAngle() const { return m_targetTurretAngle; }
    void UpdateTurretEnabled();
    bool IsFinishedLaunching();
    void UpdateCachedLoggingValues();
    void StartLaunchCurrentTimer() { m_launchCurrentTimer.Start(); }
    void ResetLaunchCurrentTimer()
    {
        m_launchCurrentTimer.Stop();
        m_launchCurrentTimer.Reset();
    }
    void AgitateSpindexer();
    void InitializeSpindexerTargets();
    void TurretHasReset(bool turretHasReset) { m_turretHasReset = turretHasReset; }
    units::length::inch_t GetDistanceToTarget() { return m_distanceToTarget; };

protected:
    RobotIdentifier m_activeRobotId;
    std::string m_ntName;
    ControlData *GetControlData(std::string name) override;

    // --- Handwritten Protected Members ---

private:
    /// @brief update the output to the mechanism using the current controller and target value(s)
    virtual void Update();

    std::unordered_map<std::string, STATE_NAMES> m_stateMap;

    // Command-based mode tracking + autonomous command handle (replaces StateMgr internals)
    int m_currentState = STATE_OFF;
    frc2::CommandPtr m_autonCommand;

    // Hardware Initializtion Methods
    void InitializeTalonFXLauncherCompBot302();
    void InitializeTalonFXSHoodCompBot302();
    void InitializeTalonFXTransferCompBot302();
    void InitializeTalonFXIndexerCompBot302();
    void InitializeTalonFXSpindexerCompBot302();
    void InitializeCANdiHoodCompBot302();
    void InitializeCANdiTurretCompBot302();
    void InitializeTalonFXSTurretCompBot302();

    // Hardware Declarations
    ctre::phoenix6::hardware::TalonFX *m_launcherMotor = nullptr;
    ctre::phoenix6::hardware::TalonFXS *m_hoodMotor = nullptr;
    ctre::phoenix6::hardware::TalonFX *m_transferMotor = nullptr;
    ctre::phoenix6::hardware::TalonFX *m_indexerMotor = nullptr;
    ctre::phoenix6::hardware::TalonFX *m_spindexerMotor = nullptr;
    ctre::phoenix6::hardware::CANdi *m_hoodCANdi = nullptr;
    ctre::phoenix6::hardware::CANdi *m_turretCANdi = nullptr;
    ctre::phoenix6::hardware::TalonFXS *m_turretMotor = nullptr;

    // Control Data Declarations
    ControlData *m_percentOut = nullptr;
    ControlData *m_velocityLauncher = nullptr;
    ControlData *m_velocityLauncherFullField = nullptr;
    ControlData *m_velocityIndexer = nullptr;
    ControlData *m_velocitySpindexer = nullptr;
    ControlData *m_velocityTransfer = nullptr;
    ControlData *m_positionDegreesHood = nullptr;
    ControlData *m_positionDegreesTurret = nullptr;
    ControlData *m_positionTurnSpindexer = nullptr;

    // Control requested
    ctre::phoenix6::controls::DutyCycleOut m_launcherPercentOut{0.0};
    ctre::phoenix6::controls::DutyCycleOut m_hoodPercentOut{0.0};
    ctre::phoenix6::controls::DutyCycleOut m_transferPercentOut{0.0};
    ctre::phoenix6::controls::DutyCycleOut m_indexerPercentOut{0.0};
    ctre::phoenix6::controls::DutyCycleOut m_spindexerPercentOut{0.0};
    ctre::phoenix6::controls::DutyCycleOut m_turretPercentOut{0.0};
    ctre::phoenix6::controls::VelocityVoltage m_spindexerVelocityLauncher{0.0_rpm};
    ctre::phoenix6::controls::VelocityVoltage m_launcherVelocityLauncher{0.0_rpm};
    ctre::phoenix6::controls::MotionMagicVoltage m_hoodPositionDegreesHood{0.0_tr};
    ctre::phoenix6::controls::PositionVoltage m_spindexerPositionTurnSpindexer{0.0_tr};
    ctre::phoenix6::controls::MotionMagicVoltage m_turretPositionDegreesTurret{0.0_tr};
    ctre::phoenix6::controls::VelocityVoltage m_transferVelocityTransfer{0.0_rpm};
    ctre::phoenix6::controls::VelocityVoltage m_indexerVelocityIndexer{0.0_rpm};
    ctre::phoenix6::controls::VelocityVoltage m_spindexerVelocitySpindexer{0.0_rpm};
    ctre::phoenix6::controls::ControlRequest *m_launcherActiveTarget = &m_launcherPercentOut;
    ctre::phoenix6::controls::ControlRequest *m_hoodActiveTarget = &m_hoodPercentOut;
    ctre::phoenix6::controls::ControlRequest *m_transferActiveTarget = &m_transferPercentOut;
    ctre::phoenix6::controls::ControlRequest *m_indexerActiveTarget = &m_indexerPercentOut;
    ctre::phoenix6::controls::ControlRequest *m_spindexerActiveTarget = &m_spindexerPercentOut;
    ctre::phoenix6::controls::ControlRequest *m_turretActiveTarget = &m_turretPercentOut;

    // Cached Sensor Values
    units::angular_velocity::revolutions_per_minute_t m_cachedLauncherVelocityLauncher = units::angular_velocity::revolutions_per_minute_t(0.0);
    units::angle::turn_t m_cachedHoodPositionDegreesHood = units::angle::turn_t(0.0);
    units::angular_velocity::revolutions_per_minute_t m_cachedTransferVelocityTransfer = units::angular_velocity::revolutions_per_minute_t(0.0);
    units::angular_velocity::revolutions_per_minute_t m_cachedIndexerVelocityIndexer = units::angular_velocity::revolutions_per_minute_t(0.0);
    units::angular_velocity::revolutions_per_minute_t m_cachedSpindexerVelocityLauncher = units::angular_velocity::revolutions_per_minute_t(0.0);
    units::angle::turn_t m_cachedTurretPositionDegreesTurret = units::angle::turn_t(0.0);

    void RefreshCachedData();

    // Logging Paths
    static constexpr std::string_view m_launcherStatePath = "/Launcher/State";
    static constexpr std::string_view m_loggingLauncherTargetPath = "/Launcher/LauncherMotorTarget";
    static constexpr std::string_view m_loggingLauncherVelocityPath = "/Launcher/LauncherVelocity";
    static constexpr std::string_view m_loggingLauncherControlRequest = "/Launcher/LauncherControlRequest";
    static constexpr std::string_view m_loggingHoodTargetPath = "/Launcher/HoodMotorTarget";
    static constexpr std::string_view m_loggingHoodPositionPath = "/Launcher/HoodPosition";
    static constexpr std::string_view m_loggingHoodControlRequest = "/Launcher/HoodControlRequest";
    static constexpr std::string_view m_loggingTransferTargetPath = "/Launcher/TransferMotorTarget";
    static constexpr std::string_view m_loggingTransferVelocityPath = "/Launcher/TransferVelocity";
    static constexpr std::string_view m_loggingTransferControlRequest = "/Launcher/TransferControlRequest";
    static constexpr std::string_view m_loggingIndexerTargetPath = "/Launcher/IndexerMotorTarget";
    static constexpr std::string_view m_loggingIndexerVelocityPath = "/Launcher/IndexerVelocity";
    static constexpr std::string_view m_loggingIndexerControlRequest = "/Launcher/IndexerControlRequest";
    static constexpr std::string_view m_loggingSpindexerTargetPath = "/Launcher/SpindexerMotorTarget";
    static constexpr std::string_view m_loggingSpindexerVelocityPath = "/Launcher/SpindexerVelocity";
    static constexpr std::string_view m_loggingSpindexerControlRequest = "/Launcher/SpindexerControlRequest";
    static constexpr std::string_view m_loggingTurretTargetPath = "/Launcher/TurretMotorTarget";
    static constexpr std::string_view m_loggingTurretPositionPath = "/Launcher/TurretPosition";
    static constexpr std::string_view m_loggingTurretControlRequest = "/Launcher/TurretControlRequest";

    // --- Handwritten Private Members ---
    bool m_launcherProtectedMode = false;
    bool m_launcherOffButtonReleased = true;
    bool m_isClimbMode = false;
    bool m_isAllowedToClimb = false;
    bool m_isHubActive = false;
    bool m_startLaunching = false;
    bool m_isIntaking = false;

    units::angle::degree_t m_targetTurretAngle = 90.0_deg;
    units::angular_velocity::revolutions_per_minute_t m_targetLauncherAngularVelocity = 0.0_rpm;
    units::angle::turn_t m_targetHoodAngle = 0.0_tr;
    units::angle::turn_t m_minHoodAngle = 0.0_tr;
    units::angle::turn_t m_maxHoodAngle = 30.0_tr;
    units::angle::turn_t m_minTurretAngle = 90_tr;
    units::angle::turn_t m_maxTurretAngle = 268_tr;
    units::angle::degree_t m_turretAngleThreshold = 5.0_deg;
    units::angular_velocity::revolutions_per_minute_t m_launcherVelocityThreshold = 150.0_rpm;
    units::angle::turn_t m_hoodAngleThreshold = 0.5_tr;
    units::velocity::meters_per_second_t m_chassisSpeedThreshold = 3.0_mps;
    units::angle::turn_t m_minTurretSoftLimit{93};
    units::angle::turn_t m_maxTurretSoftLimit{265};

    RebuiltTargetCalculator *m_targetCalculator;
    subsystems::CommandSwerveDrivetrain *m_chassis;

    void CalculateTargets();
    void RefreshCachedMotorData();

    bool m_launcherInitialized = false;
    bool m_tuningLauncher = false;

    // All values in turns are actually Degree's
    // MECH_TODO: Need to verify values after 116 inches, may need to add more points on both sides
    static constexpr std::array<units::length::inch_t, 11> m_scoringDistanceArray = {50.0_in, 80.0_in, 110.0_in, 130.0_in, 140_in, 150_in, 170.0_in, 200.0_in, 230.0_in, 260.0_in, 290.0_in};
    static constexpr std::array<units::angle::turn_t, 11> m_scoringHoodAngleArray = {0.0_tr, 8.0_tr, 15.2_tr, 18_tr, 19_tr, 20_tr, 21.8_tr, 24.4_tr, 25.5_tr, 30.0_tr, 30.0_tr};
    static constexpr std::array<units::angular_velocity::revolutions_per_minute_t, 11> m_scoringLauncherVelocityArray = {2000.0_rpm, 2050.0_rpm, 2150.0_rpm, 2350.0_rpm, 2375_rpm, 2475_rpm, 2600.0_rpm, 2850.0_rpm, 3200.0_rpm, 3525.0_rpm, 3950.0_rpm};

    static constexpr std::array<units::length::foot_t, 8> m_passingDistanceArray = {10.0_ft, 16.66666667_ft, 20.0_ft, 23.08333333_ft, 26.33333333_ft, 30.0_ft, 35.0_ft, 42.33333333_ft};
    static constexpr std::array<units::angle::turn_t, 8> m_passingHoodAngleArray = {23.5_tr, 23.5_tr, 23.5_tr, 29.7_tr, 30.0_tr, 30.0_tr, 30.0_tr, 30.0_tr};
    static constexpr std::array<units::angular_velocity::revolutions_per_minute_t, 8> m_passingLauncherVelocityArray = {1900.0_rpm, 2150.0_rpm, 2450.0_rpm, 2500.0_rpm, 3000.0_rpm, 3600.0_rpm, 4300.0_rpm, 5500.0_rpm};
    // All values in turns are actually Degree's

    // Cached motor status signals for performance optimization
    // These are refreshed once per loop in RunCommonTasks() to avoid multiple CAN bus queries
    units::angular_velocity::turns_per_second_t m_cachedLauncherVelocity = 0.0_tps;
    units::angle::turn_t m_cachedHoodPosition = 0.0_tr;
    units::angle::degree_t m_cachedTurretPosition = 0.0_deg;
    units::current::ampere_t m_cachedLauncherCurrent = 0.0_A;

    units::angle::turn_t m_passingHoodTargetAngle = 25.0_tr;
    units::angular_velocity::revolutions_per_minute_t m_passingLauncherTargetVelocity = 2500.0_rpm;

    bool m_turretEnabled = true;
    bool m_turretEnabledButtonReleased = true;

    units::current::ampere_t m_isLaunchingCurrentThreshold = 21.0_A;
    frc::Timer m_launchCurrentTimer;
    units::time::second_t m_isLaunchingTimeThreshold = 1.0_s;
    bool m_hasValidTurretAngle = false;
    bool m_cachedHoodError = false;
    bool m_cachedLauncherSpeedError = false;
    bool m_cachedinLaunchzone = false;
    bool m_cachedIsChassisSpeed = false;
    bool m_cachedTurretAtTarget = false;
    bool m_turretHasReset = false;
    AllianceZoneManager *m_allianceZoneManager;
    DeadZoneManager *m_deadZoneManager;

    // Agitate Spindexer
    units::angle::degree_t m_minSpindexerTarget;
    units::angle::degree_t m_maxSpindexerTarget;
    bool m_minReached;
    static constexpr units::angle::degree_t m_spindexerTargetAng{30};
    units::length::inch_t m_distanceToTarget{0.0};
};