//====================================================================================================================================================
// Copyright 2026 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
// This file was automatically generated by the Team 302 code generator version 20.26.00.00
// Generated on Thursday, January 22, 2026 11:43:04 PM

#pragma once

#include <array>
#include <memory>
#include <string>

// FRC Includes
#include "ctre/phoenix6/CANdi.hpp"
#include "ctre/phoenix6/TalonFX.hpp"
#include "ctre/phoenix6/TalonFXS.hpp"
#include "ctre/phoenix6/configs/Configuration.hpp"
#include "ctre/phoenix6/controls/Follower.hpp"

#include "mechanisms/base/BaseMech.h"
#include "mechanisms/controllers/ControlData.h"
#include "state/IRobotStateChangeSubscriber.h"
#include "state/RobotStateChanges.h"
#include "state/StateMgr.h"

#include "RobotIdentifier.h"
#include "chassis/generated/CommandSwerveDrivetrain.h"
#include "mechanisms/configs/MechanismConfigMgr.h"
#include "mechanisms/configs/RobotElementNames.h"
#include "wpi/units/angle.hpp"
#include "wpi/units/length.hpp"
#include "wpi/units/velocity.hpp"

// #include "utils/logging/signals/DragonDataLogger.h"//  SystemCore TO DO: Figure out how logging works in SystemCore

// Includes after generation
#include "auton/AllianceZoneManager.h"
#include "auton/DeadZoneManager.h"
#include "utils/RebuiltTargetCalculator.h"
class Launcher : public BaseMech, public StateMgr, public IRobotStateChangeSubscriber //, public DragonDataLogger
{
public:
	enum STATE_NAMES
	{
		STATE_OFF,
		STATE_INITIALIZE,
		STATE_IDLE,
		STATE_PREPARE_TO_LAUNCH,
		STATE_LAUNCH,
		STATE_EMPTY_HOPPER,
		STATE_CLIMB,
		STATE_LAUNCHER_TUNING,
		STATE_MANUAL_LAUNCH,
		STATE_AGITATOR
	};

	Launcher(RobotIdentifier activeRobotId);
	Launcher() = delete;
	~Launcher() = default;

	void CreateCompBot302();
	void InitializeCompBot302();

	/// @brief Set the control constants (e.g. PIDF values).
	/// @param indentifier the motor controller usage to identify the motor
	/// @param slot position on the motor controller to set
	/// @param pid control data / constants
	virtual void SetControlConstants(RobotElementNames::MOTOR_CONTROLLER_USAGE indentifier, int slot, ControlData pid);

	/// @brief update the output to the mechanism using the current controller and target value(s)
	virtual void Update();

	void UpdateTargetLauncherPercentOut(double percentOut)
	{
		m_launcherPercentOut.Output = percentOut;
		m_launcherActiveTarget = &m_launcherPercentOut;
	}
	void UpdateTargetHoodPercentOut(double percentOut)
	{
		m_hoodPercentOut.Output = percentOut;
		m_hoodActiveTarget = &m_hoodPercentOut;
	}
	void UpdateTargetTransferPercentOut(double percentOut)
	{
		m_transferPercentOut.Output = percentOut;
		m_transferActiveTarget = &m_transferPercentOut;
	}
	void UpdateTargetTurretPercentOut(double percentOut)
	{
		m_turretPercentOut.Output = percentOut;
		m_turretActiveTarget = &m_turretPercentOut;
	}
	void UpdateTargetIndexerPercentOut(double percentOut)
	{
		m_indexerPercentOut.Output = percentOut;
		m_indexerActiveTarget = &m_indexerPercentOut;
	}
	void UpdateTargetHoodPositionDegreesHood(wpi::units::angle::turn_t position)
	{
		position = std::clamp(position, m_minHoodAngle, m_maxHoodAngle);
		m_hoodPositionDegreesHood.Position = position;
		m_hoodActiveTarget = &m_hoodPositionDegreesHood.WithSlot(0);
	}
	void UpdateTargetTurretPositionDegreesTurret(wpi::units::angle::degree_t position)
	{
		wpi::units::angle::turn_t positionTurn = wpi::units::angle::turn_t(position.value()); // Turns = Degrees from sensor to mech ratio, but physical units are degrees, but motor controller is in turns, so convert to turns for clamping and motor controller output, but keep target in degrees for target calculator and logging
		positionTurn = std::clamp(positionTurn, m_minTurretAngle, m_maxTurretAngle);
		m_turretPositionDegreesTurret.Position = positionTurn;
		m_turretActiveTarget = &m_turretPositionDegreesTurret.WithSlot(0);
	}
	void UpdateTargetLauncherVelocityRPS(wpi::units::angular_velocity::turns_per_second_t velocity)
	{
		m_launcherVelocityRPS.Velocity = velocity;
		m_launcherVelocityRPS.Acceleration = 100_tr_per_s_sq;
		// m_launcherActiveTarget = &m_launcherVelocityRPS.WithSlot(0);
		m_launcherActiveTarget = (m_distanceToTarget > 35_ft) ? &m_launcherVelocityRPS.WithSlot(1)
															  : &m_launcherVelocityRPS.WithSlot(0);
	}

	void UpdateTargetSpindexerPercentOut(double percentOut)
	{
		m_spindexerPercentOut.Output = percentOut;
		m_spindexerActiveTarget = &m_spindexerPercentOut;
	}
	void UpdateTargetSpindexerPositionTurns(wpi::units::angle::turn_t position)
	{
		m_spindexerPositionTurns.Position = position;
		m_spindexerActiveTarget = &m_spindexerPositionTurns.WithSlot(0);
	}
	void UpdateTargetTransferVelocityRPS(wpi::units::angular_velocity::turns_per_second_t velocity)
	{
		m_transferVelocityRPS.Velocity = velocity;
		m_transferActiveTarget = &m_transferVelocityRPS.WithSlot(0);
	}
	void UpdateTargetIndexerVelocityRPS(wpi::units::angular_velocity::turns_per_second_t velocity)
	{
		m_indexerVelocityRPS.Velocity = velocity;
		m_indexerActiveTarget = &m_indexerVelocityRPS.WithSlot(0);
	}
	void UpdateTargetSpindexerVelocityRPS(wpi::units::angular_velocity::turns_per_second_t velocity)
	{
		m_spindexerVelocityRPS.Velocity = velocity;
		m_spindexerActiveTarget = &m_spindexerVelocityRPS.WithSlot(1);
	}

	void CreateAndRegisterStates();
	void Cyclic();
	void RunCommonTasks() override;
	// void DataLog(uint64_t timestamp) override; // SystemCore TO DO: Figure out how logging works in SystemCore

	RobotIdentifier getActiveRobotId() { return m_activeRobotId; }

	ctre::phoenix6::hardware::TalonFX *GetLauncher() const { return m_launcher; }
	ctre::phoenix6::hardware::TalonFXS *GetHood() const { return m_hood; }
	ctre::phoenix6::hardware::TalonFX *GetTransfer() const { return m_transfer; }
	ctre::phoenix6::hardware::TalonFXS *GetTurret() const { return m_turret; }
	ctre::phoenix6::hardware::TalonFX *GetIndexer() const { return m_indexer; }
	ctre::phoenix6::hardware::TalonFX *GetSpindexer() const { return m_spindexer; }
	ctre::phoenix6::hardware::CANdi *GetHoodCANdi() const { return m_hoodCANdi; }
	ctre::phoenix6::hardware::CANdi *GetTurretCANdi() const { return m_turretCANdi; }

	ControlData *GetPercentOut() const { return m_percentOut; }
	ControlData *GetVelocityLauncher() const { return m_velocityLauncher; }
	ControlData *GetVelocityLauncherFullField() const { return m_velocityLauncherFullField; }
	ControlData *GetVelocityIndexer() const { return m_velocityIndexer; }
	ControlData *GetVelocitySpindexer() const { return m_velocitySpindexer; }
	ControlData *GetVelocityTransfer() const { return m_velocityTransfer; }
	ControlData *GetPositionDegreesHood() const { return m_positionDegreesHood; }
	ControlData *GetPositionDegreesTurret() const { return m_positionDegreesTurret; }

	static std::map<std::string, STATE_NAMES> stringToSTATE_NAMESEnumMap;
	static std::map<STATE_NAMES, std::string> STATE_NAMESEnumToStringMap;

	void SetCurrentState(int state, bool run) override;
	std::string GetCurrentStateName();
	bool IsLauncherInProtectedMode() const { return m_launcherProtectedMode; }
	void PublishLaunchMode(bool launching);
	void NotifyStateUpdate(RobotStateChanges::StateChange statechange, bool value) override;
	bool IsInClimbMode() const { return m_isClimbMode; }
	bool IsAllowedToClimb() const { return m_isAllowedToClimb; }
	bool IsLauncherAtTarget();
	bool IsInLaunchZone() const;
	bool IsLauncherInitialized() const { return m_launcherInitialized; }
	void SetLauncherInitialized(bool initialized) { m_launcherInitialized = initialized; }
	bool IsTuningLauncherMode() const { return m_tuningLauncher; }
	bool IsIntakingMode() const { return m_isIntaking; };
	void UpdateLauncherTargets();
	void InitilaizeLauncher();
	void SetLauncherProtect();
	bool IsTurretAtTarget();
	wpi::units::angle::degree_t GetTargetTurretAngle() const { return m_targetTurretAngle; }
	void UpdateTurretEnabled();
	bool IsFinishedLaunching();
	void UpdateCachedLoggingValues();
	void StartLaunchCurrentTimer() { m_launchCurrentTimer.Start(); }
	void ResetLaunchCurrentTimer()
	{
		m_launchCurrentTimer.Stop();
		m_launchCurrentTimer.Reset();
	}
	void AgitateSpindexer();
	void InitializeSpindexerTargets();
	void TurretHasReset(bool turretHasReset) { m_turretHasReset = turretHasReset; }
	wpi::units::length::inch_t GetDistanceToTarget() { return m_distanceToTarget; };

protected:
	RobotIdentifier m_activeRobotId;
	std::string m_ntName;

	ControlData *GetControlData(std::string name) override;

private:
	std::unordered_map<std::string, STATE_NAMES> m_stateMap;

	ctre::phoenix6::hardware::TalonFX *m_launcher;
	ctre::phoenix6::hardware::TalonFXS *m_hood;
	ctre::phoenix6::hardware::TalonFX *m_transfer;
	ctre::phoenix6::hardware::TalonFXS *m_turret;
	ctre::phoenix6::hardware::TalonFX *m_indexer;
	ctre::phoenix6::hardware::TalonFX *m_spindexer;
	ctre::phoenix6::hardware::CANdi *m_hoodCANdi;
	ctre::phoenix6::hardware::CANdi *m_turretCANdi;
	// ctre::phoenix6::hardware::CANcoder *m_turretAngleSensor;

	ControlData *m_percentOut;
	ControlData *m_velocityLauncher;
	ControlData *m_velocityLauncherFullField;
	ControlData *m_velocityIndexer;
	ControlData *m_velocitySpindexer;
	ControlData *m_velocityTransfer;
	ControlData *m_positionDegreesHood;
	ControlData *m_positionDegreesTurret;
	ControlData *m_positionDegreesSpindexer;

	void InitializeTalonFXLauncherCompBot302();
	void InitializeTalonFXSHoodCompBot302();
	void InitializeTalonFXTransferCompBot302();
	void InitializeTalonFXSTurretCompBot302();
	void InitializeTalonFXIndexerCompBot302();
	void InitializeTalonFXSpindexerCompBot302();

	ctre::phoenix6::controls::DutyCycleOut m_launcherPercentOut{0.0};
	ctre::phoenix6::controls::DutyCycleOut m_hoodPercentOut{0.0};
	ctre::phoenix6::controls::DutyCycleOut m_transferPercentOut{0.0};
	ctre::phoenix6::controls::DutyCycleOut m_turretPercentOut{0.0};
	ctre::phoenix6::controls::DutyCycleOut m_indexerPercentOut{0.0};
	ctre::phoenix6::controls::DutyCycleOut m_spindexerPercentOut{0.0};
	ctre::phoenix6::controls::PositionVoltage m_spindexerPositionTurns{wpi::units::angle::turn_t(0.0)};
	ctre::phoenix6::controls::MotionMagicVoltage m_hoodPositionDegreesHood{wpi::units::angle::degree_t(0.0)};
	ctre::phoenix6::controls::MotionMagicVoltage m_turretPositionDegreesTurret{wpi::units::angle::degree_t(0.0)};
	ctre::phoenix6::controls::VelocityVoltage m_launcherVelocityRPS{wpi::units::angular_velocity::turns_per_second_t(0.0)};
	ctre::phoenix6::controls::VelocityVoltage m_transferVelocityRPS{wpi::units::angular_velocity::turns_per_second_t(0.0)};
	ctre::phoenix6::controls::VelocityVoltage m_indexerVelocityRPS{wpi::units::angular_velocity::turns_per_second_t(0.0)};
	ctre::phoenix6::controls::VelocityVoltage m_spindexerVelocityRPS{wpi::units::angular_velocity::turns_per_second_t(0.0)};
	ctre::phoenix6::controls::ControlRequest *m_launcherActiveTarget;
	ctre::phoenix6::controls::ControlRequest *m_hoodActiveTarget;
	ctre::phoenix6::controls::ControlRequest *m_transferActiveTarget;
	ctre::phoenix6::controls::ControlRequest *m_turretActiveTarget;
	ctre::phoenix6::controls::ControlRequest *m_indexerActiveTarget;
	ctre::phoenix6::controls::ControlRequest *m_spindexerActiveTarget;

	bool m_launcherProtectedMode = false;
	bool m_launcherOffButtonReleased = true;
	bool m_isClimbMode = false;
	bool m_isAllowedToClimb = false;
	bool m_isHubActive = false;
	bool m_startLaunching = false;
	bool m_isIntaking = false;

	wpi::units::angle::degree_t m_targetTurretAngle = 90.0_deg;
	wpi::units::angular_velocity::revolutions_per_minute_t m_targetLauncherAngularVelocity = 0.0_rpm;
	wpi::units::angle::turn_t m_targetHoodAngle = 0.0_tr;
	wpi::units::angle::turn_t m_minHoodAngle = 0.0_tr;
	wpi::units::angle::turn_t m_maxHoodAngle = 30.0_tr;
	wpi::units::angle::turn_t m_minTurretAngle = 90_tr;
	wpi::units::angle::turn_t m_maxTurretAngle = 268_tr;
	wpi::units::angle::degree_t m_turretAngleThreshold = 5.0_deg;
	wpi::units::angular_velocity::revolutions_per_minute_t m_launcherVelocityThreshold = 150.0_rpm;
	wpi::units::angle::turn_t m_hoodAngleThreshold = 0.5_tr;
	wpi::units::velocity::meters_per_second_t m_chassisVelocitiesThreshold = 3.0_mps;
	wpi::units::angle::turn_t m_minTurretSoftLimit{93};
	wpi::units::angle::turn_t m_maxTurretSoftLimit{265};

	RebuiltTargetCalculator *m_targetCalculator;
	subsystems::CommandSwerveDrivetrain *m_chassis;

	void CalculateTargets();
	void RefreshCachedMotorData();

	bool m_launcherInitialized = false;
	bool m_tuningLauncher = false;

	// All values in turns are actually Degree's
	// MECH_TODO: Need to verify values after 116 inches, may need to add more points on both sides
	inline static const std::array<wpi::units::length::inch_t, 11> m_scoringDistanceArray = {50.0_in, 80.0_in, 110.0_in, 130.0_in, 140_in, 150_in, 170.0_in, 200.0_in, 230.0_in, 260.0_in, 290.0_in};
	inline static const std::array<wpi::units::angle::turn_t, 11> m_scoringHoodAngleArray = {0.0_tr, 8.0_tr, 15.2_tr, 18_tr, 19_tr, 20_tr, 21.8_tr, 24.4_tr, 25.5_tr, 30.0_tr, 30.0_tr};
	inline static const std::array<wpi::units::angular_velocity::revolutions_per_minute_t, 11> m_scoringLauncherVelocityArray = {2000.0_rpm, 2050.0_rpm, 2150.0_rpm, 2350.0_rpm, 2375_rpm, 2475_rpm, 2600.0_rpm, 2850.0_rpm, 3200.0_rpm, 3525.0_rpm, 3950.0_rpm};

	inline static const std::array<wpi::units::length::foot_t, 8> m_passingDistanceArray = {10.0_ft, 16.66666667_ft, 20.0_ft, 23.08333333_ft, 26.33333333_ft, 30.0_ft, 35.0_ft, 42.33333333_ft};
	inline static const std::array<wpi::units::angle::turn_t, 8> m_passingHoodAngleArray = {23.5_tr, 23.5_tr, 23.5_tr, 29.7_tr, 30.0_tr, 30.0_tr, 30.0_tr, 30.0_tr};
	inline static const std::array<wpi::units::angular_velocity::revolutions_per_minute_t, 8> m_passingLauncherVelocityArray = {1900.0_rpm, 2150.0_rpm, 2450.0_rpm, 2500.0_rpm, 3000.0_rpm, 3600.0_rpm, 4300.0_rpm, 5500.0_rpm};
	// All values in turns are actually Degree's

	// Cached motor status signals for performance optimization
	// These are refreshed once per loop in RunCommonTasks() to avoid multiple CAN bus queries
	wpi::units::angular_velocity::turns_per_second_t m_cachedLauncherVelocity = 0.0_tps;
	wpi::units::angle::turn_t m_cachedHoodPosition = 0.0_tr;
	wpi::units::angle::degree_t m_cachedTurretPosition = 0.0_deg;
	wpi::units::current::ampere_t m_cachedLauncherCurrent = 0.0_A;

	wpi::units::angle::turn_t m_passingHoodTargetAngle = 25.0_tr;
	wpi::units::angular_velocity::revolutions_per_minute_t m_passingLauncherTargetVelocity = 2500.0_rpm;

	// logging paths
	static constexpr std::string_view m_loggingLauncherTargetPath = "/Launcher/TargetLauncherVelocity";
	static constexpr std::string_view m_loggingHoodTargetPath = "/Launcher/HoodTargetAngle";
	static constexpr std::string_view m_loggingTurretAngleTargetPath = "/Launcher/TargetTurretAngle";
	static constexpr std::string_view m_loggingLauncherStatePath = "/Launcher/State";
	static constexpr std::string_view m_loggingProtectedModePath = "/Launcher/IsProtectedMode";
	static constexpr std::string_view m_loggingTurnsUnits = "Turns";

	static constexpr std::string_view m_loggingHoodErrorPath = "Launcher/HoodError";
	static constexpr std::string_view m_loggingLauncherSpeedErrorPath = "/Launcher/LauncherSpeedError";
	static constexpr std::string_view m_loggingLaunchingZonePath = "Launcher/IsLaunchingZone";
	static constexpr std::string_view m_loggingTurretAtTargetPath = "Launcher/IsTurretAtTarget";
	static constexpr std::string_view m_loggingChassisVelocitiesPath = "Launcher/IsChassisVelocities";

	static constexpr std::string_view m_loggingTurnsUnitsPath = "Turns";
	static constexpr std::string_view m_loggingRPMUnits = "RPM";

	bool m_turretEnabled = true;
	bool m_turretEnabledButtonReleased = true;

	wpi::units::current::ampere_t m_isLaunchingCurrentThreshold = 21.0_A;
	wpi::Timer m_launchCurrentTimer;
	wpi::units::time::second_t m_isLaunchingTimeThreshold = 1.0_s;
	bool m_hasValidTurretAngle = false;
	bool m_cachedHoodError = false;
	bool m_cachedLauncherSpeedError = false;
	bool m_cachedinLaunchzone = false;
	bool m_cachedIsChassisVelocities = false;
	bool m_cachedTurretAtTarget = false;
	bool m_turretHasReset = false;
	AllianceZoneManager *m_allianceZoneManager;
	DeadZoneManager *m_deadZoneManager;

	// Agitate Spindexer
	wpi::units::angle::degree_t m_minSpindexerTarget;
	wpi::units::angle::degree_t m_maxSpindexerTarget;
	bool m_minReached;
	static constexpr wpi::units::angle::degree_t m_spindexerTargetAng{30};
	wpi::units::length::inch_t m_distanceToTarget{0.0};
};