//====================================================================================================================================================
// Copyright 2026 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
// This file was automatically generated by the Team 302 code generator version 20.26.00.01
// Generated on Saturday, January 31, 2026 2:50:23 PM

// C++ Includes
#include <string>

// FRC includes

// Team 302 includes
#include "mechanisms/Launcher/LauncherTuningState.h"
#include "teleopcontrol/TeleopControl.h"
#include "teleopcontrol/TeleopControlFunctions.h"
#include "utils/logging/debug/Logger.h"

// Third Party Includes

using namespace std;
using namespace LauncherStates;

/// @class ExampleForwardState
/// @brief information about the control (open loop, closed loop position, closed loop velocity, etc.) for a mechanism state
LauncherTuningState::LauncherTuningState(std::string stateName,
										 int stateId,
										 Launcher *mech,
										 RobotIdentifier activeRobotId) : State(stateName, stateId), m_mechanism(mech), m_RobotId(activeRobotId)
{
}

void LauncherTuningState::Init()
{
	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, string("ArrivedAt"), string("LauncherTuningState"), string("Init"));

	if (m_RobotId == RobotIdentifier::COMP_BOT_302)
		InitCompBot302();
}

void LauncherTuningState::InitCompBot302()
{
	m_mechanism->UpdateTargetTransferPercentOut(m_transferTarget);
	m_mechanism->UpdateTargetIndexerPercentOut(m_indexerTarget);
	m_mechanism->UpdateTargetHoodPercentOut(m_hoodTarget);
}

void LauncherTuningState::Run()
{
	double manualHoodPercentOut = TeleopControl::GetInstance()->GetAxisValue(TeleopControlFunctions::UPDATE_DEPOT_PASSING_TARGET_X);
	if (abs(manualHoodPercentOut) < 0.075)
	{
		manualHoodPercentOut = 0;
	}

	if (TeleopControl::GetInstance()->IsButtonPressed(TeleopControlFunctions::UPDATE_TARGET_OFFSET_UP))
	{
		if (m_speedUpButtonReleased)
		{
			m_launcherPercentOut += 0.05;
			m_launcherTarget += wpi::units::angular_velocity::revolutions_per_minute_t(50);
		}
		m_speedUpButtonReleased = false;
	}
	else if (TeleopControl::GetInstance()->IsButtonPressed(TeleopControlFunctions::UPDATE_TARGET_OFFSET_DOWN))
	{
		if (m_speedDownButtonReleased)
		{
			m_launcherPercentOut -= 0.05;
			m_launcherTarget -= wpi::units::angular_velocity::revolutions_per_minute_t(50);
		}
		m_speedDownButtonReleased = false;
	}
	else
	{
		m_speedUpButtonReleased = true;
		m_speedDownButtonReleased = true;
	}

	if (m_tuningLauncherPercentOut)
	{
		m_mechanism->UpdateTargetLauncherPercentOut(m_launcherPercentOut);
		double manualTurretPercentOut = TeleopControl::GetInstance()->GetAxisValue(TeleopControlFunctions::UPDATE_OUTPOST_PASSING_TARGET_Y);
		if (abs(manualTurretPercentOut) < 0.075)
		{
			manualTurretPercentOut = 0;
		}
		m_mechanism->UpdateTargetTurretPercentOut(manualTurretPercentOut);
	}
	else
	{
		m_mechanism->UpdateTargetLauncherVelocityRPS(m_launcherTarget);
		m_mechanism->UpdateTargetTurretPositionDegreesTurret(m_mechanism->GetTargetTurretAngle());
	}

	m_mechanism->UpdateTargetHoodPercentOut(manualHoodPercentOut);

	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, string("LauncherTuningState"), string("Launcher Target RPM"), m_launcherTarget.value());
	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, string("LauncherTuningState"), string("Launcher Percent Out"), m_launcherPercentOut);
	wpi::units::length::inch_t distanceToTarget = RebuiltTargetCalculator::GetInstance()->CalculateMechanismDistanceToTarget();
	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, string("LauncherTuningState"), "Distance", distanceToTarget.value());
}

void LauncherTuningState::Exit()
{
	// Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, string("ArrivedAt"), string("LauncherTuningState"), string("Exit"));
}

bool LauncherTuningState::AtTarget()
{
	// Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, string("ArrivedAt"), string("LauncherTuningState"), string("AtTarget"));

	bool atTarget = false;
	return atTarget;
}

bool LauncherTuningState::IsTransitionCondition(bool considerGamepadTransitions)
{
	// To get the current state use m_mechanism->GetCurrentState()
	return m_mechanism->IsTuningLauncherMode();
}
