//====================================================================================================================================================
// Copyright 2026 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
// This file was automatically generated by the Team 302 code generator version 2026.1.0

#include "mechanisms/intake/commands/IntakeExpelCommand.h"
#include "mechanisms/intake/Intake.h"

// Unit Includes
#include <units/angle.h>

using namespace IntakeCommands;

static constexpr double m_intakeTarget{-1.0};
static constexpr units::angle::turn_t m_extenderTarget{-0.5};

IntakeExpelCommand::IntakeExpelCommand(Intake *mechanism) : m_mechanism(mechanism)
{
    AddRequirements(m_mechanism);
    SetName("IntakeExpel");
}

void IntakeExpelCommand::Initialize()
{
    m_mechanism->SetCurrentState(Intake::STATE_EXPEL);

    // Motor targets for Expel
    m_mechanism->UpdateTargetIntakePercentOut(m_intakeTarget);
    m_mechanism->UpdateTargetExtenderPositionDeg(m_extenderTarget);

    m_mechanism->PublishIntakeMode(false);
}

void IntakeExpelCommand::Execute()
{
}

void IntakeExpelCommand::End(bool interrupted)
{
}

bool IntakeExpelCommand::IsFinished()
{
    return false; // Default continuous execution
}