
//====================================================================================================================================================
// Copyright 2026 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
// This file was automatically generated by the Team 302 code generator version 2026.1.0

#include "mechanisms/intake/commands/IntakeLaunchCommand.h"
#include "mechanisms/intake/Intake.h"

#include <frc/DriverStation.h>

// Unit Includes
#include <units/angle.h>

using namespace IntakeCommands;

static constexpr double m_intakeTarget{1.0};
static constexpr units::angle::turn_t m_extenderTarget{20.0_tr};

IntakeLaunchCommand::IntakeLaunchCommand(Intake *mechanism) : m_mechanism(mechanism)
{
    AddRequirements(m_mechanism);
    SetName("IntakeLaunch");
}

void IntakeLaunchCommand::Initialize()
{
    m_mechanism->SetCurrentState(Intake::STATE_LAUNCH);

    // Motor targets for Launch
    m_mechanism->UpdateTargetIntakePercentOut(m_intakeTarget);
    m_mechanism->UpdateTargetExtenderPositionDeg(m_extenderTarget);

    m_bumpCounter = 0;
    m_currentExtenderBumpTarget = 0.0;
    m_mechanism->PublishIntakeMode(false);
}

void IntakeLaunchCommand::Execute()
{
    BumpIntake();
}

void IntakeLaunchCommand::End(bool interrupted)
{
}

bool IntakeLaunchCommand::IsFinished()
{
    return false; // Default continuous execution
}

void IntakeLaunchCommand::BumpIntake()
{
    // Periodically "bump" the extender during autonomous launching (moved from LaunchState).
    if ((m_bumpCounter > m_counterMax) && frc::DriverStation::IsAutonomous())
    {
        m_currentExtenderBumpTarget = (m_currentExtenderBumpTarget > 0) ? m_extenderTargetDown : m_extenderTargetUp;
        m_mechanism->UpdateTargetExtenderPercentOut(m_currentExtenderBumpTarget);
        m_bumpCounter = 0;
    }
    else
    {
        m_bumpCounter++;
    }
}