//====================================================================================================================================================
// Copyright 2026 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
// This file was automatically generated by the Team 302 code generator version 20.26.00.01
// Generated on Friday, January 23, 2026 7:56:41 PM

#pragma once

#include <memory>
#include <string>

// FRC Includes
#include "wpi/nt/NetworkTable.hpp"

#include "ctre/phoenix6/CANcoder.hpp"
#include "ctre/phoenix6/CANdi.hpp"
#include "ctre/phoenix6/TalonFX.hpp"
#include "ctre/phoenix6/configs/Configuration.hpp"
#include "ctre/phoenix6/configs/Configurator.hpp"
#include "ctre/phoenix6/controls/Follower.hpp"
#include "ctre/phoenix6/signals/SpnEnums.hpp"
#include "wpi/hardware/pneumatic/Solenoid.hpp"

#include "mechanisms/base/BaseMech.h"
#include "mechanisms/controllers/ControlData.h"
#include "state/IRobotStateChangeSubscriber.h"
#include "state/RobotStateChanges.h"
#include "state/StateMgr.h"

#include "chassis/ChassisConfigMgr.h"
#include "mechanisms/configs/MechanismConfigMgr.h"
#include "mechanisms/configs/RobotElementNames.h"
// #include "utils/logging/signals/DragonDataLogger.h"
//  SystemCore TO DO: Figure out how logging works in SystemCore

#include "RobotIdentifier.h"

class Climber : public BaseMech, public StateMgr, public IRobotStateChangeSubscriber //, public DragonDataLogger
{
public:
	enum STATE_NAMES
	{
		STATE_OFF,
		STATE_WANT_TO_CLIMB,
		STATE_PREPARE_TO_CLIMB,
		STATE_L1CLIMB,
		STATE_L3CLIMB,
		STATE_EXIT,
		STATE_AUTON_L1CLIMB
	};

	Climber(RobotIdentifier activeRobotId);
	Climber() = delete;
	~Climber() = default;

	void CreateCompBot302();
	void InitializeCompBot302();

	/// @brief Set the control constants (e.g. PIDF values).
	/// @param indentifier the motor controller usage to identify the motor
	/// @param slot position on the motor controller to set
	/// @param pid control data / constants
	virtual void SetControlConstants(RobotElementNames::MOTOR_CONTROLLER_USAGE indentifier, int slot, ControlData pid);

	/// @brief update the output to the mechanism using the current controller and target value(s)
	virtual void Update();

	void UpdateTargetClimberPositionDegree(wpi::units::angle::turn_t position)
	{
		m_climberPositionDegree.Position = position;
		m_climberActiveTarget = &m_climberPositionDegree.WithSlot(0);
	}

	void CreateAndRegisterStates();
	void Cyclic();
	void RunCommonTasks() override;
	// void DataLog(uint64_t timestamp) override; // SystemCore TO DO: Figure out how logging works in SystemCore

	void NotifyStateUpdate(RobotStateChanges::StateChange stchange, bool value) override;

	RobotIdentifier getActiveRobotId() { return m_activeRobotId; }

	ctre::phoenix6::hardware::TalonFX *GetClimber() const { return m_climber; }
	ctre::phoenix6::hardware::CANdi *GetCANdi() const { return m_CANdi; }
	ControlData *GetPositionDegree() const { return m_positionDegree; }

	bool IsClimbMode() const { return m_climbModeStatus; }
	bool IsAllowedToClimb() const { return m_allowedToClimb; };
	bool IsDriveToDone() const { return m_driveToFinished; };
	bool IsClimberExtended() const { return m_CANdi->GetS2Closed().GetValue(); };
	bool IsClimberRetracted() const { return m_CANdi->GetS1Closed().GetValue(); };

	static std::map<std::string, STATE_NAMES> stringToSTATE_NAMESEnumMap;
	static std::map<STATE_NAMES, std::string> STATE_NAMESEnumToStringMap;

	void SetCurrentState(int state, bool run) override;
	std::string GetCurrentStateName();

	void UpdateTargetClimberPercentOut(double percentOut)
	{
		m_ClimberPercentOut.Output = percentOut;
		m_climberActiveTarget = &m_ClimberPercentOut;
	}
	void ManualClimb(wpi::units::angle::degree_t climbTarget, double manualClimberPercent);

	// Hand-created Methods

	wpi::units::angle::degree_t GetPigeonPitch();
	wpi::units::angular_velocity::degrees_per_second_t GetMaxAngularVelocity() const { return m_maxAngularVelocity; }

protected:
	RobotIdentifier m_activeRobotId;
	std::string m_ntName;

	ControlData *GetControlData(std::string name) override;

private:
	std::unordered_map<std::string, STATE_NAMES> m_stateMap;

	ctre::phoenix6::hardware::TalonFX *m_climber;
	ctre::phoenix6::hardware::CANdi *m_CANdi;

	ControlData *m_positionDegree;

	void InitializeTalonFXClimberCompBot302();

	ctre::phoenix6::controls::MotionMagicExpoTorqueCurrentFOC m_climberPositionDegree{0_tr};
	ctre::phoenix6::controls::ControlRequest *m_climberActiveTarget;
	ctre::phoenix6::controls::DutyCycleOut m_ClimberPercentOut{0.0};
	double m_percentOutScale = 0.5;
	double m_holdPercentOut = 0;

	bool m_climbModeStatus;
	bool m_allowedToClimb;
	bool m_driveToFinished;
	subsystems::CommandSwerveDrivetrain *m_chassis; ///< pointer to chassis for pitch

	wpi::units::angular_velocity::degrees_per_second_t m_maxAngularVelocity = 360_deg_per_s;

	// logging paths
	static constexpr std::string_view m_climberStatePath = "/Climber/State";
};