//====================================================================================================================================================
// Copyright 2026 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
// This file was automatically generated by the Team 302 code generator version 20.26.00.00
// Generated on Thursday, January 22, 2026 11:43:04 PM

#pragma once
#include <string>

#include "state/State.h"
#include "mechanisms/Climber/Climber.h"
#include <wpi/math/controller/ProfiledPIDController.hpp>

using namespace std;

namespace ClimberStates
{
	class ExitState : public State
	{
	public:
		ExitState() = delete;
		ExitState(std::string stateName,
				  int stateId,
				  Climber *mech,
				  RobotIdentifier activeRobotId);
		~ExitState() = default;
		void Init() override;
		void Run() override;
		void Exit() override;
		bool AtTarget() override;
		bool IsTransitionCondition(bool considerGamepadTransitions) override;

	private:
		Climber *m_mechanism;
		void InitCompBot302();
		RobotIdentifier m_RobotId;

		const wpi::units::angle::degree_t m_climberTarget = wpi::units::angle::degree_t(0);

		const double m_rotationKP = 0.0;
		const double m_rotationKI = 0.0;
		const double m_rotationKD = 0.0;

		const wpi::units::angular_velocity::degrees_per_second_t kMaxVelocity = 4_deg_per_s;
		const wpi::units::angular_acceleration::degrees_per_second_squared_t kMaxAcceleration = 4_deg_per_s_sq;

		const wpi::math::TrapezoidProfile<wpi::units::angle::degrees>::Constraints m_rotationConstraints{kMaxVelocity, kMaxAcceleration};

		wpi::math::ProfiledPIDController<wpi::units::angle::degrees> m_rotationPID{m_rotationKP, m_rotationKI, m_rotationKD, m_rotationConstraints, 20_ms};
	};
}
