<!ELEMENT auton (snippet | primitive)* >

<!ELEMENT snippet EMPTY>
<!ATTLIST snippet file CDATA #IMPLIED>

<!ELEMENT primitive (zone* ) >
<!ATTLIST primitive 
          id                ( DO_NOTHING | TRAJECTORY_DRIVE | RESET_POSITION | RESET_POSITION_NO_VISION | DRIVE_STOP_MECH) "DO_NOTHING"
		  time				CDATA #IMPLIED
		  choreoname		CDATA #IMPLIED
		  driveToOption				    ( DRIVE_TO_HUB | DRIVE_OVER_BUMP | DRIVE_TO_DEPOT | DRIVE_TO_OUTPOST | DRIVE_TO_TOWER | NONE ) "NONE"
		  intakeState		 ( STATE_OFF | STATE_INTAKE | STATE_EXPEL | STATE_LAUNCH | STATE_LOAD_HOPPER ) #IMPLIED
		  launcherState		 ( STATE_OFF | STATE_INITIALIZE | STATE_IDLE | STATE_PREPARE_TO_LAUNCH | STATE_LAUNCH | STATE_LAUNCHER_TUNING | STATE_MANUAL_LAUNCH ) #IMPLIED
>


<!ELEMENT zone EMPTY >
<!ATTLIST zone
		filename CDATA #REQUIRED
		
>


