<!ELEMENT auton (zone) >

<!ELEMENT zone EMPTY >
<!ATTLIST zone
    ygrid1             		(  1 |  2 |  3 |  4 |  5 |  6 |  7 |  8 |  9 | 
							  10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 
                              20 | 21 | 22 | 23 | 24 | 25 | 26 | 27 | 28 | 29 | 
                              30 | 31 | 32 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 
                              40 | 41 | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 | 
                              50 | 51 | 52 | 53 | 54 ) "1"
    xgrid1             		(  1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 
                               10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 
                               19 | 20 | 21 | 22 | 23 | 24 | 25 | 26 | 27) "1"
    ygrid2             		(  1 |  2 |  3 |  4 |  5 |  6 |  7 |  8 |  9 | 
							  10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 
                              20 | 21 | 22 | 23 | 24 | 25 | 26 | 27 | 28 | 29 | 
                              30 | 31 | 32 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 
                              40 | 41 | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 | 
                              50 | 51 | 52 | 53 | 54 ) "1"
    xgrid2             		(  1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 
                               10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 
                               19 | 20 | 21 | 22 | 23 | 24 | 25 | 26 | 27) "1"

    x1_rect CDATA #IMPLIED
    y1_rect CDATA #IMPLIED
    x2_rect CDATA #IMPLIED
    y2_rect CDATA #IMPLIED


    circlex                 CDATA #IMPLIED
    circley                 CDATA #IMPLIED
    radius                  CDATA #IMPLIED                

    pathUpdateOption 	    ( DRIVE_TO_HUB | DRIVE_OVER_BUMP | DRIVE_TO_DEPOT | DRIVE_TO_OUTPOST | DRIVE_TO_TOWER | NOTHING ) "NOTHING"         
    
    chassisOption           ( NO_VISION ) "NO_VISION"
    avoidOption             ( ROBOT_COLLISION | NO_AVOID_OPTION ) "NO_AVOID_OPTION"
    headingOption           ( MAINTAIN | SPECIFIED_ANGLE | FACE_GAME_PIECE | IGNORE) "IGNORE"
    launcherState		( STATE_OFF | STATE_IDLE | STATE_PREPARE_TO_LAUNCH ) "STATE_IDLE"
    intakeState		    ( STATE_OFF | STATE_INTAKE | STATE_EXPEL ) "STATE_OFF"
	climberState		( STATE_OFF | STATE_WANT_TO_CLIMB ) "STATE_OFF"


    allianceColor ( RED | BLUE | BOTH ) "BOTH"


    
>


